In [91]:
import pandas as pd

In [92]:
import json
import time
def transform_csv(file_path: str, users: bool = True):
    """
    Converts the CSV format into JSON-like to send it as an API payload. The function creates a list with JSON items, each item has keys based on the CSV column names and each key has a single value from the data related to their respective column.
    ## **Parameters**
    - ```file_path```: Path to the file that will be processed.
    - ```users```: Determine whether the file is for the table "users", otherwise, the table will be "viewing_sessions".

    ## **Returns**
    A dictionary with the table name and its data:\n
    {'table': 'table_name',\n
    'data': [\n
        \n{
        'column1': 'value',\n
        'column2': 'value',
        ...
        },\n
        {
        'column1': 'value',
        'column2': 'value',
        ...
        }, ...\n
    ]
    """

    df = pd.read_csv(file_path)
    if users == True:
        table_name = 'users'
    elif users == False:
        table_name = 'viewing_sessions'
    df.to_json(path_or_buf=f"./data/{table_name}_processed.json", orient='records')
    #Giving a few seconds to process and save the file.
    time.sleep(3)
    with open(f"./data/{table_name}_processed.json", "r") as json_raw:
        content_processed = json.load(json_raw)
    return content_processed

In [93]:
transform_csv('./data/users.csv', True)
transform_csv('./data/viewing_sessions.csv', False)

FileNotFoundError: [Errno 2] No such file or directory: './data/users.csv'

In [ ]:
import json
idk = []
with open('./data/content.json','r') as file: content_json = json.load(file)
content = content_json.items()
for key, documents in content:
    for docs in documents:
        collection = key
        data = docs
        my_dict = {}
        if "M" in data["_id"]:
            for key_2 in data:
                my_dict[key_2] = data[key_2]
            idk.append(my_dict)
            payload = {
            'collection': collection,
            'data': idk
        }
payload

{'collection': 'movies',
 'data': [{'_id': 'M001',
   'title': 'Advanced World',
   'genre': ['Sci-Fi', 'Horror', 'Drama'],
   'duration_minutes': 179,
   'release_year': 2020,
   'rating': 3.5,
   'views_count': 66721,
   'production_budget': 220088717},
  {'_id': 'M002',
   'title': 'Neural Signal',
   'genre': ['Animation', 'Horror'],
   'duration_minutes': 146,
   'release_year': 2021,
   'rating': 2.8,
   'views_count': 11128,
   'production_budget': 23593231},
  {'_id': 'M003',
   'title': 'An Stream',
   'genre': ['Action'],
   'duration_minutes': 102,
   'release_year': 2023,
   'rating': 1.9,
   'views_count': 75949,
   'production_budget': 83166461},
  {'_id': 'M004',
   'title': 'Binary Journey',
   'genre': ['Thriller', 'Documentary'],
   'duration_minutes': 146,
   'release_year': 2022,
   'rating': 3.0,
   'views_count': 85958,
   'production_budget': 46298444},
  {'_id': 'M005',
   'title': 'Lost Data',
   'genre': ['Horror', 'Romance'],
   'duration_minutes': 169,
   'release_year': 2022,
   'rating': 4.7,
   'views_count': 56808,
   'production_budget': 67293750},
  {'_id': 'M006',
   'title': 'Ultimate Mystery',
   'genre': ['Action', 'Animation', 'Horror'],
   'duration_minutes': 157,
   'release_year': 2024,
   'rating': 1.1,
   'views_count': 148876,
   'production_budget': 234348717},
  {'_id': 'M007',
   'title': 'Code',
   'genre': ['Comedy', 'Romance'],
   'duration_minutes': 136,
   'release_year': 2022,
   'rating': 3.1,
   'views_count': 9228,
   'production_budget': 35028167},
  {'_id': 'M008',
   'title': 'Digital Protocol',
   'genre': ['Documentary', 'Romance'],
   'duration_minutes': 155,
   'release_year': 2023,
   'rating': 3.7,
   'views_count': 125068,
   'production_budget': 49545701},
  {'_id': 'M009',
   'title': 'Tale',
   'genre': ['Drama', 'Horror'],
   'duration_minutes': 90,
   'release_year': 2023,
   'rating': 4.4,
   'views_count': 37911,
   'production_budget': 146895476},
  {'_id': 'M010',
   'title': 'An Code 2',
   'genre': ['Comedy', 'Romance', 'Action'],
   'duration_minutes': 174,
   'release_year': 2021,
   'rating': 3.5,
   'views_count': 78005,
   'production_budget': 224671521},
  {'_id': 'M011',
   'title': 'Algorithm',
   'genre': ['Drama', 'Animation', 'Horror'],
   'duration_minutes': 81,
   'release_year': 2023,
   'rating': 2.7,
   'views_count': 92634,
   'production_budget': 20512281},
  {'_id': 'M012',
   'title': 'Quest 5',
   'genre': ['Comedy'],
   'duration_minutes': 104,
   'release_year': 2023,
   'rating': 2.4,
   'views_count': 59155,
   'production_budget': 36408859},
  {'_id': 'M013',
   'title': 'Mystery',
   'genre': ['Documentary', 'Drama'],
   'duration_minutes': 178,
   'release_year': 2020,
   'rating': 1.6,
   'views_count': 61328,
   'production_budget': 16064411},
  {'_id': 'M014',
   'title': 'Kingdom',
   'genre': ['Thriller', 'Action'],
   'duration_minutes': 122,
   'release_year': 2021,
   'rating': 4.2,
   'views_count': 138918,
   'production_budget': 202395249},
  {'_id': 'M015',
   'title': 'Quantum Code',
   'genre': ['Animation', 'Documentary', 'Sci-Fi'],
   'duration_minutes': 177,
   'release_year': 2021,
   'rating': 2.4,
   'views_count': 13807,
   'production_budget': 227198245},
  {'_id': 'M016',
   'title': 'A Database',
   'genre': ['Drama', 'Documentary'],
   'duration_minutes': 95,
   'release_year': 2023,
   'rating': 3.0,
   'views_count': 81858,
   'production_budget': 6729979},
  {'_id': 'M017',
   'title': 'Adventure',
   'genre': ['Action', 'Documentary', 'Horror'],
   'duration_minutes': 97,
   'release_year': 2020,
   'rating': 4.6,
   'views_count': 132014,
   'production_budget': 50839665},
  {'_id': 'M018',
   'title': 'Mystery',
   'genre': ['Comedy', 'Action'],
   'duration_minutes': 84,
   'release_year': 2023,
   'rating': 3.6,
   'views_count': 81531,
   'production_budget': 158431993},
  {'_id': 'M019',
   'title': 'Final Stream',
   'genre': ['Action'],
   'duration_minutes': 83,
   'release_year': 2023,
   'rating': 2.3,
   'views_count': 144211,
   'production_budget': 114952801},
  {'_id': 'M020',
   'title': 'Quest',
   'genre': ['Thriller', 'Action', 'Drama'],
   'duration_minutes': 108,
   'release_year': 2022,
   'rating': 3.1,
   'views_count': 47873,
   'production_budget': 250548961},
  {'_id': 'M021',
   'title': 'Tale',
   'genre': ['Drama', 'Horror'],
   'duration_minutes': 148,
   'release_year': 2020,
   'rating': 4.9,
   'views_count': 168298,
   'production_budget': 62478620},
  {'_id': 'M022',
   'title': 'Quantum System',
   'genre': ['Horror'],
   'duration_minutes': 147,
   'release_year': 2023,
   'rating': 4.7,
   'views_count': 116580,
   'production_budget': 73128204},
  {'_id': 'M023',
   'title': 'Smart Story',
   'genre': ['Horror'],
   'duration_minutes': 147,
   'release_year': 2022,
   'rating': 3.3,
   'views_count': 36200,
   'production_budget': 12509378},
  {'_id': 'M024',
   'title': 'First Mystery',
   'genre': ['Horror'],
   'duration_minutes': 159,
   'release_year': 2020,
   'rating': 4.2,
   'views_count': 117924,
   'production_budget': 146907831},
  {'_id': 'M025',
   'title': 'An Protocol',
   'genre': ['Comedy'],
   'duration_minutes': 162,
   'release_year': 2020,
   'rating': 4.0,
   'views_count': 26519,
   'production_budget': 49021276},
  {'_id': 'M026',
   'title': 'Lost Kingdom',
   'genre': ['Documentary', 'Drama', 'Action'],
   'duration_minutes': 163,
   'release_year': 2024,
   'rating': 2.6,
   'views_count': 113230,
   'production_budget': 90625130},
  {'_id': 'M027',
   'title': 'Quantum Story',
   'genre': ['Thriller', 'Horror', 'Sci-Fi'],
   'duration_minutes': 128,
   'release_year': 2023,
   'rating': 1.2,
   'views_count': 19816,
   'production_budget': 150283990},
  {'_id': 'M028',
   'title': 'Final Kingdom',
   'genre': ['Comedy', 'Horror', 'Drama'],
   'duration_minutes': 175,
   'release_year': 2023,
   'rating': 1.7,
   'views_count': 87291,
   'production_budget': 8816404},
  {'_id': 'M029',
   'title': 'System',
   'genre': ['Documentary'],
   'duration_minutes': 123,
   'release_year': 2023,
   'rating': 1.8,
   'views_count': 27793,
   'production_budget': 30738350},
  {'_id': 'M030',
   'title': 'Database 4',
   'genre': ['Drama', 'Action'],
   'duration_minutes': 145,
   'release_year': 2020,
   'rating': 1.3,
   'views_count': 98063,
   'production_budget': 100987742},
  {'_id': 'M031',
   'title': 'Empire',
   'genre': ['Action', 'Animation', 'Drama'],
   'duration_minutes': 104,
   'release_year': 2020,
   'rating': 4.9,
   'views_count': 114316,
   'production_budget': 184475405},
  {'_id': 'M032',
   'title': 'A Code',
   'genre': ['Thriller', 'Action'],
   'duration_minutes': 133,
   'release_year': 2024,
   'rating': 3.4,
   'views_count': 83014,
   'production_budget': 283617949},
  {'_id': 'M033',
   'title': 'Dark Stream',
   'genre': ['Action', 'Animation'],
   'duration_minutes': 119,
   'release_year': 2023,
   'rating': 2.9,
   'views_count': 54865,
   'production_budget': 193790052},
  {'_id': 'M034',
   'title': 'Stream',
   'genre': ['Romance', 'Sci-Fi', 'Action'],
   'duration_minutes': 151,
   'release_year': 2020,
   'rating': 4.9,
   'views_count': 41348,
   'production_budget': 122112109},
  {'_id': 'M035',
   'title': 'Lost System 5',
   'genre': ['Thriller', 'Romance'],
   'duration_minutes': 112,
   'release_year': 2021,
   'rating': 1.8,
   'views_count': 64414,
   'production_budget': 2127388},
  {'_id': 'M036',
   'title': 'Quest',
   'genre': ['Romance', 'Animation'],
   'duration_minutes': 100,
   'release_year': 2020,
   'rating': 2.9,
   'views_count': 90335,
   'production_budget': 12670028},
  {'_id': 'M037',
   'title': 'Quest',
   'genre': ['Animation', 'Comedy', 'Documentary'],
   'duration_minutes': 90,
   'release_year': 2022,
   'rating': 1.2,
   'views_count': 13250,
   'production_budget': 33987762},
  {'_id': 'M038',
   'title': 'Data',
   'genre': ['Animation', 'Documentary'],
   'duration_minutes': 161,
   'release_year': 2021,
   'rating': 3.6,
   'views_count': 47672,
   'production_budget': 15316213},
  {'_id': 'M039',
   'title': 'Lost Cloud',
   'genre': ['Horror', 'Drama', 'Action'],
   'duration_minutes': 103,
   'release_year': 2020,
   'rating': 2.8,
   'views_count': 48310,
   'production_budget': 202148811},
  {'_id': 'M040',
   'title': 'Quest',
   'genre': ['Comedy', 'Documentary', 'Drama'],
   'duration_minutes': 171,
   'release_year': 2022,
   'rating': 2.2,
   'views_count': 52925,
   'production_budget': 1600669},
  {'_id': 'M041',
   'title': 'Infinite Story',
   'genre': ['Horror', 'Thriller'],
   'duration_minutes': 117,
   'release_year': 2021,
   'rating': 4.2,
   'views_count': 129104,
   'production_budget': 186923029},
  {'_id': 'M042',
   'title': 'Advanced System 2',
   'genre': ['Documentary'],
   'duration_minutes': 163,
   'release_year': 2020,
   'rating': 3.3,
   'views_count': 44583,
   'production_budget': 42856949},
  {'_id': 'M043',
   'title': 'Hidden Empire',
   'genre': ['Horror'],
   'duration_minutes': 134,
   'release_year': 2024,
   'rating': 4.1,
   'views_count': 290064,
   'production_budget': 128140036},
  {'_id': 'M044',
   'title': 'Cyber Cloud 4',
   'genre': ['Animation', 'Thriller'],
   'duration_minutes': 134,
   'release_year': 2024,
   'rating': 3.3,
   'views_count': 8992,
   'production_budget': 8120314},
  {'_id': 'M045',
   'title': 'First Database',
   'genre': ['Animation', 'Action'],
   'duration_minutes': 123,
   'release_year': 2023,
   'rating': 3.1,
   'views_count': 115282,
   'production_budget': 182644208},
  {'_id': 'M046',
   'title': 'Binary Signal',
   'genre': ['Animation', 'Documentary', 'Thriller'],
   'duration_minutes': 147,
   'release_year': 2023,
   'rating': 1.9,
   'views_count': 18247,
   'production_budget': 24000248},
  {'_id': 'M047',
   'title': 'Story',
   'genre': ['Drama'],
   'duration_minutes': 120,
   'release_year': 2023,
   'rating': 3.3,
   'views_count': 5974,
   'production_budget': 18448764},
  {'_id': 'M048',
   'title': 'Tale',
   'genre': ['Horror', 'Romance', 'Documentary'],
   'duration_minutes': 104,
   'release_year': 2021,
   'rating': 4.9,
   'views_count': 178486,
   'production_budget': 59289648},
  {'_id': 'M049',
   'title': 'Neural Cloud 2',
   'genre': ['Drama', 'Sci-Fi', 'Action'],
   'duration_minutes': 126,
   'release_year': 2020,
   'rating': 3.7,
   'views_count': 33051,
   'production_budget': 135871052},
  {'_id': 'M050',
   'title': 'Infinite Protocol',
   'genre': ['Thriller', 'Documentary'],
   'duration_minutes': 96,
   'release_year': 2021,
   'rating': 2.0,
   'views_count': 53173,
   'production_budget': 39370044},
  {'_id': 'M051',
   'title': 'A Algorithm',
   'genre': ['Animation'],
   'duration_minutes': 155,
   'release_year': 2022,
   'rating': 4.8,
   'views_count': 136410,
   'production_budget': 106311259},
  {'_id': 'M052',
   'title': 'Adventure',
   'genre': ['Horror', 'Thriller', 'Sci-Fi'],
   'duration_minutes': 120,
   'release_year': 2021,
   'rating': 3.9,
   'views_count': 94063,
   'production_budget': 193008798},
  {'_id': 'M053',
   'title': 'Infinite Empire',
   'genre': ['Action'],
   'duration_minutes': 162,
   'release_year': 2022,
   'rating': 1.9,
   'views_count': 50863,
   'production_budget': 296179703},
  {'_id': 'M054',
   'title': 'Binary Stream',
   'genre': ['Action', 'Animation', 'Documentary'],
   'duration_minutes': 98,
   'release_year': 2021,
   'rating': 4.6,
   'views_count': 17832,
   'production_budget': 122289319},
  {'_id': 'M055',
   'title': 'Infinite Adventure',
   'genre': ['Thriller'],
   'duration_minutes': 142,
   'release_year': 2023,
   'rating': 3.6,
   'views_count': 121651,
   'production_budget': 37909361},
  {'_id': 'M056',
   'title': 'Binary Journey',
   'genre': ['Thriller', 'Action'],
   'duration_minutes': 88,
   'release_year': 2023,
   'rating': 3.6,
   'views_count': 105627,
   'production_budget': 140493022},
  {'_id': 'M057',
   'title': 'Journey',
   'genre': ['Drama', 'Sci-Fi'],
   'duration_minutes': 149,
   'release_year': 2022,
   'rating': 1.9,
   'views_count': 38409,
   'production_budget': 213938522},
  {'_id': 'M058',
   'title': 'Last Quest',
   'genre': ['Documentary', 'Animation', 'Romance'],
   'duration_minutes': 173,
   'release_year': 2020,
   'rating': 3.6,
   'views_count': 53146,
   'production_budget': 20440772},
  {'_id': 'M059',
   'title': 'System',
   'genre': ['Sci-Fi', 'Thriller', 'Drama'],
   'duration_minutes': 146,
   'release_year': 2020,
   'rating': 1.5,
   'views_count': 63578,
   'production_budget': 80650718},
  {'_id': 'M060',
   'title': 'Dark Kingdom',
   'genre': ['Thriller', 'Sci-Fi'],
   'duration_minutes': 122,
   'release_year': 2020,
   'rating': 4.9,
   'views_count': 196906,
   'production_budget': 107714280},
  {'_id': 'M061',
   'title': 'An Cloud',
   'genre': ['Drama', 'Comedy', 'Action'],
   'duration_minutes': 99,
   'release_year': 2022,
   'rating': 4.6,
   'views_count': 58038,
   'production_budget': 181262622},
  {'_id': 'M062',
   'title': 'Secret Empire',
   'genre': ['Horror'],
   'duration_minutes': 136,
   'release_year': 2024,
   'rating': 1.1,
   'views_count': 113496,
   'production_budget': 45559979},
  {'_id': 'M063',
   'title': 'Neural Cloud',
   'genre': ['Sci-Fi', 'Drama'],
   'duration_minutes': 104,
   'release_year': 2024,
   'rating': 4.5,
   'views_count': 241308,
   'production_budget': 52788131},
  {'_id': 'M064',
   'title': 'Virtual Adventure',
   'genre': ['Drama', 'Action'],
   'duration_minutes': 113,
   'release_year': 2024,
   'rating': 4.4,
   'views_count': 99105,
   'production_budget': 99191442},
  {'_id': 'M065',
   'title': 'Final Story',
   'genre': ['Documentary', 'Romance', 'Sci-Fi'],
   'duration_minutes': 102,
   'release_year': 2024,
   'rating': 1.9,
   'views_count': 107506,
   'production_budget': 92334091},
  {'_id': 'M066',
   'title': 'Last World',
   'genre': ['Animation'],
   'duration_minutes': 134,
   'release_year': 2024,
   'rating': 4.1,
   'views_count': 139206,
   'production_budget': 232940727},
  {'_id': 'M067',
   'title': 'Smart World',
   'genre': ['Documentary', 'Romance', 'Sci-Fi'],
   'duration_minutes': 126,
   'release_year': 2023,
   'rating': 4.0,
   'views_count': 125397,
   'production_budget': 233435578},
  {'_id': 'M068',
   'title': 'Protocol',
   'genre': ['Comedy', 'Thriller', 'Horror'],
   'duration_minutes': 169,
   'release_year': 2024,
   'rating': 4.2,
   'views_count': 110097,
   'production_budget': 100149438},
  {'_id': 'M069',
   'title': 'Last World',
   'genre': ['Horror'],
   'duration_minutes': 119,
   'release_year': 2022,
   'rating': 4.0,
   'views_count': 12355,
   'production_budget': 39301506},
  {'_id': 'M070',
   'title': 'Lost Adventure',
   'genre': ['Drama', 'Sci-Fi'],
   'duration_minutes': 171,
   'release_year': 2020,
   'rating': 1.7,
   'views_count': 5512,
   'production_budget': 218689270},
  {'_id': 'M071',
   'title': 'Cyber Tale',
   'genre': ['Sci-Fi', 'Drama', 'Comedy'],
   'duration_minutes': 102,
   'release_year': 2023,
   'rating': 4.3,
   'views_count': 292824,
   'production_budget': 139504878},
  {'_id': 'M072',
   'title': 'Secret Signal',
   'genre': ['Romance'],
   'duration_minutes': 125,
   'release_year': 2022,
   'rating': 1.6,
   'views_count': 60180,
   'production_budget': 8844926},
  {'_id': 'M073',
   'title': 'System',
   'genre': ['Documentary', 'Animation', 'Action'],
   'duration_minutes': 141,
   'release_year': 2021,
   'rating': 1.3,
   'views_count': 12675,
   'production_budget': 167251523},
  {'_id': 'M074',
   'title': 'Digital Database',
   'genre': ['Comedy'],
   'duration_minutes': 146,
   'release_year': 2022,
   'rating': 3.2,
   'views_count': 8998,
   'production_budget': 29227591},
  {'_id': 'M075',
   'title': 'Neural Journey',
   'genre': ['Sci-Fi', 'Thriller', 'Romance'],
   'duration_minutes': 125,
   'release_year': 2020,
   'rating': 4.2,
   'views_count': 84468,
   'production_budget': 296040480},
  {'_id': 'M076',
   'title': 'The Journey',
   'genre': ['Thriller', 'Documentary', 'Animation'],
   'duration_minutes': 166,
   'release_year': 2020,
   'rating': 2.4,
   'views_count': 78189,
   'production_budget': 27396354},
  {'_id': 'M077',
   'title': 'Signal',
   'genre': ['Romance'],
   'duration_minutes': 101,
   'release_year': 2021,
   'rating': 4.5,
   'views_count': 97638,
   'production_budget': 203590741},
  {'_id': 'M078',
   'title': 'Algorithm',
   'genre': ['Comedy', 'Romance', 'Documentary'],
   'duration_minutes': 155,
   'release_year': 2024,
   'rating': 1.6,
   'views_count': 28957,
   'production_budget': 13524987},
  {'_id': 'M079',
   'title': 'Secret Algorithm',
   'genre': ['Thriller'],
   'duration_minutes': 156,
   'release_year': 2022,
   'rating': 3.8,
   'views_count': 44993,
   'production_budget': 46138210},
  {'_id': 'M080',
   'title': 'Digital Empire',
   'genre': ['Comedy'],
   'duration_minutes': 99,
   'release_year': 2022,
   'rating': 3.5,
   'views_count': 51624,
   'production_budget': 49787105},
  {'_id': 'M081',
   'title': 'A Empire',
   'genre': ['Thriller'],
   'duration_minutes': 158,
   'release_year': 2023,
   'rating': 3.2,
   'views_count': 20857,
   'production_budget': 21843745},
  {'_id': 'M082',
   'title': 'Protocol',
   'genre': ['Romance', 'Action', 'Comedy'],
   'duration_minutes': 135,
   'release_year': 2023,
   'rating': 4.0,
   'views_count': 106275,
   'production_budget': 182661326},
  {'_id': 'M083',
   'title': 'Final World',
   'genre': ['Horror'],
   'duration_minutes': 116,
   'release_year': 2023,
   'rating': 1.1,
   'views_count': 147540,
   'production_budget': 9691644},
  {'_id': 'M084',
   'title': 'The Matrix',
   'genre': ['Drama', 'Comedy'],
   'duration_minutes': 141,
   'release_year': 2021,
   'rating': 2.2,
   'views_count': 40998,
   'production_budget': 49636072},
  {'_id': 'M085',
   'title': 'Lost Adventure',
   'genre': ['Action', 'Romance'],
   'duration_minutes': 150,
   'release_year': 2022,
   'rating': 4.4,
   'views_count': 185972,
   'production_budget': 272623780},
  {'_id': 'M086',
   'title': 'Data',
   'genre': ['Thriller', 'Horror', 'Animation'],
   'duration_minutes': 130,
   'release_year': 2021,
   'rating': 2.3,
   'views_count': 41342,
   'production_budget': 25908762},
  {'_id': 'M087',
   'title': 'A Data',
   'genre': ['Action', 'Romance', 'Drama'],
   'duration_minutes': 139,
   'release_year': 2020,
   'rating': 2.7,
   'views_count': 41100,
   'production_budget': 251619945},
  {'_id': 'M088',
   'title': 'Data',
   'genre': ['Romance'],
   'duration_minutes': 146,
   'release_year': 2023,
   'rating': 1.2,
   'views_count': 2689,
   'production_budget': 41797064},
  {'_id': 'M089',
   'title': 'Hidden Data',
   'genre': ['Horror', 'Sci-Fi', 'Romance'],
   'duration_minutes': 107,
   'release_year': 2021,
   'rating': 3.0,
   'views_count': 48176,
   'production_budget': 283777035},
  {'_id': 'M090',
   'title': 'Network',
   'genre': ['Comedy', 'Animation'],
   'duration_minutes': 86,
   'release_year': 2020,
   'rating': 2.6,
   'views_count': 38966,
   'production_budget': 41347239},
  {'_id': 'M091',
   'title': 'Empire',
   'genre': ['Animation', 'Romance'],
   'duration_minutes': 122,
   'release_year': 2022,
   'rating': 2.5,
   'views_count': 48892,
   'production_budget': 10832696},
  {'_id': 'M092',
   'title': 'Infinite Code',
   'genre': ['Comedy', 'Horror'],
   'duration_minutes': 145,
   'release_year': 2021,
   'rating': 2.1,
   'views_count': 56151,
   'production_budget': 16160068},
  {'_id': 'M093',
   'title': 'Digital Code',
   'genre': ['Horror', 'Drama'],
   'duration_minutes': 87,
   'release_year': 2024,
   'rating': 3.8,
   'views_count': 97083,
   'production_budget': 9974518},
  {'_id': 'M094',
   'title': 'Matrix',
   'genre': ['Action', 'Animation'],
   'duration_minutes': 173,
   'release_year': 2020,
   'rating': 1.2,

In [99]:
import json
idk = []
with open('../data/content.json','r') as file: content_json = json.load(file)
content = content_json.items()
values = []
for key, documents in content:
    for docs in documents:
        collection = key
        data = docs
        if "S" in data["_id"]:
            values.append(data)
payload ={
'collection': collection,
'data': values
}
jsoncito=payload
jsoncito

{'collection': 'series',
 'data': [{'_id': 'S001',
   'title': 'The Investigators',
   'genre': ['Crime'],
   'seasons': 7,
   'episodes_per_season': [8, 14, 7, 17, 12, 13, 18],
   'avg_episode_duration': 50,
   'rating': 1.3,
   'total_views': 50315,
   'production_budget': 44041273},
  {'_id': 'S002',
   'title': 'The Investigators',
   'genre': ['Sci-Fi'],
   'seasons': 7,
   'episodes_per_season': [16, 12, 14, 14, 23, 9, 24],
   'avg_episode_duration': 20,
   'rating': 4.4,
   'total_views': 351932,
   'production_budget': 126866932},
  {'_id': 'S003',
   'title': 'System Archives',
   'genre': ['Documentary'],
   'seasons': 4,
   'episodes_per_season': [9, 7, 21, 14],
   'avg_episode_duration': 44,
   'rating': 2.8,
   'total_views': 78137,
   'production_budget': 56625408},
  {'_id': 'S004',
   'title': 'Cyber Archives',
   'genre': ['Comedy', 'Romance'],
   'seasons': 2,
   'episodes_per_season': [8, 6],
   'avg_episode_duration': 58,
   'rating': 2.2,
   'total_views': 58071,
   'production_budget': 47182636},
  {'_id': 'S005',
   'title': 'The Scientists',
   'genre': ['Action', 'Drama'],
   'seasons': 5,
   'episodes_per_season': [22, 14, 6, 14, 9],
   'avg_episode_duration': 29,
   'rating': 4.4,
   'total_views': 76998,
   'production_budget': 327965922},
  {'_id': 'S006',
   'title': 'The Scientists',
   'genre': ['Reality', 'Crime'],
   'seasons': 8,
   'episodes_per_season': [10, 19, 7, 12, 21, 6, 10, 9],
   'avg_episode_duration': 30,
   'rating': 1.5,
   'total_views': 34209,
   'production_budget': 10288145},
  {'_id': 'S007',
   'title': 'The Analysts',
   'genre': ['Documentary'],
   'seasons': 4,
   'episodes_per_season': [16, 9, 14, 12],
   'avg_episode_duration': 58,
   'rating': 1.2,
   'total_views': 63328,
   'production_budget': 58423635},
  {'_id': 'S008',
   'title': 'Intelligence Cases',
   'genre': ['Reality', 'Sci-Fi'],
   'seasons': 3,
   'episodes_per_season': [21, 6, 7],
   'avg_episode_duration': 28,
   'rating': 3.8,
   'total_views': 172536,
   'production_budget': 65923441},
  {'_id': 'S009',
   'title': 'The Investigators',
   'genre': ['Action'],
   'seasons': 2,
   'episodes_per_season': [12, 23],
   'avg_episode_duration': 38,
   'rating': 3.4,
   'total_views': 176621,
   'production_budget': 25451448},
  {'_id': 'S010',
   'title': 'The Detectives',
   'genre': ['Romance', 'Sci-Fi'],
   'seasons': 6,
   'episodes_per_season': [11, 7, 21, 24, 15, 7],
   'avg_episode_duration': 51,
   'rating': 2.2,
   'total_views': 137965,
   'production_budget': 30273595},
  {'_id': 'S011',
   'title': 'Tech Cases',
   'genre': ['Crime', 'Sci-Fi'],
   'seasons': 1,
   'episodes_per_season': [17],
   'avg_episode_duration': 39,
   'rating': 4.9,
   'total_views': 290490,
   'production_budget': 114902788},
  {'_id': 'S012',
   'title': 'Code Engineer Files',
   'genre': ['Sci-Fi'],
   'seasons': 5,
   'episodes_per_season': [7, 10, 18, 19, 13],
   'avg_episode_duration': 34,
   'rating': 4.1,
   'total_views': 170988,
   'production_budget': 208347149},
  {'_id': 'S013',
   'title': 'The Analysts',
   'genre': ['Documentary'],
   'seasons': 8,
   'episodes_per_season': [11, 21, 24, 14, 19, 15, 19, 10],
   'avg_episode_duration': 52,
   'rating': 3.2,
   'total_views': 107304,
   'production_budget': 77414168},
  {'_id': 'S014',
   'title': 'System Master Records',
   'genre': ['Romance', 'Drama'],
   'seasons': 8,
   'episodes_per_season': [24, 21, 23, 21, 7, 10, 22, 12],
   'avg_episode_duration': 60,
   'rating': 1.7,
   'total_views': 120686,
   'production_budget': 396719513},
  {'_id': 'S015',
   'title': 'System Analyst Logs',
   'genre': ['Documentary'],
   'seasons': 8,
   'episodes_per_season': [10, 10, 12, 12, 16, 8, 9, 22],
   'avg_episode_duration': 30,
   'rating': 1.7,
   'total_views': 173243,
   'production_budget': 86131629},
  {'_id': 'S016',
   'title': 'The Investigators',
   'genre': ['Action'],
   'seasons': 4,
   'episodes_per_season': [23, 7, 18, 7],
   'avg_episode_duration': 55,
   'rating': 2.1,
   'total_views': 134389,
   'production_budget': 68265098},
  {'_id': 'S017',
   'title': 'Data Expert Chronicles',
   'genre': ['Action', 'Drama'],
   'seasons': 7,
   'episodes_per_season': [9, 15, 11, 24, 18, 17, 19],
   'avg_episode_duration': 38,
   'rating': 2.4,
   'total_views': 12444,
   'production_budget': 137756173},
  {'_id': 'S018',
   'title': 'Code Files',
   'genre': ['Action', 'Comedy'],
   'seasons': 5,
   'episodes_per_season': [8, 19, 19, 21, 21],
   'avg_episode_duration': 37,
   'rating': 1.5,
   'total_views': 157045,
   'production_budget': 19314996},
  {'_id': 'S019',
   'title': 'Analytics Archives',
   'genre': ['Romance', 'Drama'],
   'seasons': 6,
   'episodes_per_season': [15, 14, 11, 12, 11, 22],
   'avg_episode_duration': 40,
   'rating': 2.2,
   'total_views': 188719,
   'production_budget': 456731471},
  {'_id': 'S020',
   'title': 'The Analysts',
   'genre': ['Romance', 'Crime'],
   'seasons': 6,
   'episodes_per_season': [7, 13, 13, 16, 16, 23],
   'avg_episode_duration': 36,
   'rating': 2.2,
   'total_views': 66964,
   'production_budget': 30466126},
  {'_id': 'S021',
   'title': 'The Specialists',
   'genre': ['Crime'],
   'seasons': 8,
   'episodes_per_season': [20, 17, 14, 17, 12, 22, 17, 10],
   'avg_episode_duration': 45,
   'rating': 3.0,
   'total_views': 33356,
   'production_budget': 98820528},
  {'_id': 'S022',
   'title': 'The Investigators',
   'genre': ['Reality', 'Drama'],
   'seasons': 8,
   'episodes_per_season': [13, 21, 7, 23, 9, 11, 11, 8],
   'avg_episode_duration': 37,
   'rating': 2.1,
   'total_views': 61463,
   'production_budget': 197105748},
  {'_id': 'S023',
   'title': 'The Engineers',
   'genre': ['Action', 'Sci-Fi'],
   'seasons': 1,
   'episodes_per_season': [14],
   'avg_episode_duration': 41,
   'rating': 2.6,
   'total_views': 47152,
   'production_budget': 37455594},
  {'_id': 'S024',
   'title': 'The Detectives',
   'genre': ['Crime'],
   'seasons': 4,
   'episodes_per_season': [20, 21, 17, 23],
   'avg_episode_duration': 48,
   'rating': 1.3,
   'total_views': 88924,
   'production_budget': 79333132},
  {'_id': 'S025',
   'title': 'Digital Master Files',
   'genre': ['Documentary'],
   'seasons': 6,
   'episodes_per_season': [20, 15, 19, 24, 12, 20],
   'avg_episode_duration': 36,
   'rating': 3.7,
   'total_views': 181783,
   'production_budget': 65631668},
  {'_id': 'S026',
   'title': 'Analytics Chronicles',
   'genre': ['Comedy'],
   'seasons': 6,
   'episodes_per_season': [13, 10, 18, 7, 14, 12],
   'avg_episode_duration': 59,
   'rating': 3.9,
   'total_views': 159023,
   'production_budget': 85960997},
  {'_id': 'S027',
   'title': 'The Specialists',
   'genre': ['Reality', 'Romance'],
   'seasons': 8,
   'episodes_per_season': [9, 22, 14, 22, 22, 16, 23, 9],
   'avg_episode_duration': 50,
   'rating': 3.6,
   'total_views': 124627,
   'production_budget': 17641045},
  {'_id': 'S028',
   'title': 'The Experts',
   'genre': ['Crime'],
   'seasons': 7,
   'episodes_per_season': [15, 11, 21, 9, 22, 10, 11],
   'avg_episode_duration': 45,
   'rating': 1.6,
   'total_views': 111067,
   'production_budget': 15293760},
  {'_id': 'S029',
   'title': 'Digital Diaries',
   'genre': ['Documentary'],
   'seasons': 4,
   'episodes_per_season': [21, 16, 23, 12],
   'avg_episode_duration': 42,
   'rating': 1.8,
   'total_views': 81277,
   'production_budget': 68389735},
  {'_id': 'S030',
   'title': 'The Scientists',
   'genre': ['Romance', 'Documentary'],
   'seasons': 6,
   'episodes_per_season': [21, 6, 6, 13, 20, 7],
   'avg_episode_duration': 58,
   'rating': 4.5,
   'total_views': 268280,
   'production_budget': 400393000},
  {'_id': 'S031',
   'title': 'The Analysts',
   'genre': ['Crime'],
   'seasons': 1,
   'episodes_per_season': [23],
   'avg_episode_duration': 59,
   'rating': 4.2,
   'total_views': 328774,
   'production_budget': 415835464},
  {'_id': 'S032',
   'title': 'Tech Reports',
   'genre': ['Sci-Fi', 'Reality'],
   'seasons': 5,
   'episodes_per_season': [12, 14, 17, 13, 19],
   'avg_episode_duration': 37,
   'rating': 1.7,
   'total_views': 53516,
   'production_budget': 95839378},
  {'_id': 'S033',
   'title': 'The Experts',
   'genre': ['Crime', 'Romance'],
   'seasons': 7,
   'episodes_per_season': [7, 11, 6, 8, 15, 20, 10],
   'avg_episode_duration': 28,
   'rating': 3.0,
   'total_views': 186235,
   'production_budget': 19617530},
  {'_id': 'S034',
   'title': 'Tech Master Records',
   'genre': ['Drama'],
   'seasons': 1,
   'episodes_per_season': [11],
   'avg_episode_duration': 27,
   'rating': 4.2,
   'total_views': 250364,
   'production_budget': 210303817},
  {'_id': 'S035',
   'title': 'Cloud Chronicles',
   'genre': ['Action'],
   'seasons': 8,
   'episodes_per_season': [11, 12, 7, 13, 7, 14, 9, 6],
   'avg_episode_duration': 49,
   'rating': 1.5,
   'total_views': 24212,
   'production_budget': 32588164},
  {'_id': 'S036',
   'title': 'Intelligence Logs',
   'genre': ['Comedy'],
   'seasons': 4,
   'episodes_per_season': [24, 24, 7, 8],
   'avg_episode_duration': 35,
   'rating': 2.2,
   'total_views': 122031,
   'production_budget': 36342177},
  {'_id': 'S037',
   'title': 'The Experts',
   'genre': ['Reality'],
   'seasons': 5,
   'episodes_per_season': [20, 8, 15, 24, 7],
   'avg_episode_duration': 39,
   'rating': 1.3,
   'total_views': 177234,
   'production_budget': 6067543},
  {'_id': 'S038',
   'title': 'The Masters',
   'genre': ['Action'],
   'seasons': 3,
   'episodes_per_season': [22, 13, 13],
   'avg_episode_duration': 52,
   'rating': 4.3,
   'total_views': 91190,
   'production_budget': 228468542},
  {'_id': 'S039',
   'title': 'The Experts',
   'genre': ['Comedy', 'Action'],
   'seasons': 3,
   'episodes_per_season': [9, 19, 20],
   'avg_episode_duration': 52,
   'rating': 3.2,
   'total_views': 186734,
   'production_budget': 55906418},
  {'_id': 'S040',
   'title': 'Cyber Archives',
   'genre': ['Drama', 'Action'],
   'seasons': 1,
   'episodes_per_season': [15],
   'avg_episode_duration': 34,
   'rating': 4.4,
   'total_views': 269484,
   'production_budget': 467178636},
  {'_id': 'S041',
   'title': 'The Analysts',
   'genre': ['Action', 'Romance'],
   'seasons': 7,
   'episodes_per_season': [16, 11, 6, 15, 14, 22, 9],
   'avg_episode_duration': 34,
   'rating': 2.0,
   'total_views': 193868,
   'production_budget': 8921678},
  {'_id': 'S042',
   'title': 'The Analysts',
   'genre': ['Action'],
   'seasons': 3,
   'episodes_per_season': [10, 8, 18],
   'avg_episode_duration': 51,
   'rating': 4.9,
   'total_views': 364998,
   'production_budget': 470357872},
  {'_id': 'S043',
   'title': 'The Specialists',
   'genre': ['Drama', 'Reality'],
   'seasons': 5,
   'episodes_per_season': [8, 21, 23, 14, 11],
   'avg_episode_duration': 35,
   'rating': 1.4,
   'total_views': 36502,
   'production_budget': 352436532},
  {'_id': 'S044',
   'title': 'Cloud Reports',
   'genre': ['Comedy'],
   'seasons': 1,
   'episodes_per_season': [13],
   'avg_episode_duration': 46,
   'rating': 3.4,
   'total_views': 152609,
   'production_budget': 78560006},
  {'_id': 'S045',
   'title': 'The Scientists',
   'genre': ['Crime'],
   'seasons': 3,
   'episodes_per_season': [20, 13, 24],
   'avg_episode_duration': 24,
   'rating': 2.7,
   'total_views': 55899,
   'production_budget': 57056031},
  {'_id': 'S046',
   'title': 'Code Archives',
   'genre': ['Sci-Fi', 'Drama'],
   'seasons': 5,
   'episodes_per_season': [17, 7, 11, 7, 20],
   'avg_episode_duration': 21,
   'rating': 2.2,
   'total_views': 46760,
   'production_budget': 292316186},
  {'_id': 'S047',
   'title': 'Intelligence Stories',
   'genre': ['Comedy', 'Reality'],
   'seasons': 5,
   'episodes_per_season': [11, 24, 7, 15, 13],
   'avg_episode_duration': 58,
   'rating': 2.6,
   'total_views': 96207,
   'production_budget': 37685089},
  {'_id': 'S048',
   'title': 'The Experts',
   'genre': ['Comedy', 'Documentary'],
   'seasons': 8,
   'episodes_per_season': [24, 21, 7, 24, 11, 11, 17, 9],
   'avg_episode_duration': 29,
   'rating': 1.5,
   'total_views': 78818,
   'production_budget': 30228151},
  {'_id': 'S049',
   'title': 'Cyber Archives',
   'genre': ['Reality'],
   'seasons': 1,
   'episodes_per_season': [18],
   'avg_episode_duration': 37,
   'rating': 3.1,
   'total_views': 84555,
   'production_budget': 58765760},
  {'_id': 'S050',
   'title': 'The Experts',
   'genre': ['Sci-Fi', 'Comedy'],
   'seasons': 2,
   'episodes_per_season': [14, 15],
   'avg_episode_duration': 39,
   'rating': 4.6,
   'total_views': 111070,
   'production_budget': 291245363},
  {'_id': 'S051',
   'title': 'Cyber Diaries',
   'genre': ['Action'],
   'seasons': 1,
   'episodes_per_season': [24],
   'avg_episode_duration': 23,
   'rating': 4.3,
   'total_views': 68702,
   'production_budget': 368102832},
  {'_id': 'S052',
   'title': 'Intelligence Engineer Records',
   'genre': ['Action', 'Crime'],
   'seasons': 4,
   'episodes_per_season': [17, 10, 19, 11],
   'avg_episode_duration': 55,
   'rating': 1.2,
   'total_views': 101497,
   'production_budget': 60906031},
  {'_id': 'S053',
   'title': 'Analytics Archives',
   'genre': ['Sci-Fi'],
   'seasons': 3,
   'episodes_per_season': [6, 14, 19],
   'avg_episode_duration': 43,
   'rating': 2.2,
   'total_views': 49311,
   'production_budget': 41543684},
  {'_id': 'S054',
   'title': 'Intelligence Chronicles',
   'genre': ['Romance', 'Action'],
   'seasons': 4,
   'episodes_per_season': [16, 10, 11, 24],
   'avg_episode_duration': 55,
   'rating': 2.0,
   'total_views': 99736,
   'production_budget': 14694325},
  {'_id': 'S055',
   'title': 'The Scientists',
   'genre': ['Crime'],
   'seasons': 2,
   'episodes_per_season': [15, 18],
   'avg_episode_duration': 59,
   'rating': 1.5,
   'total_views': 139418,
   'production_budget': 28230331},
  {'_id': 'S056',
   'title': 'The Scientists',
   'genre': ['Crime'],
   'seasons': 7,
   'episodes_per_season': [24, 13, 13, 15, 18, 15, 10],
   'avg_episode_duration': 59,
   'rating': 1.0,
   'total_views': 173098,
   'production_budget': 93373094},
  {'_id': 'S057',
   'title': 'Cyber Chronicles',
   'genre': ['Documentary', 'Comedy'],
   'seasons': 5,
   'episodes_per_season': [17, 11, 13, 9, 23],
   'avg_episode_duration': 23,
   'rating': 4.1,
   'total_views': 241304,
   'production_budget': 499744453},
  {'_id': 'S058',
   'title': 'Data Logs',
   'genre': ['Comedy', 'Romance'],
   'seasons': 6,
   'episodes_per_season': [11, 7, 20, 10, 13, 18],
   'avg_episode_duration': 57,
   'rating': 1.2,
   'total_views': 99661,
   'production_budget': 66154832},
  {'_id': 'S059',
   'title': 'The Scientists',
   'genre': ['Documentary'],
   'seasons': 2,
   'episodes_per_season': [6, 20],
   'avg_episode_duration': 27,
   'rating': 5.0,
   'total_views': 27954,
   'production_budget': 280522409},
  {'_id': 'S060',
   'title': 'The Detectives',
   'genre': ['Drama'],
   'seasons': 7,
   'episodes_per_season': [14, 16, 10, 21, 19, 8, 7],
   'avg_episode_duration': 41,
   'rating': 3.1,
   'total_views': 11044,
   'production_budget': 143304276},
  {'_id': 'S061',
   'title': 'Tech Master Files',
   'genre': ['Documentary'],
   'seasons': 5,
   'episodes_per_season': [20, 10, 19, 16, 15],
   'avg_episode_duration': 50,
   'rating': 2.9,
   'total_views': 17393,
   'production_budget': 99027997},
  {'_id': 'S062',
   'title': 'Digital Chronicles',
   'genre': ['Documentary', 'Drama'],
   'seasons': 7,
   'episodes_per_season': [13, 14, 6, 15, 16, 14, 12],
   'avg_episode_duration': 54,
   'rating': 2.9,
   'total_views': 157616,
   'production_budget': 127511414},
  {'_id': 'S063',
   'title': 'Digital Archives',
   'genre': ['Drama', 'Comedy'],
   'seasons': 6,
   'episodes_per_season': [22, 18, 21, 14, 12, 11],
   'avg_episode_duration': 51,
   'rating': 4.0,
   'total_views': 60750,
   'production_budget': 382523478},
  {'_id': 'S064',
   'title': 'The Masters',
   'genre': ['Crime'],
   'seasons': 6,
   'episodes_per_season': [21, 24, 19, 16, 13, 13],
   'avg_episode_duration': 37,
   'rating': 3.6,
   'total_views': 25420,
   'production_budget': 35573482},
  {'_id': 'S065',
   'title': 'The Detectives',
   'genre': ['Crime', 'Drama'],
   'seasons': 3,
   'episodes_per_season': [23, 24, 9],
   'avg_episode_duration': 44,
   'rating': 3.0,
   'total_views': 183444,
   'production_budget': 278507421},
  {'_id': 'S066',
   'title': 'The Experts',
   'genre': ['Reality', 'Romance'],
   'seasons': 7,
   'episodes_per_season': [19, 19, 24, 17, 18, 23, 9],
   'avg_episode_duration': 35,
   'rating': 2.9,
   'total_views': 128430,
   'production_budget': 63619939},
  {'_id': 'S067',
   'title': 'System Files',
   'genre': ['Crime'],
   'seasons': 4,
   'episodes_per_season': [19, 8, 17, 20],
   'avg_episode_duration': 60,
   'rating': 2.4,
   'total_views': 71070,
   'production_budget': 73813095},
  {'_id': 'S068',
   'title': 'Analytics Cases',
   'genre': ['Sci-Fi'],
   'seasons': 8,
   'episodes_per_season': [18, 17, 17, 12, 21, 15, 23, 20],
   'avg_episode_duration': 25,
   'rating': 3.3,
   'total_views': 63083,
   'production_budget': 69011874},
  {'_id': 'S069',
   'title': 'Network Chronicles',
   'genre': ['Action'],
   'seasons': 6,
   'episodes_per_season': [7, 14, 7, 17, 7, 7],
   'avg_episode_duration': 49,
   'rating': 4.1,
   'total_views': 135238,
   'production_budget': 216309090},
  {'_id': 'S070',
   'title': 'The Analysts',
   'genre': ['Action'],
   'seasons': 4,
   'episodes_per_season': [8, 9, 19, 16],
   'avg_episode_duration': 55,
   'rating': 4.0,
   'total_views': 165360,
   'production_budget': 18764279},
  {'_id': 'S071',
   'title': 'Code Logs',
   'genre': ['Crime'],
   'seasons': 3,
   'episodes_per_season': [18, 15, 8],
   'avg_episode_duration': 37,
   'rating': 4.7,
   'total_views': 133808,
   'production_budget': 299747822},
  {'_id': 'S072',
   'title': 'The Scientists',
   'genre': ['Romance'],
   'seasons': 2,
   'episodes_per_season': [20, 17],
   'avg_episode_duration': 21,
   'rating': 3.8,
   'total_views': 110021,
   'production_budget': 27120174},
  {'_id': 'S073',
   'title': 'The Engineers',
   'genre': ['Documentary', 'Romance'],
   'seasons': 4,
   'episodes_per_season': [11, 21, 16, 11],
   'avg_episode_duration': 50,
   'rating': 1.6,
   'total_views': 174261,
   'production_budget': 55156195},
  {'_id': 'S074',
   'title': 'The Specialists',
   'genre': ['Reality', 'Crime'],
   'seasons': 4,
   'episodes_per_season': [6, 24, 8, 10],
   'avg_episode_duration': 47,
   'rating': 4.1,
   'total_views': 233200,
   'production_budget': 141489146},
  {'_id': 'S075',
   'title': 'The Investigators',
   'genre': ['Sci-Fi', 'Action'],
   'seasons': 8,
   'episodes_per_season': [11, 8, 22, 11, 22, 11, 9, 8],
   'avg_episode_duration': 38,
   'rating': 3.6,
   'total_views': 111955,
   'production_budget': 40425131},
  {'_id': 'S076',
   'title': 'The Analysts',
   'genre': ['Sci-Fi', 'Crime'],
   'seasons': 4,
   'episodes_per_season': [13, 12, 22, 15],
   'avg_episode_duration': 49,
   'rating': 1.9,
   'total_views': 187502,
   'production_budget': 87863196},
  {'_id': 'S077',
   'title': 'Cloud Investigator Reports',
   'genre': ['Action'],
   'seasons': 2,
   'episodes_per_season': [17, 20],
   'avg_episode_duration': 23,
   'rating': 3.3,
   'total_views': 22208,
   'production_budget': 22963861},
  {'_id': 'S078',
   'title': 'Analytics Investigator Cases',
   'genre': ['Reality'],
   'seasons': 5,
   'episodes_per_season': [6, 6, 21, 18, 14],
   'avg_episode_duration': 25,
   'rating': 4.3,
   'total_views': 317878,
   'production_budget': 448231718},
  {'_id': 'S079',
   'title': 'The Engineers',
   'genre': ['Comedy', 'Action'],
   'seasons': 3,
   'episodes_per_season': [6, 7, 11],
   'avg_episode_duration': 46,
   'rating': 4.0,
   'total_views': 181689,
   'production_budget': 30474598},
  {'_id': 'S080',
   'title': 'The Specialists',
   'genre': ['Romance'],
   'seasons': 6,

In [ ]:
print([content_json])

[{'movies': [{'_id': 'M001', 'title': 'Advanced World', 'genre': ['Sci-Fi', 'Horror', 'Drama'], 'duration_minutes': 179, 'release_year': 2020, 'rating': 3.5, 'views_count': 66721, 'production_budget': 220088717}, {'_id': 'M002', 'title': 'Neural Signal', 'genre': ['Animation', 'Horror'], 'duration_minutes': 146, 'release_year': 2021, 'rating': 2.8, 'views_count': 11128, 'production_budget': 23593231}, {'_id': 'M003', 'title': 'An Stream', 'genre': ['Action'], 'duration_minutes': 102, 'release_year': 2023, 'rating': 1.9, 'views_count': 75949, 'production_budget': 83166461}, {'_id': 'M004', 'title': 'Binary Journey', 'genre': ['Thriller', 'Documentary'], 'duration_minutes': 146, 'release_year': 2022, 'rating': 3.0, 'views_count': 85958, 'production_budget': 46298444}, {'_id': 'M005', 'title': 'Lost Data', 'genre': ['Horror', 'Romance'], 'duration_minutes': 169, 'release_year': 2022, 'rating': 4.7, 'views_count': 56808, 'production_budget': 67293750}, {'_id': 'M006', 'title': 'Ultimate Mystery', 'genre': ['Action', 'Animation', 'Horror'], 'duration_minutes': 157, 'release_year': 2024, 'rating': 1.1, 'views_count': 148876, 'production_budget': 234348717}, {'_id': 'M007', 'title': 'Code', 'genre': ['Comedy', 'Romance'], 'duration_minutes': 136, 'release_year': 2022, 'rating': 3.1, 'views_count': 9228, 'production_budget': 35028167}, {'_id': 'M008', 'title': 'Digital Protocol', 'genre': ['Documentary', 'Romance'], 'duration_minutes': 155, 'release_year': 2023, 'rating': 3.7, 'views_count': 125068, 'production_budget': 49545701}, {'_id': 'M009', 'title': 'Tale', 'genre': ['Drama', 'Horror'], 'duration_minutes': 90, 'release_year': 2023, 'rating': 4.4, 'views_count': 37911, 'production_budget': 146895476}, {'_id': 'M010', 'title': 'An Code 2', 'genre': ['Comedy', 'Romance', 'Action'], 'duration_minutes': 174, 'release_year': 2021, 'rating': 3.5, 'views_count': 78005, 'production_budget': 224671521}, {'_id': 'M011', 'title': 'Algorithm', 'genre': ['Drama', 'Animation', 'Horror'], 'duration_minutes': 81, 'release_year': 2023, 'rating': 2.7, 'views_count': 92634, 'production_budget': 20512281}, {'_id': 'M012', 'title': 'Quest 5', 'genre': ['Comedy'], 'duration_minutes': 104, 'release_year': 2023, 'rating': 2.4, 'views_count': 59155, 'production_budget': 36408859}, {'_id': 'M013', 'title': 'Mystery', 'genre': ['Documentary', 'Drama'], 'duration_minutes': 178, 'release_year': 2020, 'rating': 1.6, 'views_count': 61328, 'production_budget': 16064411}, {'_id': 'M014', 'title': 'Kingdom', 'genre': ['Thriller', 'Action'], 'duration_minutes': 122, 'release_year': 2021, 'rating': 4.2, 'views_count': 138918, 'production_budget': 202395249}, {'_id': 'M015', 'title': 'Quantum Code', 'genre': ['Animation', 'Documentary', 'Sci-Fi'], 'duration_minutes': 177, 'release_year': 2021, 'rating': 2.4, 'views_count': 13807, 'production_budget': 227198245}, {'_id': 'M016', 'title': 'A Database', 'genre': ['Drama', 'Documentary'], 'duration_minutes': 95, 'release_year': 2023, 'rating': 3.0, 'views_count': 81858, 'production_budget': 6729979}, {'_id': 'M017', 'title': 'Adventure', 'genre': ['Action', 'Documentary', 'Horror'], 'duration_minutes': 97, 'release_year': 2020, 'rating': 4.6, 'views_count': 132014, 'production_budget': 50839665}, {'_id': 'M018', 'title': 'Mystery', 'genre': ['Comedy', 'Action'], 'duration_minutes': 84, 'release_year': 2023, 'rating': 3.6, 'views_count': 81531, 'production_budget': 158431993}, {'_id': 'M019', 'title': 'Final Stream', 'genre': ['Action'], 'duration_minutes': 83, 'release_year': 2023, 'rating': 2.3, 'views_count': 144211, 'production_budget': 114952801}, {'_id': 'M020', 'title': 'Quest', 'genre': ['Thriller', 'Action', 'Drama'], 'duration_minutes': 108, 'release_year': 2022, 'rating': 3.1, 'views_count': 47873, 'production_budget': 250548961}, {'_id': 'M021', 'title': 'Tale', 'genre': ['Drama', 'Horror'], 'duration_minutes': 148, 'release_year': 2020, 'rating': 4.9, 'views_count': 168298, 'production_budget': 62478620}, {'_id': 'M022', 'title': 'Quantum System', 'genre': ['Horror'], 'duration_minutes': 147, 'release_year': 2023, 'rating': 4.7, 'views_count': 116580, 'production_budget': 73128204}, {'_id': 'M023', 'title': 'Smart Story', 'genre': ['Horror'], 'duration_minutes': 147, 'release_year': 2022, 'rating': 3.3, 'views_count': 36200, 'production_budget': 12509378}, {'_id': 'M024', 'title': 'First Mystery', 'genre': ['Horror'], 'duration_minutes': 159, 'release_year': 2020, 'rating': 4.2, 'views_count': 117924, 'production_budget': 146907831}, {'_id': 'M025', 'title': 'An Protocol', 'genre': ['Comedy'], 'duration_minutes': 162, 'release_year': 2020, 'rating': 4.0, 'views_count': 26519, 'production_budget': 49021276}, {'_id': 'M026', 'title': 'Lost Kingdom', 'genre': ['Documentary', 'Drama', 'Action'], 'duration_minutes': 163, 'release_year': 2024, 'rating': 2.6, 'views_count': 113230, 'production_budget': 90625130}, {'_id': 'M027', 'title': 'Quantum Story', 'genre': ['Thriller', 'Horror', 'Sci-Fi'], 'duration_minutes': 128, 'release_year': 2023, 'rating': 1.2, 'views_count': 19816, 'production_budget': 150283990}, {'_id': 'M028', 'title': 'Final Kingdom', 'genre': ['Comedy', 'Horror', 'Drama'], 'duration_minutes': 175, 'release_year': 2023, 'rating': 1.7, 'views_count': 87291, 'production_budget': 8816404}, {'_id': 'M029', 'title': 'System', 'genre': ['Documentary'], 'duration_minutes': 123, 'release_year': 2023, 'rating': 1.8, 'views_count': 27793, 'production_budget': 30738350}, {'_id': 'M030', 'title': 'Database 4', 'genre': ['Drama', 'Action'], 'duration_minutes': 145, 'release_year': 2020, 'rating': 1.3, 'views_count': 98063, 'production_budget': 100987742}, {'_id': 'M031', 'title': 'Empire', 'genre': ['Action', 'Animation', 'Drama'], 'duration_minutes': 104, 'release_year': 2020, 'rating': 4.9, 'views_count': 114316, 'production_budget': 184475405}, {'_id': 'M032', 'title': 'A Code', 'genre': ['Thriller', 'Action'], 'duration_minutes': 133, 'release_year': 2024, 'rating': 3.4, 'views_count': 83014, 'production_budget': 283617949}, {'_id': 'M033', 'title': 'Dark Stream', 'genre': ['Action', 'Animation'], 'duration_minutes': 119, 'release_year': 2023, 'rating': 2.9, 'views_count': 54865, 'production_budget': 193790052}, {'_id': 'M034', 'title': 'Stream', 'genre': ['Romance', 'Sci-Fi', 'Action'], 'duration_minutes': 151, 'release_year': 2020, 'rating': 4.9, 'views_count': 41348, 'production_budget': 122112109}, {'_id': 'M035', 'title': 'Lost System 5', 'genre': ['Thriller', 'Romance'], 'duration_minutes': 112, 'release_year': 2021, 'rating': 1.8, 'views_count': 64414, 'production_budget': 2127388}, {'_id': 'M036', 'title': 'Quest', 'genre': ['Romance', 'Animation'], 'duration_minutes': 100, 'release_year': 2020, 'rating': 2.9, 'views_count': 90335, 'production_budget': 12670028}, {'_id': 'M037', 'title': 'Quest', 'genre': ['Animation', 'Comedy', 'Documentary'], 'duration_minutes': 90, 'release_year': 2022, 'rating': 1.2, 'views_count': 13250, 'production_budget': 33987762}, {'_id': 'M038', 'title': 'Data', 'genre': ['Animation', 'Documentary'], 'duration_minutes': 161, 'release_year': 2021, 'rating': 3.6, 'views_count': 47672, 'production_budget': 15316213}, {'_id': 'M039', 'title': 'Lost Cloud', 'genre': ['Horror', 'Drama', 'Action'], 'duration_minutes': 103, 'release_year': 2020, 'rating': 2.8, 'views_count': 48310, 'production_budget': 202148811}, {'_id': 'M040', 'title': 'Quest', 'genre': ['Comedy', 'Documentary', 'Drama'], 'duration_minutes': 171, 'release_year': 2022, 'rating': 2.2, 'views_count': 52925, 'production_budget': 1600669}, {'_id': 'M041', 'title': 'Infinite Story', 'genre': ['Horror', 'Thriller'], 'duration_minutes': 117, 'release_year': 2021, 'rating': 4.2, 'views_count': 129104, 'production_budget': 186923029}, {'_id': 'M042', 'title': 'Advanced System 2', 'genre': ['Documentary'], 'duration_minutes': 163, 'release_year': 2020, 'rating': 3.3, 'views_count': 44583, 'production_budget': 42856949}, {'_id': 'M043', 'title': 'Hidden Empire', 'genre': ['Horror'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 4.1, 'views_count': 290064, 'production_budget': 128140036}, {'_id': 'M044', 'title': 'Cyber Cloud 4', 'genre': ['Animation', 'Thriller'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 3.3, 'views_count': 8992, 'production_budget': 8120314}, {'_id': 'M045', 'title': 'First Database', 'genre': ['Animation', 'Action'], 'duration_minutes': 123, 'release_year': 2023, 'rating': 3.1, 'views_count': 115282, 'production_budget': 182644208}, {'_id': 'M046', 'title': 'Binary Signal', 'genre': ['Animation', 'Documentary', 'Thriller'], 'duration_minutes': 147, 'release_year': 2023, 'rating': 1.9, 'views_count': 18247, 'production_budget': 24000248}, {'_id': 'M047', 'title': 'Story', 'genre': ['Drama'], 'duration_minutes': 120, 'release_year': 2023, 'rating': 3.3, 'views_count': 5974, 'production_budget': 18448764}, {'_id': 'M048', 'title': 'Tale', 'genre': ['Horror', 'Romance', 'Documentary'], 'duration_minutes': 104, 'release_year': 2021, 'rating': 4.9, 'views_count': 178486, 'production_budget': 59289648}, {'_id': 'M049', 'title': 'Neural Cloud 2', 'genre': ['Drama', 'Sci-Fi', 'Action'], 'duration_minutes': 126, 'release_year': 2020, 'rating': 3.7, 'views_count': 33051, 'production_budget': 135871052}, {'_id': 'M050', 'title': 'Infinite Protocol', 'genre': ['Thriller', 'Documentary'], 'duration_minutes': 96, 'release_year': 2021, 'rating': 2.0, 'views_count': 53173, 'production_budget': 39370044}, {'_id': 'M051', 'title': 'A Algorithm', 'genre': ['Animation'], 'duration_minutes': 155, 'release_year': 2022, 'rating': 4.8, 'views_count': 136410, 'production_budget': 106311259}, {'_id': 'M052', 'title': 'Adventure', 'genre': ['Horror', 'Thriller', 'Sci-Fi'], 'duration_minutes': 120, 'release_year': 2021, 'rating': 3.9, 'views_count': 94063, 'production_budget': 193008798}, {'_id': 'M053', 'title': 'Infinite Empire', 'genre': ['Action'], 'duration_minutes': 162, 'release_year': 2022, 'rating': 1.9, 'views_count': 50863, 'production_budget': 296179703}, {'_id': 'M054', 'title': 'Binary Stream', 'genre': ['Action', 'Animation', 'Documentary'], 'duration_minutes': 98, 'release_year': 2021, 'rating': 4.6, 'views_count': 17832, 'production_budget': 122289319}, {'_id': 'M055', 'title': 'Infinite Adventure', 'genre': ['Thriller'], 'duration_minutes': 142, 'release_year': 2023, 'rating': 3.6, 'views_count': 121651, 'production_budget': 37909361}, {'_id': 'M056', 'title': 'Binary Journey', 'genre': ['Thriller', 'Action'], 'duration_minutes': 88, 'release_year': 2023, 'rating': 3.6, 'views_count': 105627, 'production_budget': 140493022}, {'_id': 'M057', 'title': 'Journey', 'genre': ['Drama', 'Sci-Fi'], 'duration_minutes': 149, 'release_year': 2022, 'rating': 1.9, 'views_count': 38409, 'production_budget': 213938522}, {'_id': 'M058', 'title': 'Last Quest', 'genre': ['Documentary', 'Animation', 'Romance'], 'duration_minutes': 173, 'release_year': 2020, 'rating': 3.6, 'views_count': 53146, 'production_budget': 20440772}, {'_id': 'M059', 'title': 'System', 'genre': ['Sci-Fi', 'Thriller', 'Drama'], 'duration_minutes': 146, 'release_year': 2020, 'rating': 1.5, 'views_count': 63578, 'production_budget': 80650718}, {'_id': 'M060', 'title': 'Dark Kingdom', 'genre': ['Thriller', 'Sci-Fi'], 'duration_minutes': 122, 'release_year': 2020, 'rating': 4.9, 'views_count': 196906, 'production_budget': 107714280}, {'_id': 'M061', 'title': 'An Cloud', 'genre': ['Drama', 'Comedy', 'Action'], 'duration_minutes': 99, 'release_year': 2022, 'rating': 4.6, 'views_count': 58038, 'production_budget': 181262622}, {'_id': 'M062', 'title': 'Secret Empire', 'genre': ['Horror'], 'duration_minutes': 136, 'release_year': 2024, 'rating': 1.1, 'views_count': 113496, 'production_budget': 45559979}, {'_id': 'M063', 'title': 'Neural Cloud', 'genre': ['Sci-Fi', 'Drama'], 'duration_minutes': 104, 'release_year': 2024, 'rating': 4.5, 'views_count': 241308, 'production_budget': 52788131}, {'_id': 'M064', 'title': 'Virtual Adventure', 'genre': ['Drama', 'Action'], 'duration_minutes': 113, 'release_year': 2024, 'rating': 4.4, 'views_count': 99105, 'production_budget': 99191442}, {'_id': 'M065', 'title': 'Final Story', 'genre': ['Documentary', 'Romance', 'Sci-Fi'], 'duration_minutes': 102, 'release_year': 2024, 'rating': 1.9, 'views_count': 107506, 'production_budget': 92334091}, {'_id': 'M066', 'title': 'Last World', 'genre': ['Animation'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 4.1, 'views_count': 139206, 'production_budget': 232940727}, {'_id': 'M067', 'title': 'Smart World', 'genre': ['Documentary', 'Romance', 'Sci-Fi'], 'duration_minutes': 126, 'release_year': 2023, 'rating': 4.0, 'views_count': 125397, 'production_budget': 233435578}, {'_id': 'M068', 'title': 'Protocol', 'genre': ['Comedy', 'Thriller', 'Horror'], 'duration_minutes': 169, 'release_year': 2024, 'rating': 4.2, 'views_count': 110097, 'production_budget': 100149438}, {'_id': 'M069', 'title': 'Last World', 'genre': ['Horror'], 'duration_minutes': 119, 'release_year': 2022, 'rating': 4.0, 'views_count': 12355, 'production_budget': 39301506}, {'_id': 'M070', 'title': 'Lost Adventure', 'genre': ['Drama', 'Sci-Fi'], 'duration_minutes': 171, 'release_year': 2020, 'rating': 1.7, 'views_count': 5512, 'production_budget': 218689270}, {'_id': 'M071', 'title': 'Cyber Tale', 'genre': ['Sci-Fi', 'Drama', 'Comedy'], 'duration_minutes': 102, 'release_year': 2023, 'rating': 4.3, 'views_count': 292824, 'production_budget': 139504878}, {'_id': 'M072', 'title': 'Secret Signal', 'genre': ['Romance'], 'duration_minutes': 125, 'release_year': 2022, 'rating': 1.6, 'views_count': 60180, 'production_budget': 8844926}, {'_id': 'M073', 'title': 'System', 'genre': ['Documentary', 'Animation', 'Action'], 'duration_minutes': 141, 'release_year': 2021, 'rating': 1.3, 'views_count': 12675, 'production_budget': 167251523}, {'_id': 'M074', 'title': 'Digital Database', 'genre': ['Comedy'], 'duration_minutes': 146, 'release_year': 2022, 'rating': 3.2, 'views_count': 8998, 'production_budget': 29227591}, {'_id': 'M075', 'title': 'Neural Journey', 'genre': ['Sci-Fi', 'Thriller', 'Romance'], 'duration_minutes': 125, 'release_year': 2020, 'rating': 4.2, 'views_count': 84468, 'production_budget': 296040480}, {'_id': 'M076', 'title': 'The Journey', 'genre': ['Thriller', 'Documentary', 'Animation'], 'duration_minutes': 166, 'release_year': 2020, 'rating': 2.4, 'views_count': 78189, 'production_budget': 27396354}, {'_id': 'M077', 'title': 'Signal', 'genre': ['Romance'], 'duration_minutes': 101, 'release_year': 2021, 'rating': 4.5, 'views_count': 97638, 'production_budget': 203590741}, {'_id': 'M078', 'title': 'Algorithm', 'genre': ['Comedy', 'Romance', 'Documentary'], 'duration_minutes': 155, 'release_year': 2024, 'rating': 1.6, 'views_count': 28957, 'production_budget': 13524987}, {'_id': 'M079', 'title': 'Secret Algorithm', 'genre': ['Thriller'], 'duration_minutes': 156, 'release_year': 2022, 'rating': 3.8, 'views_count': 44993, 'production_budget': 46138210}, {'_id': 'M080', 'title': 'Digital Empire', 'genre': ['Comedy'], 'duration_minutes': 99, 'release_year': 2022, 'rating': 3.5, 'views_count': 51624, 'production_budget': 49787105}, {'_id': 'M081', 'title': 'A Empire', 'genre': ['Thriller'], 'duration_minutes': 158, 'release_year': 2023, 'rating': 3.2, 'views_count': 20857, 'production_budget': 21843745}, {'_id': 'M082', 'title': 'Protocol', 'genre': ['Romance', 'Action', 'Comedy'], 'duration_minutes': 135, 'release_year': 2023, 'rating': 4.0, 'views_count': 106275, 'production_budget': 182661326}, {'_id': 'M083', 'title': 'Final World', 'genre': ['Horror'], 'duration_minutes': 116, 'release_year': 2023, 'rating': 1.1, 'views_count': 147540, 'production_budget': 9691644}, {'_id': 'M084', 'title': 'The Matrix', 'genre': ['Drama', 'Comedy'], 'duration_minutes': 141, 'release_year': 2021, 'rating': 2.2, 'views_count': 40998, 'production_budget': 49636072}, {'_id': 'M085', 'title': 'Lost Adventure', 'genre': ['Action', 'Romance'], 'duration_minutes': 150, 'release_year': 2022, 'rating': 4.4, 'views_count': 185972, 'production_budget': 272623780}, {'_id': 'M086', 'title': 'Data', 'genre': ['Thriller', 'Horror', 'Animation'], 'duration_minutes': 130, 'release_year': 2021, 'rating': 2.3, 'views_count': 41342, 'production_budget': 25908762}, {'_id': 'M087', 'title': 'A Data', 'genre': ['Action', 'Romance', 'Drama'], 'duration_minutes': 139, 'release_year': 2020, 'rating': 2.7, 'views_count': 41100, 'production_budget': 251619945}, {'_id': 'M088', 'title': 'Data', 'genre': ['Romance'], 'duration_minutes': 146, 'release_year': 2023, 'rating': 1.2, 'views_count': 2689, 'production_budget': 41797064}, {'_id': 'M089', 'title': 'Hidden Data', 'genre': ['Horror', 'Sci-Fi', 'Romance'], 'duration_minutes': 107, 'release_year': 2021, 'rating': 3.0, 'views_count': 48176, 'production_budget': 283777035}, {'_id': 'M090', 'title': 'Network', 'genre': ['Comedy', 'Animation'], 'duration_minutes': 86, 'release_year': 2020, 'rating': 2.6, 'views_count': 38966, 'production_budget': 41347239}, {'_id': 'M091', 'title': 'Empire', 'genre': ['Animation', 'Romance'], 'duration_minutes': 122, 'release_year': 2022, 'rating': 2.5, 'views_count': 48892, 'production_budget': 10832696}, {'_id': 'M092', 'title': 'Infinite Code', 'genre': ['Comedy', 'Horror'], 'duration_minutes': 145, 'release_year': 2021, 'rating': 2.1, 'views_count': 56151, 'production_budget': 16160068}, {'_id': 'M093', 'title': 'Digital Code', 'genre': ['Horror', 'Drama'], 'duration_minutes': 87, 'release_year': 2024, 'rating': 3.8, 'views_count': 97083, 'production_budget': 9974518}, {'_id': 'M094', 'title': 'Matrix', 'genre': ['Action', 'Animation'], 'duration_minutes': 173, 'release_year': 2020, 'rating': 1.2, 'views_count': 48295, 'production_budget': 250209902}, {'_id': 'M095', 'title': 'Digital Tale', 'genre': ['Documentary', 'Comedy', 'Romance'], 'duration_minutes': 131, 'release_year': 2024, 'rating': 3.8, 'views_count': 104163, 'production_budget': 27080387}, {'_id': 'M096', 'title': 'Final Mystery 5', 'genre': ['Romance', 'Comedy', 'Action'], 'duration_minutes': 85, 'release_year': 2022, 'rating': 2.0, 'views_count': 80921, 'production_budget': 134466599}, {'_id': 'M097', 'title': 'Dark Stream', 'genre': ['Horror', 'Comedy'], 'duration_minutes': 131, 'release_year': 2020, 'rating': 4.9, 'views_count': 152164, 'production_budget': 65465290}, {'_id': 'M098', 'title': 'Digital Data', 'genre': ['Horror', 'Thriller', 'Romance'], 'duration_minutes': 142, 'release_year': 2022, 'rating': 2.6, 'views_count': 13908, 'production_budget': 41421645}, {'_id': 'M099', 'title': 'Algorithm', 'genre': ['Animation', 'Romance', 'Action'], 'duration_minutes': 159, 'release_year': 2022, 'rating': 2.3, 'views_count': 53649, 'production_budget': 195742202}, {'_id': 'M100', 'title': 'Mystery', 'genre': ['Animation', 'Drama', 'Comedy'], 'duration_minutes': 145, 'release_year': 2022, 'rating': 2.5, 'views_count': 85093, 'production_budget': 1818805}, {'_id': 'M101', 'title': 'System', 'genre': ['Horror', 'Sci-Fi', 'Drama'], 'duration_minutes': 152, 'release_year': 2024, 'rating': 2.9, 'views_count': 27931, 'production_budget': 122138266}, {'_id': 'M102', 'title': 'A Algorithm', 'genre': ['Drama', 'Action'], 'duration_minutes': 147, 'release_year': 2022, 'rating': 2.8, 'views_count': 26612, 'production_budget': 81782662}, {'_id': 'M103', 'title': 'Quantum Tale', 'genre': ['Sci-Fi', 'Documentary', 'Romance'], 'duration_minutes': 156, 'release_year': 2023, 'rating': 4.6, 'views_count': 138177, 'production_budget': 287247899}, {'_id': 'M104', 'title': 'Binary World', 'genre': ['Sci-Fi', 'Horror', 'Animation'], 'duration_minutes': 109, 'release_year': 2024, 'rating': 3.3, 'views_count': 38659, 'production_budget': 270713263}, {'_id': 'M105', 'title': 'Binary Tale', 'genre': ['Horror', 'Animation'], 'duration_minutes': 104, 'release_year': 2021, 'rating': 2.3, 'views_count': 5

In [ ]:
users_df = pd.read_csv(r'C:\Users\ariel\OneDrive - Universidad Politécnica de Yucatán\Universidad\9th quarter\VMI\Programming\visualization-tools-IX\Inyector\Files\data\users.csv')
users_df

,user_id,age,country,subscription_type,registration_date,total_watch_time_hours
0,U0001,21,Argentina,Basic,2022-10-02,58.0
1,U0002,44,Mexico,Standard,2022-09-30,75.3
2,U0003,20,Argentina,Standard,2023-01-24,360.0
3,U0004,39,Peru,Standard,2022-12-15,513.0
4,U0005,28,Colombia,Basic,2022-05-19,192.8
...,...,...,...,...,...,...
4995,U4996,35,Colombia,Basic,2022-08-18,225.3
4996,U4997,58,Colombia,Basic,2023-09-29,405.1
4997,U4998,19,Colombia,Basic,2023-06-11,277.0
4998,U4999,64,Argentina,Premium,2022-09-27,689.2
4999,U5000,35,Mexico,Standard,2022-03-16,375.3

In [ ]:
"""users_df['registration_date'] = pd.to_datetime(users_df['registration_date'], format="%Y-%m-%d")
users_df['registration_date'].dtype"""

'users_df[\'registration_date\'] = pd.to_datetime(users_df[\'registration_date\'], format="%Y-%m-%d")\nusers_df[\'registration_date\'].dtype'

In [ ]:
json_test = users_df.to_json(path_or_buf=r"C:\Users\ariel\OneDrive - Universidad Politécnica de Yucatán\Universidad\9th quarter\VMI\Programming\visualization-tools-IX\Inyector\Files\data\users_test.json", orient='records')
json_test

In [ ]:
import json
import time
table_name = 'viewing_sessions'
users_df.to_json(path_or_buf=f"./data/{table_name}_processed.json", orient='records')
time.sleep(3)
with open(f"./data/{table_name}_processed.json", "r") as file:
    content = json.load(file)
content

[{'user_id': 'U0001',
  'age': 21,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-10-02',
  'total_watch_time_hours': 58.0},
 {'user_id': 'U0002',
  'age': 44,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-09-30',
  'total_watch_time_hours': 75.3},
 {'user_id': 'U0003',
  'age': 20,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-24',
  'total_watch_time_hours': 360.0},
 {'user_id': 'U0004',
  'age': 39,
  'country': 'Peru',
  'subscription_type': 'Standard',
  'registration_date': '2022-12-15',
  'total_watch_time_hours': 513.0},
 {'user_id': 'U0005',
  'age': 28,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2022-05-19',
  'total_watch_time_hours': 192.8},
 {'user_id': 'U0006',
  'age': 39,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-12-20',
  'total_watch_time_hours': 156.2},
 {'user_id': 'U0007',
  'age': 18,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-03-23',
  'total_watch_time_hours': 428.0},
 {'user_id': 'U0008',
  'age': 56,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-22',
  'total_watch_time_hours': 47.8},
 {'user_id': 'U0009',
  'age': 38,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2024-01-20',
  'total_watch_time_hours': 229.7},
 {'user_id': 'U0010',
  'age': 20,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-04-05',
  'total_watch_time_hours': 444.7},
 {'user_id': 'U0011',
  'age': 26,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-01-22',
  'total_watch_time_hours': 336.6},
 {'user_id': 'U0012',
  'age': 45,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-08-11',
  'total_watch_time_hours': 292.4},
 {'user_id': 'U0013',
  'age': 48,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-02-07',
  'total_watch_time_hours': 386.7},
 {'user_id': 'U0014',
  'age': 39,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-06-19',
  'total_watch_time_hours': 402.7},
 {'user_id': 'U0015',
  'age': 31,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-09-16',
  'total_watch_time_hours': 387.6},
 {'user_id': 'U0016',
  'age': 54,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-11-19',
  'total_watch_time_hours': 17.4},
 {'user_id': 'U0017',
  'age': 59,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-06-10',
  'total_watch_time_hours': 240.7},
 {'user_id': 'U0018',
  'age': 52,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-10-16',
  'total_watch_time_hours': 360.2},
 {'user_id': 'U0019',
  'age': 56,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2023-05-13',
  'total_watch_time_hours': 477.2},
 {'user_id': 'U0020',
  'age': 44,
  'country': 'Peru',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-19',
  'total_watch_time_hours': 311.9},
 {'user_id': 'U0021',
  'age': 59,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-07-05',
  'total_watch_time_hours': 329.1},
 {'user_id': 'U0022',
  'age': 23,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-05-14',
  'total_watch_time_hours': 438.8},
 {'user_id': 'U0023',
  'age': 28,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2022-12-09',
  'total_watch_time_hours': 192.6},
 {'user_id': 'U0024',
  'age': 43,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-03-17',
  'total_watch_time_hours': 728.7},
 {'user_id': 'U0025',
  'age': 42,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-08-10',
  'total_watch_time_hours': 469.9},
 {'user_id': 'U0026',
  'age': 19,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2022-07-13',
  'total_watch_time_hours': 653.9},
 {'user_id': 'U0027',
  'age': 58,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-08',
  'total_watch_time_hours': 17.6},
 {'user_id': 'U0028',
  'age': 40,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2022-08-23',
  'total_watch_time_hours': 208.8},
 {'user_id': 'U0029',
  'age': 50,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2024-01-12',
  'total_watch_time_hours': 496.6},
 {'user_id': 'U0030',
  'age': 21,
  'country': 'Chile',
  'subscription_type': 'Standard',
  'registration_date': '2023-10-17',
  'total_watch_time_hours': 199.3},
 {'user_id': 'U0031',
  'age': 49,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2024-02-22',
  'total_watch_time_hours': 382.4},
 {'user_id': 'U0032',
  'age': 32,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-07-12',
  'total_watch_time_hours': 296.5},
 {'user_id': 'U0033',
  'age': 29,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2022-06-07',
  'total_watch_time_hours': 545.7},
 {'user_id': 'U0034',
  'age': 46,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2023-01-23',
  'total_watch_time_hours': 378.3},
 {'user_id': 'U0035',
  'age': 20,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-01-11',
  'total_watch_time_hours': 100.3},
 {'user_id': 'U0036',
  'age': 30,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2022-01-22',
  'total_watch_time_hours': 271.2},
 {'user_id': 'U0037',
  'age': 40,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-12-03',
  'total_watch_time_hours': 171.9},
 {'user_id': 'U0038',
  'age': 45,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-10-12',
  'total_watch_time_hours': 259.2},
 {'user_id': 'U0039',
  'age': 24,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2023-09-25',
  'total_watch_time_hours': 44.7},
 {'user_id': 'U0040',
  'age': 40,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-12-26',
  'total_watch_time_hours': 64.2},
 {'user_id': 'U0041',
  'age': 45,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-01-09',
  'total_watch_time_hours': 479.9},
 {'user_id': 'U0042',
  'age': 42,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-03-17',
  'total_watch_time_hours': 277.8},
 {'user_id': 'U0043',
  'age': 58,
  'country': 'Peru',
  'subscription_type': 'Premium',
  'registration_date': '2023-02-18',
  'total_watch_time_hours': 43.7},
 {'user_id': 'U0044',
  'age': 38,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2022-09-26',
  'total_watch_time_hours': 478.3},
 {'user_id': 'U0045',
  'age': 20,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2024-02-08',
  'total_watch_time_hours': 313.7},
 {'user_id': 'U0046',
  'age': 44,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-12-23',
  'total_watch_time_hours': 43.3},
 {'user_id': 'U0047',
  'age': 58,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-06-17',
  'total_watch_time_hours': 797.6},
 {'user_id': 'U0048',
  'age': 44,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2022-03-07',
  'total_watch_time_hours': 434.0},
 {'user_id': 'U0049',
  'age': 61,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2022-05-28',
  'total_watch_time_hours': 173.1},
 {'user_id': 'U0050',
  'age': 33,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2024-02-01',
  'total_watch_time_hours': 48.4},
 {'user_id': 'U0051',
  'age': 58,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-02-28',
  'total_watch_time_hours': 412.0},
 {'user_id': 'U0052',
  'age': 42,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2023-07-05',
  'total_watch_time_hours': 160.0},
 {'user_id': 'U0053',
  'age': 59,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2024-03-01',
  'total_watch_time_hours': 495.5},
 {'user_id': 'U0054',
  'age': 42,
  'country': 'Chile',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-13',
  'total_watch_time_hours': 86.4},
 {'user_id': 'U0055',
  'age': 39,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2023-06-14',
  'total_watch_time_hours': 68.6},
 {'user_id': 'U0056',
  'age': 28,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-08-27',
  'total_watch_time_hours': 219.2},
 {'user_id': 'U0057',
  'age': 21,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2024-01-30',
  'total_watch_time_hours': 168.6},
 {'user_id': 'U0058',
  'age': 60,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-01-22',
  'total_watch_time_hours': 195.8},
 {'user_id': 'U0059',
  'age': 65,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2024-01-28',
  'total_watch_time_hours': 391.9},
 {'user_id': 'U0060',
  'age': 63,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2023-11-16',
  'total_watch_time_hours': 415.9},
 {'user_id': 'U0061',
  'age': 45,
  'country': 'Peru',
  'subscription_type': 'Basic',
  'registration_date': '2022-01-29',
  'total_watch_time_hours': 87.7},
 {'user_id': 'U0062',
  'age': 38,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-06-14',
  'total_watch_time_hours': 314.7},
 {'user_id': 'U0063',
  'age': 26,
  'country': 'Peru',
  'subscription_type': 'Premium',
  'registration_date': '2022-12-18',
  'total_watch_time_hours': 561.1},
 {'user_id': 'U0064',
  'age': 52,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2024-01-14',
  'total_watch_time_hours': 206.1},
 {'user_id': 'U0065',
  'age': 54,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2022-12-15',
  'total_watch_time_hours': 49.9},
 {'user_id': 'U0066',
  'age': 50,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-09-07',
  'total_watch_time_hours': 109.6},
 {'user_id': 'U0067',
  'age': 38,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-09-28',
  'total_watch_time_hours': 410.2},
 {'user_id': 'U0068',
  'age': 50,
  'country': 'Peru',
  'subscription_type': 'Basic',
  'registration_date': '2022-03-24',
  'total_watch_time_hours': 478.5},
 {'user_id': 'U0069',
  'age': 50,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2022-07-24',
  'total_watch_time_hours': 381.5},
 {'user_id': 'U0070',
  'age': 19,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-07-18',
  'total_watch_time_hours': 186.7},
 {'user_id': 'U0071',
  'age': 32,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2022-03-29',
  'total_watch_time_hours': 304.0},
 {'user_id': 'U0072',
  'age': 23,
  'country': 'Peru',
  'subscription_type': 'Standard',
  'registration_date': '2022-12-16',
  'total_watch_time_hours': 371.9},
 {'user_id': 'U0073',
  'age': 26,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2023-07-02',
  'total_watch_time_hours': 168.0},
 {'user_id': 'U0074',
  'age': 48,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2023-05-20',
  'total_watch_time_hours': 368.0},
 {'user_id': 'U0075',
  'age': 19,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-09-21',
  'total_watch_time_hours': 791.4},
 {'user_id': 'U0076',
  'age': 54,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2023-05-13',
  'total_watch_time_hours': 318.3},
 {'user_id': 'U0077',
  'age': 32,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2023-05-29',
  'total_watch_time_hours': 463.2},
 {'user_id': 'U0078',
  'age': 57,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2023-10-13',
  'total_watch_time_hours': 11.6},
 {'user_id': 'U0079',
  'age': 56,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2023-09-16',
  'total_watch_time_hours': 873.8},
 {'user_id': 'U0080',
  'age': 39,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-12-14',
  'total_watch_time_hours': 355.8},
 {'user_id': 'U0081',
  'age': 62,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-02-23',
  'total_watch_time_hours': 336.1},
 {'user_id': 'U0082',
  'age': 47,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2023-01-06',
  'total_watch_time_hours': 479.3},
 {'user_id': 'U0083',
  'age': 44,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-11-20',
  'total_watch_time_hours': 371.5},
 {'user_id': 'U0084',
  'age': 46,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-12-18',
  'total_watch_time_hours': 815.2},
 {'user_id': 'U0085',
  'age': 30,
  'country': 'Chile',
  'subscription_type': 'Standard',
  'registration_date': '2022-07-05',
  'total_watch_time_hours': 236.8},
 {'user_id': 'U0086',
  'age': 21,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2023-03-01',
  'total_watch_time_hours': 213.3},
 {'user_id': 'U0087',
  'age': 34,
  'country': 'Chile',
  'subscription_type': 'Premium',
  'registration_date': '2022-06-29',
  'total_watch_time_hours': 859.2},
 {'user_id': 'U0088',
  'age': 42,
  'country': 'Peru',
  'subscription_type': 'Basic',
  'registration_date': '2023-01-13',
  'total_watch_time_hours': 43.9},
 {'user_id': 'U0089',
  'age': 36,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2022-05-06',
  'total_watch_time_hours': 455.0},
 {'user_id': 'U0090',
  'age': 50,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-09-12',
  'total_watch_time_hours': 201.5},
 {'user_id': 'U0091',
  'age': 42,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-02-22',
  'total_watch_time_hours': 297.1},
 {'user_id': 'U0092',
  'age': 37,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2022-04-21',
  'total_watch_time_hours': 476.2},
 {'user_id': 'U0093',
  'age': 63,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-11-29',
  'total_watch_time_hours': 232.0},
 {'user_id': 'U0094',
  'age': 46,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-09-30',
  'total_watch_time_hours': 506.4},
 {'user_id': 'U0095',
  'age': 54,
  'country': 'Peru',
  'subscription_type': 'Standard',
  'registration_date': '2023-08-09',
  'total_watch_time_hours': 192.9},
 {'user_id': 'U0096',
  'age': 62,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-04-12',
  'total_watch_time_hours': 275.9},
 {'user_id': 'U0097',
  'age': 35,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-12-12',
  'total_watch_time_hours': 573.5},
 {'user_id': 'U0098',
  'age': 29,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-05-07',
  'total_watch_time_hours': 26.1},
 {'user_id': 'U0099',
  'age': 60,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-05-24',
  'total_watch_time_hours': 399.1},
 {'user_id': 'U0100',
  'age': 48,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-07-02',
  'total_watch_time_hours': 31.0},
 {'user_id': 'U0101',
  'age': 52,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2022-05-25',
  'total_watch_time_hours': 152.7},
 {'user_id': 'U0102',
  'age': 41,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-08-15',
  'total_watch_time_hours': 605.7},
 {'user_id': 'U0103',
  'age': 20,
  'country': 'Chile',
  'subscription_type': 'Standard',
  'registration_date': '2023-04-20',
  'total_watch_time_hours': 339.3},
 {'user_id': 'U0104',
  'age': 56,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-10-23',
  'total_watch_time_hours': 384.3},
 {'user_id': 'U0105',
  'age': 18,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-11-25',
  'total_watch_time_hours': 404.4},
 {'user_id': 'U0106',
  'age': 32,
  'country': 'Chile',
  'subscription_type': 'Standard',
  'registration_date': '2023-12-06',
  'total_watch_time_hours': 534.0},
 {'user_id': 'U0107',
  'age': 34,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-10-19',
  'total_watch_time_hours': 184.7},
 {'user_id': 'U0108',
  'age': 44,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-02',
  'total_watch_time_hours': 261.9},
 {'user_id': 'U0109',
  'age': 56,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2022-01-14',
  'total_watch_time_hours': 228.1},
 {'user_id': 'U0110',
  'age': 28,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2022-07-22',
  'total_watch_time_hours': 36.1},
 {'user_id': 'U0111',
  'age': 51,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-06-19',
  'total_watch_time_hours': 691.7},
 {'user_id': 'U0112',
  'age': 51,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2022-07-18',
  'total_watch_time_hours': 285.0},
 {'user_id': 'U0113',
  'age': 47,
  'country': 'Peru',
  'subscription_type': 'Basic',
  'registration_date': '2022-08-18',
  'total_watch_time_hours': 148.4},
 {'user_id': 'U0114',
  'age': 23,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-04-16',
  'total_watch_time_hours': 299.5},
 {'user_id': 'U0115',
  'age': 52,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-07-25',
  'total_watch_time_hours': 132.2},
 {'user_id': 'U0116',
  'age': 30,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2023-06-18',
  'total_watch_time_hours': 471.0},
 {'user_id': 'U0117',
  'age': 22,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2023-10-13',
  'total_watch_time_hours': 1034.7},
 {'user_id': 'U0118',
  'age': 44,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2023-04-05',
  'total_watch_time_hours': 64.4},
 {'user_id': 'U0119',
  'age': 54,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2023-03-20',
  'total_watch_time_hours': 689.8},
 {'user_id': 'U0120',
  'age': 45,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-06-14',
  'total_watch_time_hours': 221.6},
 {'user_id': 'U0121',
  'age': 49,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-05-18',

In [ ]:
users_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 5000 non-null   object
 1   age                     5000 non-null   int64
 2   country                 5000 non-null   object
 3   subscription_type       5000 non-null   object
 4   registration_date       5000 non-null   object
 5   total_watch_time_hours  5000 non-null   float64
dtypes: float64(1), int64(1), object(4)
memory usage: 234.5+ KB

In [ ]:
users_df['subscription_type'].astype(str)
users_df['subscription_type'].dtype

dtype('O')

In [ ]:
users_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 5000 non-null   object
 1   age                     5000 non-null   int64
 2   country                 5000 non-null   object
 3   subscription_type       5000 non-null   object
 4   registration_date       5000 non-null   object
 5   total_watch_time_hours  5000 non-null   float64
dtypes: float64(1), int64(1), object(4)
memory usage: 234.5+ KB

In [ ]:
users_columns = users_df.columns.to_list()
users_columns

['user_id',
 'age',
 'country',
 'subscription_type',
 'registration_date',
 'total_watch_time_hours']

In [ ]:
my_list = []
my_dict = {}
for header in users_columns:
    my_dict[header] = 'ola'
    my_list.append(my_dict)
my_list

[{'user_id': 'ola',
  'age': 'ola',
  'country': 'ola',
  'subscription_type': 'ola',
  'registration_date': 'ola',
  'total_watch_time_hours': 'ola'},
 {'user_id': 'ola',
  'age': 'ola',
  'country': 'ola',
  'subscription_type': 'ola',
  'registration_date': 'ola',
  'total_watch_time_hours': 'ola'},
 {'user_id': 'ola',
  'age': 'ola',
  'country': 'ola',
  'subscription_type': 'ola',
  'registration_date': 'ola',
  'total_watch_time_hours': 'ola'},
 {'user_id': 'ola',
  'age': 'ola',
  'country': 'ola',
  'subscription_type': 'ola',
  'registration_date': 'ola',
  'total_watch_time_hours': 'ola'},
 {'user_id': 'ola',
  'age': 'ola',
  'country': 'ola',
  'subscription_type': 'ola',
  'registration_date': 'ola',
  'total_watch_time_hours': 'ola'},
 {'user_id': 'ola',
  'age': 'ola',
  'country': 'ola',
  'subscription_type': 'ola',
  'registration_date': 'ola',
  'total_watch_time_hours': 'ola'}]

In [ ]:
data = {}
items = []
for column in users_columns:
    column_data_formatted = users_df[column].to_list()
    for item in column_data_formatted:
        items.append(f'({item})')
    data[column] = items
    items = []
data

{'user_id': ['(U0001)',
  '(U0002)',
  '(U0003)',
  '(U0004)',
  '(U0005)',
  '(U0006)',
  '(U0007)',
  '(U0008)',
  '(U0009)',
  '(U0010)',
  '(U0011)',
  '(U0012)',
  '(U0013)',
  '(U0014)',
  '(U0015)',
  '(U0016)',
  '(U0017)',
  '(U0018)',
  '(U0019)',
  '(U0020)',
  '(U0021)',
  '(U0022)',
  '(U0023)',
  '(U0024)',
  '(U0025)',
  '(U0026)',
  '(U0027)',
  '(U0028)',
  '(U0029)',
  '(U0030)',
  '(U0031)',
  '(U0032)',
  '(U0033)',
  '(U0034)',
  '(U0035)',
  '(U0036)',
  '(U0037)',
  '(U0038)',
  '(U0039)',
  '(U0040)',
  '(U0041)',
  '(U0042)',
  '(U0043)',
  '(U0044)',
  '(U0045)',
  '(U0046)',
  '(U0047)',
  '(U0048)',
  '(U0049)',
  '(U0050)',
  '(U0051)',
  '(U0052)',
  '(U0053)',
  '(U0054)',
  '(U0055)',
  '(U0056)',
  '(U0057)',
  '(U0058)',
  '(U0059)',
  '(U0060)',
  '(U0061)',
  '(U0062)',
  '(U0063)',
  '(U0064)',
  '(U0065)',
  '(U0066)',
  '(U0067)',
  '(U0068)',
  '(U0069)',
  '(U0070)',
  '(U0071)',
  '(U0072)',
  '(U0073)',
  '(U0074)',
  '(U0075)',
  '(U0076)',
  '(U0077)',
  '(U0078)',
  '(U0079)',
  '(U0080)',
  '(U0081)',
  '(U0082)',
  '(U0083)',
  '(U0084)',
  '(U0085)',
  '(U0086)',
  '(U0087)',
  '(U0088)',
  '(U0089)',
  '(U0090)',
  '(U0091)',
  '(U0092)',
  '(U0093)',
  '(U0094)',
  '(U0095)',
  '(U0096)',
  '(U0097)',
  '(U0098)',
  '(U0099)',
  '(U0100)',
  '(U0101)',
  '(U0102)',
  '(U0103)',
  '(U0104)',
  '(U0105)',
  '(U0106)',
  '(U0107)',
  '(U0108)',
  '(U0109)',
  '(U0110)',
  '(U0111)',
  '(U0112)',
  '(U0113)',
  '(U0114)',
  '(U0115)',
  '(U0116)',
  '(U0117)',
  '(U0118)',
  '(U0119)',
  '(U0120)',
  '(U0121)',
  '(U0122)',
  '(U0123)',
  '(U0124)',
  '(U0125)',
  '(U0126)',
  '(U0127)',
  '(U0128)',
  '(U0129)',
  '(U0130)',
  '(U0131)',
  '(U0132)',
  '(U0133)',
  '(U0134)',
  '(U0135)',
  '(U0136)',
  '(U0137)',
  '(U0138)',
  '(U0139)',
  '(U0140)',
  '(U0141)',
  '(U0142)',
  '(U0143)',
  '(U0144)',
  '(U0145)',
  '(U0146)',
  '(U0147)',
  '(U0148)',
  '(U0149)',
  '(U0150)',
  '(U0151)',
  '(U0152)',
  '(U0153)',
  '(U0154)',
  '(U0155)',
  '(U0156)',
  '(U0157)',
  '(U0158)',
  '(U0159)',
  '(U0160)',
  '(U0161)',
  '(U0162)',
  '(U0163)',
  '(U0164)',
  '(U0165)',
  '(U0166)',
  '(U0167)',
  '(U0168)',
  '(U0169)',
  '(U0170)',
  '(U0171)',
  '(U0172)',
  '(U0173)',
  '(U0174)',
  '(U0175)',
  '(U0176)',
  '(U0177)',
  '(U0178)',
  '(U0179)',
  '(U0180)',
  '(U0181)',
  '(U0182)',
  '(U0183)',
  '(U0184)',
  '(U0185)',
  '(U0186)',
  '(U0187)',
  '(U0188)',
  '(U0189)',
  '(U0190)',
  '(U0191)',
  '(U0192)',
  '(U0193)',
  '(U0194)',
  '(U0195)',
  '(U0196)',
  '(U0197)',
  '(U0198)',
  '(U0199)',
  '(U0200)',
  '(U0201)',
  '(U0202)',
  '(U0203)',
  '(U0204)',
  '(U0205)',
  '(U0206)',
  '(U0207)',
  '(U0208)',
  '(U0209)',
  '(U0210)',
  '(U0211)',
  '(U0212)',
  '(U0213)',
  '(U0214)',
  '(U0215)',
  '(U0216)',
  '(U0217)',
  '(U0218)',
  '(U0219)',
  '(U0220)',
  '(U0221)',
  '(U0222)',
  '(U0223)',
  '(U0224)',
  '(U0225)',
  '(U0226)',
  '(U0227)',
  '(U0228)',
  '(U0229)',
  '(U0230)',
  '(U0231)',
  '(U0232)',
  '(U0233)',
  '(U0234)',
  '(U0235)',
  '(U0236)',
  '(U0237)',
  '(U0238)',
  '(U0239)',
  '(U0240)',
  '(U0241)',
  '(U0242)',
  '(U0243)',
  '(U0244)',
  '(U0245)',
  '(U0246)',
  '(U0247)',
  '(U0248)',
  '(U0249)',
  '(U0250)',
  '(U0251)',
  '(U0252)',
  '(U0253)',
  '(U0254)',
  '(U0255)',
  '(U0256)',
  '(U0257)',
  '(U0258)',
  '(U0259)',
  '(U0260)',
  '(U0261)',
  '(U0262)',
  '(U0263)',
  '(U0264)',
  '(U0265)',
  '(U0266)',
  '(U0267)',
  '(U0268)',
  '(U0269)',
  '(U0270)',
  '(U0271)',
  '(U0272)',
  '(U0273)',
  '(U0274)',
  '(U0275)',
  '(U0276)',
  '(U0277)',
  '(U0278)',
  '(U0279)',
  '(U0280)',
  '(U0281)',
  '(U0282)',
  '(U0283)',
  '(U0284)',
  '(U0285)',
  '(U0286)',
  '(U0287)',
  '(U0288)',
  '(U0289)',
  '(U0290)',
  '(U0291)',
  '(U0292)',
  '(U0293)',
  '(U0294)',
  '(U0295)',
  '(U0296)',
  '(U0297)',
  '(U0298)',
  '(U0299)',
  '(U0300)',
  '(U0301)',
  '(U0302)',
  '(U0303)',
  '(U0304)',
  '(U0305)',
  '(U0306)',
  '(U0307)',
  '(U0308)',
  '(U0309)',
  '(U0310)',
  '(U0311)',
  '(U0312)',
  '(U0313)',
  '(U0314)',
  '(U0315)',
  '(U0316)',
  '(U0317)',
  '(U0318)',
  '(U0319)',
  '(U0320)',
  '(U0321)',
  '(U0322)',
  '(U0323)',
  '(U0324)',
  '(U0325)',
  '(U0326)',
  '(U0327)',
  '(U0328)',
  '(U0329)',
  '(U0330)',
  '(U0331)',
  '(U0332)',
  '(U0333)',
  '(U0334)',
  '(U0335)',
  '(U0336)',
  '(U0337)',
  '(U0338)',
  '(U0339)',
  '(U0340)',
  '(U0341)',
  '(U0342)',
  '(U0343)',
  '(U0344)',
  '(U0345)',
  '(U0346)',
  '(U0347)',
  '(U0348)',
  '(U0349)',
  '(U0350)',
  '(U0351)',
  '(U0352)',
  '(U0353)',
  '(U0354)',
  '(U0355)',
  '(U0356)',
  '(U0357)',
  '(U0358)',
  '(U0359)',
  '(U0360)',
  '(U0361)',
  '(U0362)',
  '(U0363)',
  '(U0364)',
  '(U0365)',
  '(U0366)',
  '(U0367)',
  '(U0368)',
  '(U0369)',
  '(U0370)',
  '(U0371)',
  '(U0372)',
  '(U0373)',
  '(U0374)',
  '(U0375)',
  '(U0376)',
  '(U0377)',
  '(U0378)',
  '(U0379)',
  '(U0380)',
  '(U0381)',
  '(U0382)',
  '(U0383)',
  '(U0384)',
  '(U0385)',
  '(U0386)',
  '(U0387)',
  '(U0388)',
  '(U0389)',
  '(U0390)',
  '(U0391)',
  '(U0392)',
  '(U0393)',
  '(U0394)',
  '(U0395)',
  '(U0396)',
  '(U0397)',
  '(U0398)',
  '(U0399)',
  '(U0400)',
  '(U0401)',
  '(U0402)',
  '(U0403)',
  '(U0404)',
  '(U0405)',
  '(U0406)',
  '(U0407)',
  '(U0408)',
  '(U0409)',
  '(U0410)',
  '(U0411)',
  '(U0412)',
  '(U0413)',
  '(U0414)',
  '(U0415)',
  '(U0416)',
  '(U0417)',
  '(U0418)',
  '(U0419)',
  '(U0420)',
  '(U0421)',
  '(U0422)',
  '(U0423)',
  '(U0424)',
  '(U0425)',
  '(U0426)',
  '(U0427)',
  '(U0428)',
  '(U0429)',
  '(U0430)',
  '(U0431)',
  '(U0432)',
  '(U0433)',
  '(U0434)',
  '(U0435)',
  '(U0436)',
  '(U0437)',
  '(U0438)',
  '(U0439)',
  '(U0440)',
  '(U0441)',
  '(U0442)',
  '(U0443)',
  '(U0444)',
  '(U0445)',
  '(U0446)',
  '(U0447)',
  '(U0448)',
  '(U0449)',
  '(U0450)',
  '(U0451)',
  '(U0452)',
  '(U0453)',
  '(U0454)',
  '(U0455)',
  '(U0456)',
  '(U0457)',
  '(U0458)',
  '(U0459)',
  '(U0460)',
  '(U0461)',
  '(U0462)',
  '(U0463)',
  '(U0464)',
  '(U0465)',
  '(U0466)',
  '(U0467)',
  '(U0468)',
  '(U0469)',
  '(U0470)',
  '(U0471)',
  '(U0472)',
  '(U0473)',
  '(U0474)',
  '(U0475)',
  '(U0476)',
  '(U0477)',
  '(U0478)',
  '(U0479)',
  '(U0480)',
  '(U0481)',
  '(U0482)',
  '(U0483)',
  '(U0484)',
  '(U0485)',
  '(U0486)',
  '(U0487)',
  '(U0488)',
  '(U0489)',
  '(U0490)',
  '(U0491)',
  '(U0492)',
  '(U0493)',
  '(U0494)',
  '(U0495)',
  '(U0496)',
  '(U0497)',
  '(U0498)',
  '(U0499)',
  '(U0500)',
  '(U0501)',
  '(U0502)',
  '(U0503)',
  '(U0504)',
  '(U0505)',
  '(U0506)',
  '(U0507)',
  '(U0508)',
  '(U0509)',
  '(U0510)',
  '(U0511)',
  '(U0512)',
  '(U0513)',
  '(U0514)',
  '(U0515)',
  '(U0516)',
  '(U0517)',
  '(U0518)',
  '(U0519)',
  '(U0520)',
  '(U0521)',
  '(U0522)',
  '(U0523)',
  '(U0524)',
  '(U0525)',
  '(U0526)',
  '(U0527)',
  '(U0528)',
  '(U0529)',
  '(U0530)',
  '(U0531)',
  '(U0532)',
  '(U0533)',
  '(U0534)',
  '(U0535)',
  '(U0536)',
  '(U0537)',
  '(U0538)',
  '(U0539)',
  '(U0540)',
  '(U0541)',
  '(U0542)',
  '(U0543)',
  '(U0544)',
  '(U0545)',
  '(U0546)',
  '(U0547)',
  '(U0548)',
  '(U0549)',
  '(U0550)',
  '(U0551)',
  '(U0552)',
  '(U0553)',
  '(U0554)',
  '(U0555)',
  '(U0556)',
  '(U0557)',
  '(U0558)',
  '(U0559)',
  '(U0560)',
  '(U0561)',
  '(U0562)',
  '(U0563)',
  '(U0564)',
  '(U0565)',
  '(U0566)',
  '(U0567)',
  '(U0568)',
  '(U0569)',
  '(U0570)',
  '(U0571)',
  '(U0572)',
  '(U0573)',
  '(U0574)',
  '(U0575)',
  '(U0576)',
  '(U0577)',
  '(U0578)',
  '(U0579)',
  '(U0580)',
  '(U0581)',
  '(U0582)',
  '(U0583)',
  '(U0584)',
  '(U0585)',
  '(U0586)',
  '(U0587)',
  '(U0588)',
  '(U0589)',
  '(U0590)',
  '(U0591)',
  '(U0592)',
  '(U0593)',
  '(U0594)',
  '(U0595)',
  '(U0596)',
  '(U0597)',
  '(U0598)',
  '(U0599)',
  '(U0600)',
  '(U0601)',
  '(U0602)',
  '(U0603)',
  '(U0604)',
  '(U0605)',
  '(U0606)',
  '(U0607)',
  '(U0608)',
  '(U0609)',
  '(U0610)',
  '(U0611)',
  '(U0612)',
  '(U0613)',
  '(U0614)',
  '(U0615)',
  '(U0616)',
  '(U0617)',
  '(U0618)',
  '(U0619)',
  '(U0620)',
  '(U0621)',
  '(U0622)',
  '(U0623)',
  '(U0624)',
  '(U0625)',
  '(U0626)',
  '(U0627)',
  '(U0628)',
  '(U0629)',
  '(U0630)',
  '(U0631)',
  '(U0632)',
  '(U0633)',
  '(U0634)',
  '(U0635)',
  '(U0636)',
  '(U0637)',
  '(U0638)',
  '(U0639)',
  '(U0640)',
  '(U0641)',
  '(U0642)',
  '(U0643)',
  '(U0644)',
  '(U0645)',
  '(U0646)',
  '(U0647)',
  '(U0648)',
  '(U0649)',
  '(U0650)',
  '(U0651)',
  '(U0652)',
  '(U0653)',
  '(U0654)',
  '(U0655)',
  '(U0656)',
  '(U0657)',
  '(U0658)',
  '(U0659)',
  '(U0660)',
  '(U0661)',
  '(U0662)',
  '(U0663)',
  '(U0664)',
  '(U0665)',
  '(U0666)',
  '(U0667)',
  '(U0668)',
  '(U0669)',
  '(U0670)',
  '(U0671)',
  '(U0672)',
  '(U0673)',
  '(U0674)',
  '(U0675)',
  '(U0676)',
  '(U0677)',
  '(U0678)',
  '(U0679)',
  '(U0680)',
  '(U0681)',
  '(U0682)',
  '(U0683)',
  '(U0684)',
  '(U0685)',
  '(U0686)',
  '(U0687)',
  '(U0688)',
  '(U0689)',
  '(U0690)',
  '(U0691)',
  '(U0692)',
  '(U0693)',
  '(U0694)',
  '(U0695)',
  '(U0696)',
  '(U0697)',
  '(U0698)',
  '(U0699)',
  '(U0700)',
  '(U0701)',
  '(U0702)',
  '(U0703)',
  '(U0704)',
  '(U0705)',
  '(U0706)',
  '(U0707)',
  '(U0708)',
  '(U0709)',
  '(U0710)',
  '(U0711)',
  '(U0712)',
  '(U0713)',
  '(U0714)',
  '(U0715)',
  '(U0716)',
  '(U0717)',
  '(U0718)',
  '(U0719)',
  '(U0720)',
  '(U0721)',
  '(U0722)',
  '(U0723)',
  '(U0724)',
  '(U0725)',
  '(U0726)',
  '(U0727)',
  '(U0728)',
  '(U0729)',
  '(U0730)',
  '(U0731)',
  '(U0732)',
  '(U0733)',
  '(U0734)',
  '(U0735)',
  '(U0736)',
  '(U0737)',
  '(U0738)',
  '(U0739)',
  '(U0740)',
  '(U0741)',
  '(U0742)',
  '(U0743)',
  '(U0744)',
  '(U0745)',
  '(U0746)',
  '(U0747)',
  '(U0748)',
  '(U0749)',
  '(U0750)',
  '(U0751)',
  '(U0752)',
  '(U0753)',
  '(U0754)',
  '(U0755)',
  '(U0756)',
  '(U0757)',
  '(U0758)',
  '(U0759)',
  '(U0760)',
  '(U0761)',
  '(U0762)',
  '(U0763)',
  '(U0764)',
  '(U0765)',
  '(U0766)',
  '(U0767)',
  '(U0768)',
  '(U0769)',
  '(U0770)',
  '(U0771)',
  '(U0772)',
  '(U0773)',
  '(U0774)',
  '(U0775)',
  '(U0776)',
  '(U0777)',
  '(U0778)',
  '(U0779)',
  '(U0780)',
  '(U0781)',
  '(U0782)',
  '(U0783)',
  '(U0784)',
  '(U0785)',
  '(U0786)',
  '(U0787)',
  '(U0788)',
  '(U0789)',
  '(U0790)',
  '(U0791)',
  '(U0792)',
  '(U0793)',
  '(U0794)',
  '(U0795)',
  '(U0796)',
  '(U0797)',
  '(U0798)',
  '(U0799)',
  '(U0800)',
  '(U0801)',
  '(U0802)',
  '(U0803)',
  '(U0804)',
  '(U0805)',
  '(U0806)',
  '(U0807)',
  '(U0808)',
  '(U0809)',
  '(U0810)',
  '(U0811)',
  '(U0812)',
  '(U0813)',
  '(U0814)',
  '(U0815)',
  '(U0816)',
  '(U0817)',
  '(U0818)',
  '(U0819)',
  '(U0820)',
  '(U0821)',
  '(U0822)',
  '(U0823)',
  '(U0824)',
  '(U0825)',
  '(U0826)',
  '(U0827)',
  '(U0828)',
  '(U0829)',
  '(U0830)',
  '(U0831)',
  '(U0832)',
  '(U0833)',
  '(U0834)',
  '(U0835)',
  '(U0836)',
  '(U0837)',
  '(U0838)',
  '(U0839)',
  '(U0840)',
  '(U0841)',
  '(U0842)',
  '(U0843)',
  '(U0844)',
  '(U0845)',
  '(U0846)',
  '(U0847)',
  '(U0848)',
  '(U0849)',
  '(U0850)',
  '(U0851)',
  '(U0852)',
  '(U0853)',
  '(U0854)',
  '(U0855)',
  '(U0856)',
  '(U0857)',
  '(U0858)',
  '(U0859)',
  '(U0860)',
  '(U0861)',
  '(U0862)',
  '(U0863)',
  '(U0864)',
  '(U0865)',
  '(U0866)',
  '(U0867)',
  '(U0868)',
  '(U0869)',
  '(U0870)',
  '(U0871)',
  '(U0872)',
  '(U0873)',
  '(U0874)',
  '(U0875)',
  '(U0876)',
  '(U0877)',
  '(U0878)',
  '(U0879)',
  '(U0880)',
  '(U0881)',
  '(U0882)',
  '(U0883)',
  '(U0884)',
  '(U0885)',
  '(U0886)',
  '(U0887)',
  '(U0888)',
  '(U0889)',
  '(U0890)',
  '(U0891)',
  '(U0892)',
  '(U0893)',
  '(U0894)',
  '(U0895)',
  '(U0896)',
  '(U0897)',
  '(U0898)',
  '(U0899)',
  '(U0900)',
  '(U0901)',
  '(U0902)',
  '(U0903)',
  '(U0904)',
  '(U0905)',
  '(U0906)',
  '(U0907)',
  '(U0908)',
  '(U0909)',
  '(U0910)',
  '(U0911)',
  '(U0912)',
  '(U0913)',
  '(U0914)',
  '(U0915)',
  '(U0916)',
  '(U0917)',
  '(U0918)',
  '(U0919)',
  '(U0920)',
  '(U0921)',
  '(U0922)',
  '(U0923)',
  '(U0924)',
  '(U0925)',
  '(U0926)',
  '(U0927)',
  '(U0928)',
  '(U0929)',
  '(U0930)',
  '(U0931)',
  '(U0932)',
  '(U0933)',
  '(U0934)',
  '(U0935)',
  '(U0936)',
  '(U0937)',
  '(U0938)',
  '(U0939)',
  '(U0940)',
  '(U0941)',
  '(U0942)',
  '(U0943)',
  '(U0944)',
  '(U0945)',
  '(U0946)',
  '(U0947)',
  '(U0948)',
  '(U0949)',
  '(U0950)',
  '(U0951)',
  '(U0952)',
  '(U0953)',
  '(U0954)',
  '(U0955)',
  '(U0956)',
  '(U0957)',
  '(U0958)',
  '(U0959)',
  '(U0960)',
  '(U0961)',
  '(U0962)',
  '(U0963)',
  '(U0964)',
  '(U0965)',
  '(U0966)',
  '(U0967)',
  '(U0968)',
  '(U0969)',
  '(U0970)',
  '(U0971)',
  '(U0972)',
  '(U0973)',
  '(U0974)',
  '(U0975)',
  '(U0976)',
  '(U0977)',
  '(U0978)',
  '(U0979)',
  '(U0980)',
  '(U0981)',
  '(U0982)',
  '(U0983)',
  '(U0984)',
  '(U0985)',
  '(U0986)',
  '(U0987)',
  '(U0988)',
  '(U0989)',
  '(U0990)',
  '(U0991)',
  '(U0992)',
  '(U0993)',
  '(U0994)',
  '(U0995)',
  '(U0996)',
  '(U0997)',
  '(U0998)',
  '(U0999)',
  '(U1000)',
  ...],
 'age': ['(21)',
  '(44)',
  '(20)',
  '(39)',
  '(28)',
  '(39)',
  '(18)',
  '(56)',
  '(38)',
  '(20)',
  '(26)',
  '(45)',
  '(48)',
  '(39)',
  '(31)',
  '(54)',
  '(59)',
  '(52)',
  '(56)',
  '(44)',
  '(59)',
  '(23)',
  '(28)',
  '(43)',
  '(42)',
  '(19)',
  '(58)',
  '(40)',
  '(50)',
  '(21)',
  '(49)',
  '(32)',
  '(29)',
  '(46)',
  '(20)',
  '(30)',
  '(40)',
  '(45)',
  '(24)',
  '(40)',
  '(45)',
  '(42)',
  '(58)',
  '(38)',
  '(20)',
  '(44)',
  '(58)',
  '(44)',
  '(61)',
  '(33)',
  '(58)',
  '(42)',
  '(59)',
  '(42)',
  '(39)',
  '(28)',
  '(21)',
  '(60)',
  '(65)',
  '(63)',
  '(45)',
  '(38)',
  '(26)',
  '(52)',
  '(54)',
  '(50)',
  '(38)',
  '(50)',
  '(50)',
  '(19)',
  '(32)',
  '(23)',
  '(26)',
  '(48)',
  '(19)',
  '(54)',
  '(32)',
  '(57)',
  '(56)',
  '(39)',
  '(62)',
  '(47)',
  '(44)',
  '(46)',
  '(30)',
  '(21)',
  '(34)',
  '(42)',
  '(36)',
  '(50)',
  '(42)',
  '(37)',
  '(63)',
  '(46)',
  '(54)',
  '(62)',
  '(35)',
  '(29)',
  '(60)',
  '(48)',
  '(52)',
  '(41)',
  '(20)',
  '(56)',
  '(18)',
  '(32)',
  '(34)',
  '(44)',
  '(56)',
  '(28)',
  '(51)',
  '(51)',
  '(47)',
  '(23)',
  '(52)',
  '(30)',
  '(22)',
  '(44)',
  '(54)',
  '(45)',
  '(49)',
  '(31)',
  '(33)',
  '(19)',
  '(38)',
  '(33)',
  '(45)',
  '(29)',
  '(60)',
  '(31)',
  '(41)',
  '(44)',
  '(45)',
  '(42)',
  '(49)',
  '(48)',
  '(24)',
  '(40)',
  '(46)',
  '(41)',
  '(21)',
  '(24)',
  '(65)',
  '(31)',
  '(26)',
  '(18)',
  '(23)',
  '(27)',
  '(30)',
  '(21)',
  '(62)',
  '(20)',
  '(31)',
  '(45)',
  '(23)',
  '(38)',
  '(32)',
  '(22)',
  '(36)',
  '(18)',
  '(59)',
  '(44)',
  '(58)',
  '(20)',
  '(38)',
  '(40)',
  '(59)',
  '(64)',
  '(46)',
  '(65)',
  '(58)',
  '(31)',
  '(48)',
  '(53)',
  '(19)',
  '(58)',
  '(30)',
  '(26)',
  '(35)',
  '(22)',
  '(34)',
  '(44)',
  '(51)',
  '(60)',
  '(39)',
  '(58)',
  '(37)',
  '(18)',
  '(57)',
  '(46)',
  '(40)',
  '(26)',
  '(31)',
  '(44)',
  '(23)',
  '(44)',
  '(42)',
  '(19)',
  '(43)',
  '(58)',
  '(30)',
  '(53)',
  '(19)',
  '(36)',
  '(49)',
  '(27)',
  '(53)',
  '(22)',
  '(30)',
  '(45)',
  '(41)',
  '(31)',
  '(52)',
  '(31)',
  '(59)',
  '(63)',
  '(64)',
  '(39)',
  '(60)',
  '(60)',
  '(20)',
  '(59)',
  '(60)',
  '(50)',
  '(36)',
  '(52)',
  '(53)',
  '(18)',
  '(27)',
  '(60)',
  '(59)',
  '(53)',
  '(36)',
  '(59)',
  '(52)',
  '(55)',
  '(39)',
  '(41)',
  '(49)',
  '(60)',
  '(60)',
  '(54)',
  '(50)',
  '(49)',
  '(58)',
  '(38)',
  '(44)',
  '(35)',
  '(29)',
  '(63)',
  '(63)',
  '(20)',
  '(59)',
  '(43)',
  '(53)',
  '(59)',
  '(49)',
  '(48)',
  '(61)',
  '(32)',
  '(48)',
  '(58)',
  '(62)',
  '(46)',
  '(20)',
  '(41)',
  '(62)',
  '(53)',
  '(55)',
  '(32)',
  '(59)',
  '(61)',
  '(18)',
  '(26)',
  '(40)',
  '(22)',
  '(21)',
  '(51)',
  '(50)',
  '(49)',
  '(29)',
  '(62)',
  '(25)',
  '(50)',
  '(34)',
  '(41)',
  '(22)',
  '(59)',
  '(45)',
  '(44)',
  '(37)',
  '(64)',
  '(22)',
  '(25)',
  '(50)',
  '(31)',
  '(36)',
  '(48)',
  '(20)',
  '(27)',
  '(62)',
  '(37)',
  '(48)',
  '(46)',
  '(35)',
  '(36)',
  '(47)',
  '(57)',
  '(54)',
  '(32)',
  '(44)',
  '(57)',
  '(36)',
  '(33)',
  '(65)',
  '(53)',
  '(62)',
  '(28)',
  '(26)',
  '(37)',
  '(47)',
  '(57)',
  '(55)',
  '(37)',
  '(46)',
  '(39)',
  '(28)',
  '(33)',
  '(23)',
  '(45)',
  '(53)',
  '(60)',
  '(44)',
  '(37)',
  '(26)',
  '(43)',
  '(37)',
  '(56)',
  '(27)',
  '(65)',
  '(50)',
  '(55)',
  '(30)',
  '(32)',
  '(25)',
  '(29)',
  '(64)',
  '(60)',
  '(58)',
  '(45)',
  '(22)',
  '(37)',
  '(27)',
  '(30)',
  '(23)',
  '(49)',
  '(38)',
  '(52)',
  '(46)',
  '(34)',
  '(65)',
  '(37)',
  '(48)',
  '(25)',
  '(62)',
  '(51)',
  '(59)',
  '(46)',
  '(29)',
  '(61)',
  '(46)',
  '(61)',
  '(45)',
  '(34)',
  '(43)',
  '(61)',
  '(32)',
  '(56)',
  '(56)',
  '(63)',
  '(63)',
  '(39)',
  '(21)',
  '(26)',
  '(29)',
  '(28)',
  '(29)',
  '(43)',
  '(42)',
  '(62)',
  '(26)',
  '(46)',
  '(23)',
  '(44)',
  '(47)',
  '(57)',
  '(27)',
  '(32)',
  '(20)',
  '(41)',
  '(32)',
  '(22)',
  '(50)',
  '(49)',
  '(30)',
  '(58)',
  '(57)',
  '(20)',
  '(30)',
  '(35)',
  '(52)',
  '(33)',
  '(41)',
  '(41)',
  '(21)',
  '(41)',
  '(54)',
  '(43)',
  '(39)',
  '(58)',
  '(37)',
  '(46)',
  '(30)',
  '(48)',
  '(61)',
  '(49)',
  '(41)',
  '(51)',
  '(27)',
  '(21)',
  '(61)',
  '(31)',
  '(59)',
  '(57)',
  '(45)',
  '(50)',
  '(30)',
  '(58)',
  '(56)',
  '(60)',
  '(49)',
  '(61)',
  '(22)',
  '(59)',
  '(62)',
  '(45)',
  '(40)',
  '(55)',
  '(45)',
  '(47)',
  '(49)',
  '(62)',
  '(28)',
  '(26)',
  '(34)',
  '(33)',
  '(22)',
  '(39)',
  '(28)',
  '(65)',
  '(60)',
  '(45)',
  '(60)',
  '(60)',
  '(46)',
  '(53)',
  '(33)',
  '(35)',
  '(24)',
  '(61)',
  '(41)',
  '(37)',
  '(62)',
  '(23)',
  '(51)',
  '(43)',
  '(39)',
  '(31)',
  '(20)',
  '(21)',
  '(48)',
  '(62)',
  '(18)',
  '(31)',
  '(27)',
  '(54)',
  '(55)',
  '(34)',
  '(46)',
  '(35)',
  '(44)',
  '(60)',
  '(26)',
  '(57)',
  '(57)',
  '(53)',
  '(58)',
  '(54)',
  '(32)',
  '(22)',
  '(33)',
  '(62)',
  '(52)',
  '(63)',
  '(53)',
  '(19)',
  '(46)',
  '(48)',
  '(60)',
  '(25)',
  '(33)',
  '(55)',
  '(38)',
  '(23)',
  '(54)',
  '(51)',
  '(58)',
  '(32)',
  '(52)',
  '(31)',
  '(28)',
  '(37)',
  '(36)',
  '(33)',
  '(46)',
  '(36)',
  '(63)',
  '(28)',
  '(21)',
  '(46)',
  '(20)',
  '(27)',
  '(65)',
  '(54)',
  '(47)',
  '(53)',
  '(29)',
  '(52)',
  '(23)',
  '(48)',
  '(51)',
  '(62)',
  '(24)',
  '(56)',
  '(58)',
  '(39)',
  '(19)',
  '(30)',
  '(49)',
  '(26)',
  '(52)',
  '(27)',
  '(55)',
  '(22)',
  '(64)',
  '(49)',
  '(63)',
  '(48)',
  '(42)',
  '(56)',
  '(59)',
  '(32)',
  '(59)',
  '(30)',
  '(36)',
  '(61)',
  '(18)',
  '(45)',
  '(38)',
  '(59)',
  '(54)',
  '(49)',
  '(65)',
  '(45)',
  '(31)',
  '(18)',
  '(56)',
  '(24)',
  '(41)',
  '(54)',
  '(28)',
  '(53)',
  '(36)',
  '(22)',
  '(64)',
  '(22)',
  '(52)',
  '(47)',
  '(36)',
  '(52)',
  '(29)',
  '(31)',
  '(44)',
  '(35)',
  '(21)',
  '(63)',
  '(26)',
  '(40)',
  '(53)',
  '(64)',
  '(61)',
  '(29)',
  '(50)',
  '(60)',
  '(48)',
  '(53)',
  '(38)',
  '(57)',
  '(45)',
  '(49)',
  '(55)',
  '(42)',
  '(36)',
  '(36)',
  '(49)',
  '(61)',
  '(22)',
  '(31)',
  '(25)',
  '(21)',
  '(62)',
  '(33)',
  '(51)',
  '(59)',
  '(53)',
  '(33)',
  '(64)',
  '(42)',
  '(21)',
  '(33)',
  '(35)',
  '(58)',
  '(53)',
  '(40)',
  '(63)',
  '(44)',
  '(32)',
  '(19)',
  '(30)',
  '(23)',
  '(43)',
  '(47)',
  '(23)',
  '(65)',
  '(45)',
  '(42)',
  '(40)',
  '(42)',
  '(51)',
  '(38)',
  '(54)',
  '(19)',
  '(65)',
  '(46)',
  '(41)',
  '(32)',
  '(60)',
  '(38)',
  '(22)',
  '(39)',
  '(62)',
  '(48)',
  '(39)',
  '(20)',
  '(51)',
  '(35)',
  '(60)',
  '(27)',
  '(39)',
  '(57)',
  '(49)',
  '(52)',
  '(34)',
  '(42)',
  '(61)',
  '(32)',
  '(21)',
  '(42)',
  '(57)',
  '(38)',
  '(21)',
  '(53)',
  '(60)',
  '(41)',
  '(44)',
  '(51)',
  '(45)',
  '(60)',
  '(39)',
  '(26)',
  '(37)',
  '(44)',
  '(53)',
  '(51)',
  '(41)',
  '(51)',
  '(41)',

In [ ]:
data = {}
for column in users_columns:
    items = []
    column_items = users_df[column].to_list()
    for item in column_items:
        tupple_item = (item,)
        items.append(tupple_item)
    data[column] = items

print(data)

{'user_id': [('U0001',), ('U0002',), ('U0003',), ('U0004',), ('U0005',), ('U0006',), ('U0007',), ('U0008',), ('U0009',), ('U0010',), ('U0011',), ('U0012',), ('U0013',), ('U0014',), ('U0015',), ('U0016',), ('U0017',), ('U0018',), ('U0019',), ('U0020',), ('U0021',), ('U0022',), ('U0023',), ('U0024',), ('U0025',), ('U0026',), ('U0027',), ('U0028',), ('U0029',), ('U0030',), ('U0031',), ('U0032',), ('U0033',), ('U0034',), ('U0035',), ('U0036',), ('U0037',), ('U0038',), ('U0039',), ('U0040',), ('U0041',), ('U0042',), ('U0043',), ('U0044',), ('U0045',), ('U0046',), ('U0047',), ('U0048',), ('U0049',), ('U0050',), ('U0051',), ('U0052',), ('U0053',), ('U0054',), ('U0055',), ('U0056',), ('U0057',), ('U0058',), ('U0059',), ('U0060',), ('U0061',), ('U0062',), ('U0063',), ('U0064',), ('U0065',), ('U0066',), ('U0067',), ('U0068',), ('U0069',), ('U0070',), ('U0071',), ('U0072',), ('U0073',), ('U0074',), ('U0075',), ('U0076',), ('U0077',), ('U0078',), ('U0079',), ('U0080',), ('U0081',), ('U0082',), ('U0083',), ('U0084',), ('U0085',), ('U0086',), ('U0087',), ('U0088',), ('U0089',), ('U0090',), ('U0091',), ('U0092',), ('U0093',), ('U0094',), ('U0095',), ('U0096',), ('U0097',), ('U0098',), ('U0099',), ('U0100',), ('U0101',), ('U0102',), ('U0103',), ('U0104',), ('U0105',), ('U0106',), ('U0107',), ('U0108',), ('U0109',), ('U0110',), ('U0111',), ('U0112',), ('U0113',), ('U0114',), ('U0115',), ('U0116',), ('U0117',), ('U0118',), ('U0119',), ('U0120',), ('U0121',), ('U0122',), ('U0123',), ('U0124',), ('U0125',), ('U0126',), ('U0127',), ('U0128',), ('U0129',), ('U0130',), ('U0131',), ('U0132',), ('U0133',), ('U0134',), ('U0135',), ('U0136',), ('U0137',), ('U0138',), ('U0139',), ('U0140',), ('U0141',), ('U0142',), ('U0143',), ('U0144',), ('U0145',), ('U0146',), ('U0147',), ('U0148',), ('U0149',), ('U0150',), ('U0151',), ('U0152',), ('U0153',), ('U0154',), ('U0155',), ('U0156',), ('U0157',), ('U0158',), ('U0159',), ('U0160',), ('U0161',), ('U0162',), ('U0163',), ('U0164',), ('U0165',), ('U0166',), ('U0167',), ('U0168',), ('U0169',), ('U0170',), ('U0171',), ('U0172',), ('U0173',), ('U0174',), ('U0175',), ('U0176',), ('U0177',), ('U0178',), ('U0179',), ('U0180',), ('U0181',), ('U0182',), ('U0183',), ('U0184',), ('U0185',), ('U0186',), ('U0187',), ('U0188',), ('U0189',), ('U0190',), ('U0191',), ('U0192',), ('U0193',), ('U0194',), ('U0195',), ('U0196',), ('U0197',), ('U0198',), ('U0199',), ('U0200',), ('U0201',), ('U0202',), ('U0203',), ('U0204',), ('U0205',), ('U0206',), ('U0207',), ('U0208',), ('U0209',), ('U0210',), ('U0211',), ('U0212',), ('U0213',), ('U0214',), ('U0215',), ('U0216',), ('U0217',), ('U0218',), ('U0219',), ('U0220',), ('U0221',), ('U0222',), ('U0223',), ('U0224',), ('U0225',), ('U0226',), ('U0227',), ('U0228',), ('U0229',), ('U0230',), ('U0231',), ('U0232',), ('U0233',), ('U0234',), ('U0235',), ('U0236',), ('U0237',), ('U0238',), ('U0239',), ('U0240',), ('U0241',), ('U0242',), ('U0243',), ('U0244',), ('U0245',), ('U0246',), ('U0247',), ('U0248',), ('U0249',), ('U0250',), ('U0251',), ('U0252',), ('U0253',), ('U0254',), ('U0255',), ('U0256',), ('U0257',), ('U0258',), ('U0259',), ('U0260',), ('U0261',), ('U0262',), ('U0263',), ('U0264',), ('U0265',), ('U0266',), ('U0267',), ('U0268',), ('U0269',), ('U0270',), ('U0271',), ('U0272',), ('U0273',), ('U0274',), ('U0275',), ('U0276',), ('U0277',), ('U0278',), ('U0279',), ('U0280',), ('U0281',), ('U0282',), ('U0283',), ('U0284',), ('U0285',), ('U0286',), ('U0287',), ('U0288',), ('U0289',), ('U0290',), ('U0291',), ('U0292',), ('U0293',), ('U0294',), ('U0295',), ('U0296',), ('U0297',), ('U0298',), ('U0299',), ('U0300',), ('U0301',), ('U0302',), ('U0303',), ('U0304',), ('U0305',), ('U0306',), ('U0307',), ('U0308',), ('U0309',), ('U0310',), ('U0311',), ('U0312',), ('U0313',), ('U0314',), ('U0315',), ('U0316',), ('U0317',), ('U0318',), ('U0319',), ('U0320',), ('U0321',), ('U0322',), ('U0323',), ('U0324',), ('U0325',), ('U0326',), ('U0327',), ('U0328',), ('U0329',), ('U0330',), ('U0331',), ('U0332',), ('U0333',), ('U0334',), ('U0335',), ('U0336',), ('U0337',), ('U0338',), ('U0339',), ('U0340',), ('U0341',), ('U0342',), ('U0343',), ('U0344',), ('U0345',), ('U0346',), ('U0347',), ('U0348',), ('U0349',), ('U0350',), ('U0351',), ('U0352',), ('U0353',), ('U0354',), ('U0355',), ('U0356',), ('U0357',), ('U0358',), ('U0359',), ('U0360',), ('U0361',), ('U0362',), ('U0363',), ('U0364',), ('U0365',), ('U0366',), ('U0367',), ('U0368',), ('U0369',), ('U0370',), ('U0371',), ('U0372',), ('U0373',), ('U0374',), ('U0375',), ('U0376',), ('U0377',), ('U0378',), ('U0379',), ('U0380',), ('U0381',), ('U0382',), ('U0383',), ('U0384',), ('U0385',), ('U0386',), ('U0387',), ('U0388',), ('U0389',), ('U0390',), ('U0391',), ('U0392',), ('U0393',), ('U0394',), ('U0395',), ('U0396',), ('U0397',), ('U0398',), ('U0399',), ('U0400',), ('U0401',), ('U0402',), ('U0403',), ('U0404',), ('U0405',), ('U0406',), ('U0407',), ('U0408',), ('U0409',), ('U0410',), ('U0411',), ('U0412',), ('U0413',), ('U0414',), ('U0415',), ('U0416',), ('U0417',), ('U0418',), ('U0419',), ('U0420',), ('U0421',), ('U0422',), ('U0423',), ('U0424',), ('U0425',), ('U0426',), ('U0427',), ('U0428',), ('U0429',), ('U0430',), ('U0431',), ('U0432',), ('U0433',), ('U0434',), ('U0435',), ('U0436',), ('U0437',), ('U0438',), ('U0439',), ('U0440',), ('U0441',), ('U0442',), ('U0443',), ('U0444',), ('U0445',), ('U0446',), ('U0447',), ('U0448',), ('U0449',), ('U0450',), ('U0451',), ('U0452',), ('U0453',), ('U0454',), ('U0455',), ('U0456',), ('U0457',), ('U0458',), ('U0459',), ('U0460',), ('U0461',), ('U0462',), ('U0463',), ('U0464',), ('U0465',), ('U0466',), ('U0467',), ('U0468',), ('U0469',), ('U0470',), ('U0471',), ('U0472',), ('U0473',), ('U0474',), ('U0475',), ('U0476',), ('U0477',), ('U0478',), ('U0479',), ('U0480',), ('U0481',), ('U0482',), ('U0483',), ('U0484',), ('U0485',), ('U0486',), ('U0487',), ('U0488',), ('U0489',), ('U0490',), ('U0491',), ('U0492',), ('U0493',), ('U0494',), ('U0495',), ('U0496',), ('U0497',), ('U0498',), ('U0499',), ('U0500',), ('U0501',), ('U0502',), ('U0503',), ('U0504',), ('U0505',), ('U0506',), ('U0507',), ('U0508',), ('U0509',), ('U0510',), ('U0511',), ('U0512',), ('U0513',), ('U0514',), ('U0515',), ('U0516',), ('U0517',), ('U0518',), ('U0519',), ('U0520',), ('U0521',), ('U0522',), ('U0523',), ('U0524',), ('U0525',), ('U0526',), ('U0527',), ('U0528',), ('U0529',), ('U0530',), ('U0531',), ('U0532',), ('U0533',), ('U0534',), ('U0535',), ('U0536',), ('U0537',), ('U0538',), ('U0539',), ('U0540',), ('U0541',), ('U0542',), ('U0543',), ('U0544',), ('U0545',), ('U0546',), ('U0547',), ('U0548',), ('U0549',), ('U0550',), ('U0551',), ('U0552',), ('U0553',), ('U0554',), ('U0555',), ('U0556',), ('U0557',), ('U0558',), ('U0559',), ('U0560',), ('U0561',), ('U0562',), ('U0563',), ('U0564',), ('U0565',), ('U0566',), ('U0567',), ('U0568',), ('U0569',), ('U0570',), ('U0571',), ('U0572',), ('U0573',), ('U0574',), ('U0575',), ('U0576',), ('U0577',), ('U0578',), ('U0579',), ('U0580',), ('U0581',), ('U0582',), ('U0583',), ('U0584',), ('U0585',), ('U0586',), ('U0587',), ('U0588',), ('U0589',), ('U0590',), ('U0591',), ('U0592',), ('U0593',), ('U0594',), ('U0595',), ('U0596',), ('U0597',), ('U0598',), ('U0599',), ('U0600',), ('U0601',), ('U0602',), ('U0603',), ('U0604',), ('U0605',), ('U0606',), ('U0607',), ('U0608',), ('U0609',), ('U0610',), ('U0611',), ('U0612',), ('U0613',), ('U0614',), ('U0615',), ('U0616',), ('U0617',), ('U0618',), ('U0619',), ('U0620',), ('U0621',), ('U0622',), ('U0623',), ('U0624',), ('U0625',), ('U0626',), ('U0627',), ('U0628',), ('U0629',), ('U0630',), ('U0631',), ('U0632',), ('U0633',), ('U0634',), ('U0635',), ('U0636',), ('U0637',), ('U0638',), ('U0639',), ('U0640',), ('U0641',), ('U0642',), ('U0643',), ('U0644',), ('U0645',), ('U0646',), ('U0647',), ('U0648',), ('U0649',), ('U0650',), ('U0651',), ('U0652',), ('U0653',), ('U0654',), ('U0655',), ('U0656',), ('U0657',), ('U0658',), ('U0659',), ('U0660',), ('U0661',), ('U0662',), ('U0663',), ('U0664',), ('U0665',), ('U0666',), ('U0667',), ('U0668',), ('U0669',), ('U0670',), ('U0671',), ('U0672',), ('U0673',), ('U0674',), ('U0675',), ('U0676',), ('U0677',), ('U0678',), ('U0679',), ('U0680',), ('U0681',), ('U0682',), ('U0683',), ('U0684',), ('U0685',), ('U0686',), ('U0687',), ('U0688',), ('U0689',), ('U0690',), ('U0691',), ('U0692',), ('U0693',), ('U0694',), ('U0695',), ('U0696',), ('U0697',), ('U0698',), ('U0699',), ('U0700',), ('U0701',), ('U0702',), ('U0703',), ('U0704',), ('U0705',), ('U0706',), ('U0707',), ('U0708',), ('U0709',), ('U0710',), ('U0711',), ('U0712',), ('U0713',), ('U0714',), ('U0715',), ('U0716',), ('U0717',), ('U0718',), ('U0719',), ('U0720',), ('U0721',), ('U0722',), ('U0723',), ('U0724',), ('U0725',), ('U0726',), ('U0727',), ('U0728',), ('U0729',), ('U0730',), ('U0731',), ('U0732',), ('U0733',), ('U0734',), ('U0735',), ('U0736',), ('U0737',), ('U0738',), ('U0739',), ('U0740',), ('U0741',), ('U0742',), ('U0743',), ('U0744',), ('U0745',), ('U0746',), ('U0747',), ('U0748',), ('U0749',), ('U0750',), ('U0751',), ('U0752',), ('U0753',), ('U0754',), ('U0755',), ('U0756',), ('U0757',), ('U0758',), ('U0759',), ('U0760',), ('U0761',), ('U0762',), ('U0763',), ('U0764',), ('U0765',), ('U0766',), ('U0767',), ('U0768',), ('U0769',), ('U0770',), ('U0771',), ('U0772',), ('U0773',), ('U0774',), ('U0775',), ('U0776',), ('U0777',), ('U0778',), ('U0779',), ('U0780',), ('U0781',), ('U0782',), ('U0783',), ('U0784',), ('U0785',), ('U0786',), ('U0787',), ('U0788',), ('U0789',), ('U0790',), ('U0791',), ('U0792',), ('U0793',), ('U0794',), ('U0795',), ('U0796',), ('U0797',), ('U0798',), ('U0799',), ('U0800',), ('U0801',), ('U0802',), ('U0803',), ('U0804',), ('U0805',), ('U0806',), ('U0807',), ('U0808',), ('U0809',), ('U0810',), ('U0811',), ('U0812',), ('U0813',), ('U0814',), ('U0815',), ('U0816',), ('U0817',), ('U0818',), ('U0819',), ('U0820',), ('U0821',), ('U0822',), ('U0823',), ('U0824',), ('U0825',), ('U0826',), ('U0827',), ('U0828',), ('U0829',), ('U0830',), ('U0831',), ('U0832',), ('U0833',), ('U0834',), ('U0835',), ('U0836',), ('U0837',), ('U0838',), ('U0839',), ('U0840',), ('U0841',), ('U0842',), ('U0843',), ('U0844',), ('U0845',), ('U0846',), ('U0847',), ('U0848',), ('U0849',), ('U0850',), ('U0851',), ('U0852',), ('U0853',), ('U0854',), ('U0855',), ('U0856',), ('U0857',), ('U0858',), ('U0859',), ('U0860',), ('U0861',), ('U0862',), ('U0863',), ('U0864',), ('U0865',), ('U0866',), ('U0867',), ('U0868',), ('U0869',), ('U0870',), ('U0871',), ('U0872',), ('U0873',), ('U0874',), ('U0875',), ('U0876',), ('U0877',), ('U0878',), ('U0879',), ('U0880',), ('U0881',), ('U0882',), ('U0883',), ('U0884',), ('U0885',), ('U0886',), ('U0887',), ('U0888',), ('U0889',), ('U0890',), ('U0891',), ('U0892',), ('U0893',), ('U0894',), ('U0895',), ('U0896',), ('U0897',), ('U0898',), ('U0899',), ('U0900',), ('U0901',), ('U0902',), ('U0903',), ('U0904',), ('U0905',), ('U0906',), ('U0907',), ('U0908',), ('U0909',), ('U0910',), ('U0911',), ('U0912',), ('U0913',), ('U0914',), ('U0915',), ('U0916',), ('U0917',), ('U0918',), ('U0919',), ('U0920',), ('U0921',), ('U0922',), ('U0923',), ('U0924',), ('U0925',), ('U0926',), ('U0927',), ('U0928',), ('U0929',), ('U0930',), ('U0931',), ('U0932',), ('U0933',), ('U0934',), ('U0935',), ('U0936',), ('U0937',), ('U0938',), ('U0939',), ('U0940',), ('U0941',), ('U0942',), ('U0943',), ('U0944',), ('U0945',), ('U0946',), ('U0947',), ('U0948',), ('U0949',), ('U0950',), ('U0951',), ('U0952',), ('U0953',), ('U0954',), ('U0955',), ('U0956',), ('U0957',), ('U0958',), ('U0959',), ('U0960',), ('U0961',), ('U0962',), ('U0963',), ('U0964',), ('U0965',), ('U0966',), ('U0967',), ('U0968',), ('U0969',), ('U0970',), ('U0971',), ('U0972',), ('U0973',), ('U0974',), ('U0975',), ('U0976',), ('U0977',), ('U0978',), ('U0979',), ('U0980',), ('U0981',), ('U0982',), ('U0983',), ('U0984',), ('U0985',), ('U0986',), ('U0987',), ('U0988',), ('U0989',), ('U0990',), ('U0991',), ('U0992',), ('U0993',), ('U0994',), ('U0995',), ('U0996',), ('U0997',), ('U0998',), ('U0999',), ('U1000',), ('U1001',), ('U1002',), ('U1003',), ('U1004',), ('U1005',), ('U1006',), ('U1007',), ('U1008',), ('U1009',), ('U1010',), ('U1011',), ('U1012',), ('U1013',), ('U1014',), ('U1015',), ('U1016',), ('U1017',), ('U1018',), ('U1019',), ('U1020',), ('U1021',), ('U1022',), ('U1023',), ('U1024',), ('U1025',), ('U1026',), ('U1027',), ('U1028',), ('U1029',), ('U1030',), ('U1031',), ('U1032',), ('U1033',), ('U1034',), ('U1035',), ('U1036',), ('U1037',), ('U1038',), ('U1039',), ('U1040',), ('U1041',), ('U1042',), ('U1043',), ('U1044',), ('U1045',), ('U1046',), ('U1047',), ('U1048',), ('U1049',), ('U1050',), ('U1051',), ('U1052',), ('U1053',), ('U1054',), ('U1055',), ('U1056',), ('U1057',), ('U1058',), ('U1059',), ('U1060',), ('U1061',), ('U1062',), ('U1063',), ('U1064',), ('U1065',), ('U1066',), ('U1067',), ('U1068',), ('U1069',), ('U1070',), ('U1071',), ('U1072',), ('U1073',), ('U1074',), ('U1075',), ('U1076',), ('U1077',), ('U1078',), ('U1079',), ('U1080',), ('U1081',), ('U1082',), ('U1083',), ('U1084',), ('U1085',), ('U1086',), ('U1087',), ('U1088',), ('U1089',), ('U1090',), ('U1091',), ('U1092',), ('U1093',), ('U1094',), ('U1095',), ('U1096',), ('U1097',), ('U1098',), ('U1099',), ('U1100',), ('U1101',), ('U1102',), ('U1103',), ('U1104',), ('U1105',), ('U1106',), ('U1107',), ('U1108',), ('U1109',), ('U1110',), ('U1111',), ('U1112',), ('U1113',), ('U1114',), ('U1115',), ('U1116',), ('U1117',), ('U1118',), ('U1119',), ('U1120',), ('U1121',), ('U1122',), ('U1123',), ('U1124',), ('U1125',), ('U1126',), ('U1127',), ('U1128',), ('U1129',), ('U1130',), ('U1131',), ('U1132',), ('U1133',), ('U1134',), ('U1135',), ('U1136',), ('U1137',), ('U1138',), ('U1139',), ('U1140',), ('U1141',), ('U1142',), ('U1143',), ('U1144',), ('U1145',), ('U1146',), ('U1147',), ('U1148',), ('U1149',), ('U1150',), ('U1151',), ('U1152',), ('U1153',), ('U1154',), ('U1155',), ('U1156',), ('U1157',), ('U1158',), ('U1159',), ('U1160',), ('U1161',), ('U1162',), ('U1163',), ('U1164',), ('U1165',), ('U1166',), ('U1167',), ('U1168',), ('U1169',), ('U1170',), ('U1171',), ('U1172',), ('U1173',), ('U1174',), ('U1175',), ('U1176',), ('U1177',), ('U1178',), ('U1179',), ('U1180',), ('U1181',), ('U1182',), ('U1183',), ('U1184',), ('U1185',), ('U1186',), ('U1187',), ('U1188',), ('U1189',), ('U1190',), ('U1191',), ('U1192',), ('U1193',), ('U1194',), ('U1195',), ('U1196',), ('U1197',), ('U1198',), ('U1199',), ('U1200',), ('U1201',), ('U1202',), ('U1203',), ('U1204',), ('U1205',), ('U1206',), ('U1207',), ('U1208',), ('U1209',), ('U1210',), ('U1211',), ('U1212',), ('U1213',), ('U1214',), ('U1215',), ('U1216',), ('U1217',), ('U1218',), ('U1219',), ('U1220',), ('U1221',), ('U1222',), ('U1223',), ('U1224',), ('U1225',), ('U1226',), ('U1227',), ('U1228',), ('U1229',), ('U1230',), ('U1231',), ('U1232',), ('U1233',), ('U1234',), ('U1235',), ('U1236',), ('U1237',), ('U1238',), ('U1239',), ('U1240',), ('U1241',), ('U1242',), ('U1243',), ('U1244',), ('U1245',), ('U1246',), ('U1247',), ('U1248',), ('U1249',), ('U1250',), ('U1251',), ('U1252',), ('U1253',), ('U1254',), ('U1255',), ('U1256',), ('U1257',), ('U1258',), ('U1259',), ('U1260',), ('U1261',), ('U1262',), ('U1263',), ('U1264',), ('U1265',), ('U1266',), ('U1267',), ('U1268',), ('U1269',), ('U1270',), ('U1271',), ('U1272',), ('U1273',), ('U1274',), ('U1275',), ('U1276',), ('U1277',), ('U1278',), ('U1279',), ('U1280',), ('U1281',), ('U1282',), ('U1283',), ('U1284',), ('U1285',), ('U1286',), ('U1287',), ('U1288',), ('U1289',), ('U1290',), ('U1291',), ('U1292',), ('U1293',), ('U1294',), ('U1295',), ('U1296',), ('U1297',), ('U1298',), ('U1299',), ('U1300',), ('U1301',), ('U1302',), ('U1303',), ('U1304',), ('U1305',), ('U1306',), ('U1307',), ('U1308',), ('U1309',), ('U1310',), ('U1311',), ('U1312',), ('U1313',), ('U1314',), ('U1315',), ('U1316',), ('U1317',), ('U1318',), ('U1319',), ('U1320',), ('U1321',), ('U1322',), ('U1323',), ('U1324',), ('U1325',), ('U1326',), ('U1327',), ('U1328',), ('U1329',), ('U1330',), ('U1331',), ('U1332',), ('U1333',), ('U1334',), ('U1335',), ('U1336',), ('U1337',), ('U1338',), ('U1339',), ('U1340',), ('U1341',), ('U1342',), ('U1343',), ('U1344',), ('U1345',), ('U1346',), ('U1347',), ('U1348',), ('U1349',), ('U1350',), ('U1351',), ('U1352',), ('U1353',), ('U1354',), ('U1355',), ('U1356',), ('U1357',), ('U1358',), ('U1359',), ('U1360',), ('U1361',), ('U1362',), ('U1363',), ('U1364',), ('U1365',), ('U1366',), ('U1367',), ('U1368',), ('U1369',), ('U1370',), ('U1371',), ('U1372',), ('U1373',), ('U1374',), ('U1375',), ('U1376',), ('U1377',), ('U1378',), ('U1379',), ('U1380',), ('U1381',), ('U1382',), ('U1383',), ('U1384',), ('U1385',), ('U1386',), ('U1387',), ('U1388',), ('U1389',), ('U1390',), ('U1391',), ('U1392',), ('U1393',), ('U1394',), ('U1395',), ('U1396',), ('U1397',), ('U1398',), ('U1399',), ('U1400',), ('U1401',), ('U1402',), ('U1403',), ('U1404',), ('U1405',), ('U1406',), ('U1407',), ('U1408',), ('U1409',), ('U1410',), ('U1411',), ('U1412',), ('U1413',), ('U1414',), ('U1415',), ('U1416',), ('U1417',), ('U1418',), ('U1419',), ('U1420',), ('U1421',), ('U1422',), ('U1423',), ('U1424',), ('U1425',), ('U1426',), ('U1427',), ('U1428',), ('U1429',), ('U1430',), ('U1431',), ('U1432',), ('U1433',), ('U1434',), ('U1435',), ('U1436',), ('U1437',), ('U1438',), ('U1439',), ('U1440',), ('U1441',), ('U1442',), ('U1443',), ('U1444',), ('U1445',), ('U1446',), ('U1447',), ('U1448',), ('U1449',), ('U1450',), ('U1451',), ('U1452',), ('U1453',), ('U1454',), ('U1455',), ('U1456',), ('U1457',), ('U1458',), ('U1459',), ('U1460',), ('U1461',), ('U1462',), ('U1463',), ('U1464',), ('U1465',), ('U1466',), ('U1467',), ('U1468',), ('U1469',), ('U1470',), ('U1471',), ('U1472',), ('U1473',), ('U1474',), ('U1475',), ('U1476',), ('U1477',), ('U1478',), ('U1479',), ('U1480',), ('U1481',), ('U1482',), ('U1483',), ('U1484',), ('U1485',), ('U1486',), ('U1487',), ('U1488',), ('U1489',), ('U1490',), ('U1491',), ('U1492',), ('U1493',), ('U1494',), ('U1495',), ('U1496',), ('U1497',), ('U1498',), ('U1499',), ('U1500',), ('U1501',), ('U1502',), ('U1503',), ('U1504',), ('U1505',), ('U1506',), ('U1507',), ('U1508',), ('U1509',), ('U1510',), ('U1511',), ('U1512',), ('U1513',), ('U1514',), ('U1515',), ('U1516',), ('U1517',), ('U1518',), ('U1519',), ('U1520',), ('U1521',), ('U1522',), ('U1523',), ('U1524',), ('U1525',), ('U1526',), ('U1527',), ('U1528',), ('U1529',), ('U1530',), ('U1531',), ('U1532',), ('U1533',), ('U1534',), ('U1535',), ('U1536',), ('U1537',), ('U1538',), ('U1539',), ('U1540',), ('U1541',), ('U1542',), ('U1543',), ('U1544',), ('U1545',), ('U1546',), ('U1547',), ('U1548',), ('U1549',), ('U1550',), ('U1551',), ('U1552',), ('U1553',), ('U1554',), ('U1555',), ('U1556',), ('U1557',), ('U1558',), ('U1559',), ('U1560',), ('U1561',), ('U1562',), ('U1563',), ('U1564',), ('U1565',), ('U1566',), ('U1567',), ('U1568',), ('U1569',), ('U1570',), ('U1571',), ('U1572',), ('U1573',), ('U1574',), ('U1575',), ('U1576',), ('U1577',), ('U1578',), ('U1579',), ('U1580',), ('U1581',), ('U1582',), ('U1583',), ('U1584',), ('U1585',), ('U1586',), ('U1587',), ('U1588',), ('U1589',), ('U1590',), ('U1591',), ('U1592',), ('U1593',), ('U1594',), ('U1595',), ('U1596',), ('U1597',), ('U1598',), ('U1599',), ('U1600',), ('U1601',), ('U1602',), ('U1603',), ('U1604',), ('U1605',), ('U1606',), ('U1607',), ('U1608',), ('U1609',), ('U1610',), ('U1611',), ('U1612',), ('U1613',), ('U1614',), ('U1615',), ('U1616',), ('U1617',), ('U1618',), ('U1619',), ('U1620',), ('U1621',), ('U1622',), ('U1623',), ('U1624',), ('U1625',), ('U1626',), ('U1627',), ('U1628',), ('U1629',), ('U1630',), ('U1631',), ('U1632',), ('U1633',), ('U1634',), ('U1635',), ('U1636',), ('U1637',), ('U1638',), ('U1639',), ('U1640',), ('U1641',), ('U1642',), ('U1643',), ('U1644',), ('U1645',), ('U1646',), ('U1647',), ('U1648',), ('U1649',), ('U1650',), ('U1651',), ('U1652',), ('U1653',), ('U1654',), ('U1655',), ('U1656',), ('U1657',), ('U1658',), ('U1659',), ('U1660',), ('U1661',), ('U1662',), ('U1663',), ('U1664',), ('U1665',), ('U1666

In [ ]:
payload = {
    'table': 'users',
    'data': data
}

In [ ]:
viewing_df = pd.read_csv('./data/viewing_sessions.csv')
viewing_df

,session_id,user_id,content_id,watch_date,watch_duration_minutes,completion_percentage,device_type,quality_level
0,S000001,U0001,S001,2024-02-16,9,18.8,Desktop,4K
1,S000002,U0001,M110,2024-08-06,30,23.6,Smart TV,SD
2,S000003,U0001,S005,2024-03-20,18,65.3,Desktop,4K
3,S000004,U0001,M105,2024-02-24,77,74.4,Mobile,HD
4,S000005,U0001,M148,2024-08-18,47,30.1,Smart TV,4K
...,...,...,...,...,...,...,...,...
222780,S222781,U5000,M190,2024-01-15,109,92.7,Smart TV,HD
222781,S222782,U5000,M044,2024-07-14,119,88.9,Smart TV,SD
222782,S222783,U5000,S098,2024-05-08,55,96.9,Smart TV,4K
222783,S222784,U5000,M028,2024-07-25,145,83.2,Mobile,HD
222784,S222785,U5000,M083,2024-04-26,94,81.5,Tablet,4K

In [ ]:
viewing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 222785 entries, 0 to 222784
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   session_id              222785 non-null  object
 1   user_id                 222785 non-null  object
 2   content_id              222785 non-null  object
 3   watch_date              222785 non-null  object
 4   watch_duration_minutes  222785 non-null  int64
 5   completion_percentage   222785 non-null  float64
 6   device_type             222785 non-null  object
 7   quality_level           222785 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 13.6+ MB

In [ ]:
viewing_columns = viewing_df.columns

# NEW APPROACH - CSV

## Version A

In [70]:
import csv, json

In [76]:
# Variables

file_path = "../data/users.csv"
table = "users"

In [69]:
with open(file_path, newline='', encoding='utf-8', mode='r') as file:
    csv_file = csv.DictReader(file)
    for row in csv_file:
        print(row)

{'user_id': 'U0001', 'age': '21', 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-10-02', 'total_watch_time_hours': '58.0'}
{'user_id': 'U0002', 'age': '44', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-09-30', 'total_watch_time_hours': '75.3'}
{'user_id': 'U0003', 'age': '20', 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-01-24', 'total_watch_time_hours': '360.0'}
{'user_id': 'U0004', 'age': '39', 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2022-12-15', 'total_watch_time_hours': '513.0'}
{'user_id': 'U0005', 'age': '28', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-05-19', 'total_watch_time_hours': '192.8'}
{'user_id': 'U0006', 'age': '39', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-12-20', 'total_watch_time_hours': '156.2'}
{'user_id': 'U0007', 'age': '18', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-03-23', 'total_watch_time_hours': '428.0'}
{'user_id': 'U0008', 'age': '56', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-01-22', 'total_watch_time_hours': '47.8'}
{'user_id': 'U0009', 'age': '38', 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2024-01-20', 'total_watch_time_hours': '229.7'}
{'user_id': 'U0010', 'age': '20', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-04-05', 'total_watch_time_hours': '444.7'}
{'user_id': 'U0011', 'age': '26', 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-01-22', 'total_watch_time_hours': '336.6'}
{'user_id': 'U0012', 'age': '45', 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-08-11', 'total_watch_time_hours': '292.4'}
{'user_id': 'U0013', 'age': '48', 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-02-07', 'total_watch_time_hours': '386.7'}
{'user_id': 'U0014', 'age': '39', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-06-19', 'total_watch_time_hours': '402.7'}
{'user_id': 'U0015', 'age': '31', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-09-16', 'total_watch_time_hours': '387.6'}
{'user_id': 'U0016', 'age': '54', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-11-19', 'total_watch_time_hours': '17.4'}
{'user_id': 'U0017', 'age': '59', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-06-10', 'total_watch_time_hours': '240.7'}
{'user_id': 'U0018', 'age': '52', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-10-16', 'total_watch_time_hours': '360.2'}
{'user_id': 'U0019', 'age': '56', 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2023-05-13', 'total_watch_time_hours': '477.2'}
{'user_id': 'U0020', 'age': '44', 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2023-01-19', 'total_watch_time_hours': '311.9'}
{'user_id': 'U0021', 'age': '59', 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-07-05', 'total_watch_time_hours': '329.1'}
{'user_id': 'U0022', 'age': '23', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-05-14', 'total_watch_time_hours': '438.8'}
{'user_id': 'U0023', 'age': '28', 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2022-12-09', 'total_watch_time_hours': '192.6'}
{'user_id': 'U0024', 'age': '43', 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-03-17', 'total_watch_time_hours': '728.7'}
{'user_id': 'U0025', 'age': '42', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-08-10', 'total_watch_time_hours': '469.9'}
{'user_id': 'U0026', 'age': '19', 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2022-07-13', 'total_watch_time_hours': '653.9'}
{'user_id': 'U0027', 'age': '58', 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-01-08', 'total_watch_time_hours': '17.6'}
{'user_id': 'U0028', 'age': '40', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-08-23', 'total_watch_time_hours': '208.8'}
{'user_id': 'U0029', 'age': '50', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2024-01-12', 'total_watch_time_hours': '496.6'}
{'user_id': 'U0030', 'age': '21', 'country': 'Chile', 'subscription_type': 'Standard', 'registration_date': '2023-10-17', 'total_watch_time_hours': '199.3'}
{'user_id': 'U0031', 'age': '49', 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2024-02-22', 'total_watch_time_hours': '382.4'}
{'user_id': 'U0032', 'age': '32', 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-07-12', 'total_watch_time_hours': '296.5'}
{'user_id': 'U0033', 'age': '29', 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2022-06-07', 'total_watch_time_hours': '545.7'}
{'user_id': 'U0034', 'age': '46', 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2023-01-23', 'total_watch_time_hours': '378.3'}
{'user_id': 'U0035', 'age': '20', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-01-11', 'total_watch_time_hours': '100.3'}
{'user_id': 'U0036', 'age': '30', 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2022-01-22', 'total_watch_time_hours': '271.2'}
{'user_id': 'U0037', 'age': '40', 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-12-03', 'total_watch_time_hours': '171.9'}
{'user_id': 'U0038', 'age': '45', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-10-12', 'total_watch_time_hours': '259.2'}
{'user_id': 'U0039', 'age': '24', 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-09-25', 'total_watch_time_hours': '44.7'}
{'user_id': 'U0040', 'age': '40', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-12-26', 'total_watch_time_hours': '64.2'}
{'user_id': 'U0041', 'age': '45', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-01-09', 'total_watch_time_hours': '479.9'}
{'user_id': 'U0042', 'age': '42', 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-03-17', 'total_watch_time_hours': '277.8'}
{'user_id': 'U0043', 'age': '58', 'country': 'Peru', 'subscription_type': 'Premium', 'registration_date': '2023-02-18', 'total_watch_time_hours': '43.7'}
{'user_id': 'U0044', 'age': '38', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-09-26', 'total_watch_time_hours': '478.3'}
{'user_id': 'U0045', 'age': '20', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2024-02-08', 'total_watch_time_hours': '313.7'}
{'user_id': 'U0046', 'age': '44', 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-12-23', 'total_watch_time_hours': '43.3'}
{'user_id': 'U0047', 'age': '58', 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-06-17', 'total_watch_time_hours': '797.6'}
{'user_id': 'U0048', 'age': '44', 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2022-03-07', 'total_watch_time_hours': '434.0'}
{'user_id': 'U0049', 'age': '61', 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2022-05-28', 'total_watch_time_hours': '173.1'}
{'user_id': 'U0050', 'age': '33', 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2024-02-01', 'total_watch_time_hours': '48.4'}
{'user_id': 'U0051', 'age': '58', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-02-28', 'total_watch_time_hours': '412.0'}
{'user_id': 'U0052', 'age': '42', 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2023-07-05', 'total_watch_time_hours': '160.0'}
{'user_id': 'U0053', 'age': '59', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2024-03-01', 'total_watch_time_hours': '495.5'}
{'user_id': 'U0054', 'age': '42', 'country': 'Chile', 'subscription_type': 'Standard', 'registration_date': '2023-01-13', 'total_watch_time_hours': '86.4'}
{'user_id': 'U0055', 'age': '39', 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2023-06-14', 'total_watch_time_hours': '68.6'}
{'user_id': 'U0056', 'age': '28', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-08-27', 'total_watch_time_hours': '219.2'}
{'user_id': 'U0057', 'age': '21', 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2024-01-30', 'total_watch_time_hours': '168.6'}
{'user_id': 'U0058', 'age': '60', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-01-22', 'total_watch_time_hours': '195.8'}
{'user_id': 'U0059', 'age': '65', 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2024-01-28', 'total_watch_time_hours': '391.9'}
{'user_id': 'U0060', 'age': '63', 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2023-11-16', 'total_watch_time_hours': '415.9'}
{'user_id': 'U0061', 'age': '45', 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2022-01-29', 'total_watch_time_hours': '87.7'}
{'user_id': 'U0062', 'age': '38', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-06-14', 'total_watch_time_hours': '314.7'}
{'user_id': 'U0063', 'age': '26', 'country': 'Peru', 'subscription_type': 'Premium', 'registration_date': '2022-12-18', 'total_watch_time_hours': '561.1'}
{'user_id': 'U0064', 'age': '52', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2024-01-14', 'total_watch_time_hours': '206.1'}
{'user_id': 'U0065', 'age': '54', 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2022-12-15', 'total_watch_time_hours': '49.9'}
{'user_id': 'U0066', 'age': '50', 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-09-07', 'total_watch_time_hours': '109.6'}
{'user_id': 'U0067', 'age': '38', 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-09-28', 'total_watch_time_hours': '410.2'}
{'user_id': 'U0068', 'age': '50', 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2022-03-24', 'total_watch_time_hours': '478.5'}
{'user_id': 'U0069', 'age': '50', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-07-24', 'total_watch_time_hours': '381.5'}
{'user_id': 'U0070', 'age': '19', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-07-18', 'total_watch_time_hours': '186.7'}
{'user_id': 'U0071', 'age': '32', 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2022-03-29', 'total_watch_time_hours': '304.0'}
{'user_id': 'U0072', 'age': '23', 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2022-12-16', 'total_watch_time_hours': '371.9'}
{'user_id': 'U0073', 'age': '26', 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2023-07-02', 'total_watch_time_hours': '168.0'}
{'user_id': 'U0074', 'age': '48', 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-05-20', 'total_watch_time_hours': '368.0'}
{'user_id': 'U0075', 'age': '19', 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-09-21', 'total_watch_time_hours': '791.4'}
{'user_id': 'U0076', 'age': '54', 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2023-05-13', 'total_watch_time_hours': '318.3'}
{'user_id': 'U0077', 'age': '32', 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2023-05-29', 'total_watch_time_hours': '463.2'}
{'user_id': 'U0078', 'age': '57', 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-10-13', 'total_watch_time_hours': '11.6'}
{'user_id': 'U0079', 'age': '56', 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2023-09-16', 'total_watch_time_hours': '873.8'}
{'user_id': 'U0080', 'age': '39', 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-12-14', 'total_watch_time_hours': '355.8'}
{'user_id': 'U0081', 'age': '62', 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-02-23', 'total_watch_time_hours': '336.1'}
{'user_id': 'U0082', 'age': '47', 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-01-06', 'total_watch_time_hours': '479.3'}
{'user_id': 'U0083', 'age': '44', 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-11-20', 'total_watch_time_hours': '371.5'}
{'user_id': 'U0084', 'age': '46', 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-12-18', 'total_watch_time_hours': '815.2'}
{'user_id': 'U0085', 'age': '30', 'country': 'Chile', 'subscription_type': 'Standard', 'registration_date': '2022-07-05', 'total_watch_time_hours': '236.8'}
{'user_id': 'U0086', 'age': '21', 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2023-03-01', 'total_watch_time_hours': '213.3'}
{'user_id': 'U0087', 'age': '34', 'country': 'Chile', 'subscription_type': 'Premium', 'registration_date': '2022-06-29', 'total_watch_time_hours': '859.2'}
{'user_id': 'U0088', 'age': '42', 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2023-01-13', 'total_watch_time_hours': '43.9'}
{'user_id': 'U0089', 'age': '36', 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2022-05-06', 'total_watch_time_hours': '455.0'}
{'user_id': 'U0090', 'age': '50', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-09-12', 'total_watch_time_hours': '201.5'}
{'user_id': 'U0091', 'age': '42', 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-02-22', 'total_watch_time_hours': '297.1'}
{'user_id': 'U0092', 'age': '37', 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2022-04-21', 'total_watch_time_hours': '476.2'}
{'user_id': 'U0093', 'age': '63', 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-11-29', 'total_watch_time_hours': '232.0'}
{'user_id': 'U0094', 'age': '46', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-09-30', 'total_watch_time_hours': '506.4'}
{'user_id': 'U0095', 'age': '54', 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2023-08-09', 'total_watch_time_hours': '192.9'}
{'user_id': 'U0096', 'age': '62', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-04-12', 'total_watch_time_hours': '275.9'}
{'user_id': 'U0097', 'age': '35', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-12-12', 'total_watch_time_hours': '573.5'}
{'user_id': 'U0098', 'age': '29', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-05-07', 'total_watch_time_hours': '26.1'}
{'user_id': 'U0099', 'age': '60', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-05-24', 'total_watch_time_hours': '399.1'}
{'user_id': 'U0100', 'age': '48', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-07-02', 'total_watch_time_hours': '31.0'}
{'user_id': 'U0101', 'age': '52', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-05-25', 'total_watch_time_hours': '152.7'}
{'user_id': 'U0102', 'age': '41', 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-08-15', 'total_watch_time_hours': '605.7'}
{'user_id': 'U0103', 'age': '20', 'country': 'Chile', 'subscription_type': 'Standard', 'registration_date': '2023-04-20', 'total_watch_time_hours': '339.3'}
{'user_id': 'U0104', 'age': '56', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-10-23', 'total_watch_time_hours': '384.3'}
{'user_id': 'U0105', 'age': '18', 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-11-25', 'total_watch_time_hours': '404.4'}
{'user_id': 'U0106', 'age': '32', 'country': 'Chile', 'subscription_type': 'Standard', 'registration_date': '2023-12-06', 'total_watch_time_hours': '534.0'}
{'user_id': 'U0107', 'age': '34', 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-10-19', 'total_watch_time_hours': '184.7'}
{'user_id': 'U0108', 'age': '44', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-01-02', 'total_watch_time_hours': '261.9'}
{'user_id': 'U0109', 'age': '56', 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2022-01-14', 'total_watch_time_hours': '228.1'}
{'user_id': 'U0110', 'age': '28', 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2022-07-22', 'total_watch_time_hours': '36.1'}
{'user_id': 'U0111', 'age': '51', 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-06-19', 'total_watch_time_hours': '691.7'}
{'user_id': 'U0112', 'age': '51', 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2022-07-18', 'total_watch_time_hours': '285.0'}
{'user_id': 'U0113', 'age': '47', 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2022-08-18', 'total_watch_time_hours': '148.4'}
{'user_id': 'U0114', 'age': '23', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-04-16', 'total_watch_time_hours': '299.5'}
{'user_id': 'U0115', 'age': '52', 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-07-25', 'total_watch_time_hours': '132.2'}
{'user_id': 'U0116', 'age': '30', 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2023-06-18', 'total_watch_time_hours': '471.0'}
{'user_id': 'U0117', 'age': '22', 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2023-10-13', 'total_watch_time_hours': '1034.7'}
{'user_id': 'U0118', 'age': '44', 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2023-04-05', 'total_watch_time_hours': '64.4'}
{'user_id': 'U0119', 'age': '54', 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2023-03-20', 'total_watch_time_hours': '689.8'}
{'user_id': 'U0120', 'age': '45', 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-06-14', 'total_watch_time_hours': '221.6'}
{'user_id': 'U0121', 'age': '49', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-05-18', 'total_watch_time_hours': '126.3'}
{'user_id': 'U0122', 'age': '31', 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2022-09-05', 'total_watch_time_hours': '486.5'}
{'user_id': 'U0123', 'age': '33', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-08-02', 'total_watch_time_hours': '55.2'}
{'user_id': 'U0124', 'age': '19', 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2022-01-12', 'total_watch_time_hours': '233.2'}
{'user_id': 'U0125', 'age': '38', 'country': 'Chile', 'subscription_type': 'Premium', 'registration_date': '2023-07-15', 'total_watch_time_hours': '49.4'}
{'user_id': 'U0126', 'age': '33', 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2024-01-19', 'total_watch_time_hours': '533.4'}

In [72]:
def transform_types(dictionary: dict, list_1: list, list_2: list):
    for llave in list_1:
        if llave in dictionary.keys():
            value_type = list_2.pop(0)
            dictionary[llave] = value_type(dictionary[llave])
        else:
            raise Exception("The dictionary does not meet the required keys")
    return dictionary

In [78]:
def leer():
    with open(file_path, newline='', mode='r') as file:
        csv_file = csv.DictReader(file)
        for row in csv_file:
            yield row

def comprobar(dictionary: dict):
    if table == "users":
        columns = ['user_id', 'age', 'country', 'subscription_type', 'registration_date', 'total_watch_time_hours']
        data_types = [str, int, str, str, str, float]
        processed_dict = transform_types(dictionary, columns, data_types)
        return processed_dict
    else:
        columns = ['session_id','user_id', 'content_id', 'watch_date', 'watch_duration_minutes', 'completion_percentage', 'device_type', 'quality_level']
        data_types = [str, str, str, str, int, float, str, str]
        processed_dict = transform_types(dictionary, columns, data_types)
        return processed_dict

def preparar(dictionary: dict):
    new_dict = comprobar(dictionary)
    payload_body = {
        'table': table,
        'data': new_dict
    }
    return payload_body


def enviar(dictionary: dict):
    dictionary = preparar(dictionary)
    response = print(f"Se envió correctamente {dictionary}")
    return response

if __name__ == '__main__':
    for dictionary in leer():
        enviar(dictionary)

Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0001', 'age': 21, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-10-02', 'total_watch_time_hours': 58.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0002', 'age': 44, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-09-30', 'total_watch_time_hours': 75.3}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0003', 'age': 20, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-01-24', 'total_watch_time_hours': 360.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0004', 'age': 39, 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2022-12-15', 'total_watch_time_hours': 513.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0005', 'age': 28, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-05-19', 'total_watch_time_hours': 192.8}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0006', 'age': 39, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-12-20', 'total_watch_time_hours': 156.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0007', 'age': 18, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-03-23', 'total_watch_time_hours': 428.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0008', 'age': 56, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-01-22', 'total_watch_time_hours': 47.8}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0009', 'age': 38, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2024-01-20', 'total_watch_time_hours': 229.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0010', 'age': 20, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-04-05', 'total_watch_time_hours': 444.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0011', 'age': 26, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-01-22', 'total_watch_time_hours': 336.6}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0012', 'age': 45, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-08-11', 'total_watch_time_hours': 292.4}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0013', 'age': 48, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-02-07', 'total_watch_time_hours': 386.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0014', 'age': 39, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-06-19', 'total_watch_time_hours': 402.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0015', 'age': 31, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-09-16', 'total_watch_time_hours': 387.6}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0016', 'age': 54, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-11-19', 'total_watch_time_hours': 17.4}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0017', 'age': 59, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-06-10', 'total_watch_time_hours': 240.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0018', 'age': 52, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-10-16', 'total_watch_time_hours': 360.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0019', 'age': 56, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2023-05-13', 'total_watch_time_hours': 477.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0020', 'age': 44, 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2023-01-19', 'total_watch_time_hours': 311.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0021', 'age': 59, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-07-05', 'total_watch_time_hours': 329.1}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0022', 'age': 23, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-05-14', 'total_watch_time_hours': 438.8}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0023', 'age': 28, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2022-12-09', 'total_watch_time_hours': 192.6}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0024', 'age': 43, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-03-17', 'total_watch_time_hours': 728.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0025', 'age': 42, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-08-10', 'total_watch_time_hours': 469.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0026', 'age': 19, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2022-07-13', 'total_watch_time_hours': 653.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0027', 'age': 58, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-01-08', 'total_watch_time_hours': 17.6}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0028', 'age': 40, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-08-23', 'total_watch_time_hours': 208.8}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0029', 'age': 50, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2024-01-12', 'total_watch_time_hours': 496.6}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0030', 'age': 21, 'country': 'Chile', 'subscription_type': 'Standard', 'registration_date': '2023-10-17', 'total_watch_time_hours': 199.3}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0031', 'age': 49, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2024-02-22', 'total_watch_time_hours': 382.4}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0032', 'age': 32, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-07-12', 'total_watch_time_hours': 296.5}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0033', 'age': 29, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2022-06-07', 'total_watch_time_hours': 545.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0034', 'age': 46, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2023-01-23', 'total_watch_time_hours': 378.3}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0035', 'age': 20, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-01-11', 'total_watch_time_hours': 100.3}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0036', 'age': 30, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2022-01-22', 'total_watch_time_hours': 271.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0037', 'age': 40, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-12-03', 'total_watch_time_hours': 171.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0038', 'age': 45, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-10-12', 'total_watch_time_hours': 259.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0039', 'age': 24, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-09-25', 'total_watch_time_hours': 44.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0040', 'age': 40, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-12-26', 'total_watch_time_hours': 64.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0041', 'age': 45, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-01-09', 'total_watch_time_hours': 479.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0042', 'age': 42, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-03-17', 'total_watch_time_hours': 277.8}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0043', 'age': 58, 'country': 'Peru', 'subscription_type': 'Premium', 'registration_date': '2023-02-18', 'total_watch_time_hours': 43.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0044', 'age': 38, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-09-26', 'total_watch_time_hours': 478.3}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0045', 'age': 20, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2024-02-08', 'total_watch_time_hours': 313.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0046', 'age': 44, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-12-23', 'total_watch_time_hours': 43.3}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0047', 'age': 58, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-06-17', 'total_watch_time_hours': 797.6}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0048', 'age': 44, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2022-03-07', 'total_watch_time_hours': 434.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0049', 'age': 61, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2022-05-28', 'total_watch_time_hours': 173.1}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0050', 'age': 33, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2024-02-01', 'total_watch_time_hours': 48.4}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0051', 'age': 58, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-02-28', 'total_watch_time_hours': 412.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0052', 'age': 42, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2023-07-05', 'total_watch_time_hours': 160.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0053', 'age': 59, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2024-03-01', 'total_watch_time_hours': 495.5}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0054', 'age': 42, 'country': 'Chile', 'subscription_type': 'Standard', 'registration_date': '2023-01-13', 'total_watch_time_hours': 86.4}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0055', 'age': 39, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2023-06-14', 'total_watch_time_hours': 68.6}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0056', 'age': 28, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-08-27', 'total_watch_time_hours': 219.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0057', 'age': 21, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2024-01-30', 'total_watch_time_hours': 168.6}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0058', 'age': 60, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-01-22', 'total_watch_time_hours': 195.8}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0059', 'age': 65, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2024-01-28', 'total_watch_time_hours': 391.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0060', 'age': 63, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2023-11-16', 'total_watch_time_hours': 415.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0061', 'age': 45, 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2022-01-29', 'total_watch_time_hours': 87.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0062', 'age': 38, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-06-14', 'total_watch_time_hours': 314.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0063', 'age': 26, 'country': 'Peru', 'subscription_type': 'Premium', 'registration_date': '2022-12-18', 'total_watch_time_hours': 561.1}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0064', 'age': 52, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2024-01-14', 'total_watch_time_hours': 206.1}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0065', 'age': 54, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2022-12-15', 'total_watch_time_hours': 49.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0066', 'age': 50, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-09-07', 'total_watch_time_hours': 109.6}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0067', 'age': 38, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-09-28', 'total_watch_time_hours': 410.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0068', 'age': 50, 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2022-03-24', 'total_watch_time_hours': 478.5}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0069', 'age': 50, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-07-24', 'total_watch_time_hours': 381.5}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0070', 'age': 19, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-07-18', 'total_watch_time_hours': 186.7}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0071', 'age': 32, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2022-03-29', 'total_watch_time_hours': 304.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0072', 'age': 23, 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2022-12-16', 'total_watch_time_hours': 371.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0073', 'age': 26, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2023-07-02', 'total_watch_time_hours': 168.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0074', 'age': 48, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-05-20', 'total_watch_time_hours': 368.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0075', 'age': 19, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-09-21', 'total_watch_time_hours': 791.4}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0076', 'age': 54, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2023-05-13', 'total_watch_time_hours': 318.3}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0077', 'age': 32, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2023-05-29', 'total_watch_time_hours': 463.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0078', 'age': 57, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-10-13', 'total_watch_time_hours': 11.6}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0079', 'age': 56, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2023-09-16', 'total_watch_time_hours': 873.8}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0080', 'age': 39, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-12-14', 'total_watch_time_hours': 355.8}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0081', 'age': 62, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-02-23', 'total_watch_time_hours': 336.1}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0082', 'age': 47, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-01-06', 'total_watch_time_hours': 479.3}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0083', 'age': 44, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-11-20', 'total_watch_time_hours': 371.5}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0084', 'age': 46, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-12-18', 'total_watch_time_hours': 815.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0085', 'age': 30, 'country': 'Chile', 'subscription_type': 'Standard', 'registration_date': '2022-07-05', 'total_watch_time_hours': 236.8}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0086', 'age': 21, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2023-03-01', 'total_watch_time_hours': 213.3}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0087', 'age': 34, 'country': 'Chile', 'subscription_type': 'Premium', 'registration_date': '2022-06-29', 'total_watch_time_hours': 859.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0088', 'age': 42, 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2023-01-13', 'total_watch_time_hours': 43.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0089', 'age': 36, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2022-05-06', 'total_watch_time_hours': 455.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0090', 'age': 50, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-09-12', 'total_watch_time_hours': 201.5}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0091', 'age': 42, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-02-22', 'total_watch_time_hours': 297.1}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0092', 'age': 37, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2022-04-21', 'total_watch_time_hours': 476.2}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0093', 'age': 63, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-11-29', 'total_watch_time_hours': 232.0}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0094', 'age': 46, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-09-30', 'total_watch_time_hours': 506.4}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0095', 'age': 54, 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2023-08-09', 'total_watch_time_hours': 192.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0096', 'age': 62, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-04-12', 'total_watch_time_hours': 275.9}}
Se envió correctamente {'table': 'users', 'data': {'user_id': 'U0097', 'age': 35, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-12-12', 'total_watch_time_hours': 573.5}}

## Version B

In [19]:
import pandas as pd, json

In [32]:
# Variables

file_path = "../data/users.csv"
table = "users"

In [33]:
df_csv = pd.read_csv(file_path)
df = df_csv.to_json(orient="records")
df = json.loads(df)
df

[{'user_id': 'U0001',
  'age': 21,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-10-02',
  'total_watch_time_hours': 58.0},
 {'user_id': 'U0002',
  'age': 44,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-09-30',
  'total_watch_time_hours': 75.3},
 {'user_id': 'U0003',
  'age': 20,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-24',
  'total_watch_time_hours': 360.0},
 {'user_id': 'U0004',
  'age': 39,
  'country': 'Peru',
  'subscription_type': 'Standard',
  'registration_date': '2022-12-15',
  'total_watch_time_hours': 513.0},
 {'user_id': 'U0005',
  'age': 28,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2022-05-19',
  'total_watch_time_hours': 192.8},
 {'user_id': 'U0006',
  'age': 39,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-12-20',
  'total_watch_time_hours': 156.2},
 {'user_id': 'U0007',
  'age': 18,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-03-23',
  'total_watch_time_hours': 428.0},
 {'user_id': 'U0008',
  'age': 56,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-22',
  'total_watch_time_hours': 47.8},
 {'user_id': 'U0009',
  'age': 38,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2024-01-20',
  'total_watch_time_hours': 229.7},
 {'user_id': 'U0010',
  'age': 20,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-04-05',
  'total_watch_time_hours': 444.7},
 {'user_id': 'U0011',
  'age': 26,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-01-22',
  'total_watch_time_hours': 336.6},
 {'user_id': 'U0012',
  'age': 45,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-08-11',
  'total_watch_time_hours': 292.4},
 {'user_id': 'U0013',
  'age': 48,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-02-07',
  'total_watch_time_hours': 386.7},
 {'user_id': 'U0014',
  'age': 39,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-06-19',
  'total_watch_time_hours': 402.7},
 {'user_id': 'U0015',
  'age': 31,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-09-16',
  'total_watch_time_hours': 387.6},
 {'user_id': 'U0016',
  'age': 54,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-11-19',
  'total_watch_time_hours': 17.4},
 {'user_id': 'U0017',
  'age': 59,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-06-10',
  'total_watch_time_hours': 240.7},
 {'user_id': 'U0018',
  'age': 52,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-10-16',
  'total_watch_time_hours': 360.2},
 {'user_id': 'U0019',
  'age': 56,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2023-05-13',
  'total_watch_time_hours': 477.2},
 {'user_id': 'U0020',
  'age': 44,
  'country': 'Peru',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-19',
  'total_watch_time_hours': 311.9},
 {'user_id': 'U0021',
  'age': 59,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-07-05',
  'total_watch_time_hours': 329.1},
 {'user_id': 'U0022',
  'age': 23,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-05-14',
  'total_watch_time_hours': 438.8},
 {'user_id': 'U0023',
  'age': 28,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2022-12-09',
  'total_watch_time_hours': 192.6},
 {'user_id': 'U0024',
  'age': 43,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-03-17',
  'total_watch_time_hours': 728.7},
 {'user_id': 'U0025',
  'age': 42,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-08-10',
  'total_watch_time_hours': 469.9},
 {'user_id': 'U0026',
  'age': 19,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2022-07-13',
  'total_watch_time_hours': 653.9},
 {'user_id': 'U0027',
  'age': 58,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-08',
  'total_watch_time_hours': 17.6},
 {'user_id': 'U0028',
  'age': 40,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2022-08-23',
  'total_watch_time_hours': 208.8},
 {'user_id': 'U0029',
  'age': 50,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2024-01-12',
  'total_watch_time_hours': 496.6},
 {'user_id': 'U0030',
  'age': 21,
  'country': 'Chile',
  'subscription_type': 'Standard',
  'registration_date': '2023-10-17',
  'total_watch_time_hours': 199.3},
 {'user_id': 'U0031',
  'age': 49,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2024-02-22',
  'total_watch_time_hours': 382.4},
 {'user_id': 'U0032',
  'age': 32,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-07-12',
  'total_watch_time_hours': 296.5},
 {'user_id': 'U0033',
  'age': 29,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2022-06-07',
  'total_watch_time_hours': 545.7},
 {'user_id': 'U0034',
  'age': 46,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2023-01-23',
  'total_watch_time_hours': 378.3},
 {'user_id': 'U0035',
  'age': 20,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-01-11',
  'total_watch_time_hours': 100.3},
 {'user_id': 'U0036',
  'age': 30,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2022-01-22',
  'total_watch_time_hours': 271.2},
 {'user_id': 'U0037',
  'age': 40,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-12-03',
  'total_watch_time_hours': 171.9},
 {'user_id': 'U0038',
  'age': 45,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-10-12',
  'total_watch_time_hours': 259.2},
 {'user_id': 'U0039',
  'age': 24,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2023-09-25',
  'total_watch_time_hours': 44.7},
 {'user_id': 'U0040',
  'age': 40,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-12-26',
  'total_watch_time_hours': 64.2},
 {'user_id': 'U0041',
  'age': 45,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-01-09',
  'total_watch_time_hours': 479.9},
 {'user_id': 'U0042',
  'age': 42,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-03-17',
  'total_watch_time_hours': 277.8},
 {'user_id': 'U0043',
  'age': 58,
  'country': 'Peru',
  'subscription_type': 'Premium',
  'registration_date': '2023-02-18',
  'total_watch_time_hours': 43.7},
 {'user_id': 'U0044',
  'age': 38,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2022-09-26',
  'total_watch_time_hours': 478.3},
 {'user_id': 'U0045',
  'age': 20,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2024-02-08',
  'total_watch_time_hours': 313.7},
 {'user_id': 'U0046',
  'age': 44,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-12-23',
  'total_watch_time_hours': 43.3},
 {'user_id': 'U0047',
  'age': 58,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-06-17',
  'total_watch_time_hours': 797.6},
 {'user_id': 'U0048',
  'age': 44,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2022-03-07',
  'total_watch_time_hours': 434.0},
 {'user_id': 'U0049',
  'age': 61,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2022-05-28',
  'total_watch_time_hours': 173.1},
 {'user_id': 'U0050',
  'age': 33,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2024-02-01',
  'total_watch_time_hours': 48.4},
 {'user_id': 'U0051',
  'age': 58,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-02-28',
  'total_watch_time_hours': 412.0},
 {'user_id': 'U0052',
  'age': 42,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2023-07-05',
  'total_watch_time_hours': 160.0},
 {'user_id': 'U0053',
  'age': 59,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2024-03-01',
  'total_watch_time_hours': 495.5},
 {'user_id': 'U0054',
  'age': 42,
  'country': 'Chile',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-13',
  'total_watch_time_hours': 86.4},
 {'user_id': 'U0055',
  'age': 39,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2023-06-14',
  'total_watch_time_hours': 68.6},
 {'user_id': 'U0056',
  'age': 28,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-08-27',
  'total_watch_time_hours': 219.2},
 {'user_id': 'U0057',
  'age': 21,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2024-01-30',
  'total_watch_time_hours': 168.6},
 {'user_id': 'U0058',
  'age': 60,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-01-22',
  'total_watch_time_hours': 195.8},
 {'user_id': 'U0059',
  'age': 65,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2024-01-28',
  'total_watch_time_hours': 391.9},
 {'user_id': 'U0060',
  'age': 63,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2023-11-16',
  'total_watch_time_hours': 415.9},
 {'user_id': 'U0061',
  'age': 45,
  'country': 'Peru',
  'subscription_type': 'Basic',
  'registration_date': '2022-01-29',
  'total_watch_time_hours': 87.7},
 {'user_id': 'U0062',
  'age': 38,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-06-14',
  'total_watch_time_hours': 314.7},
 {'user_id': 'U0063',
  'age': 26,
  'country': 'Peru',
  'subscription_type': 'Premium',
  'registration_date': '2022-12-18',
  'total_watch_time_hours': 561.1},
 {'user_id': 'U0064',
  'age': 52,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2024-01-14',
  'total_watch_time_hours': 206.1},
 {'user_id': 'U0065',
  'age': 54,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2022-12-15',
  'total_watch_time_hours': 49.9},
 {'user_id': 'U0066',
  'age': 50,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-09-07',
  'total_watch_time_hours': 109.6},
 {'user_id': 'U0067',
  'age': 38,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-09-28',
  'total_watch_time_hours': 410.2},
 {'user_id': 'U0068',
  'age': 50,
  'country': 'Peru',
  'subscription_type': 'Basic',
  'registration_date': '2022-03-24',
  'total_watch_time_hours': 478.5},
 {'user_id': 'U0069',
  'age': 50,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2022-07-24',
  'total_watch_time_hours': 381.5},
 {'user_id': 'U0070',
  'age': 19,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-07-18',
  'total_watch_time_hours': 186.7},
 {'user_id': 'U0071',
  'age': 32,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2022-03-29',
  'total_watch_time_hours': 304.0},
 {'user_id': 'U0072',
  'age': 23,
  'country': 'Peru',
  'subscription_type': 'Standard',
  'registration_date': '2022-12-16',
  'total_watch_time_hours': 371.9},
 {'user_id': 'U0073',
  'age': 26,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2023-07-02',
  'total_watch_time_hours': 168.0},
 {'user_id': 'U0074',
  'age': 48,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2023-05-20',
  'total_watch_time_hours': 368.0},
 {'user_id': 'U0075',
  'age': 19,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-09-21',
  'total_watch_time_hours': 791.4},
 {'user_id': 'U0076',
  'age': 54,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2023-05-13',
  'total_watch_time_hours': 318.3},
 {'user_id': 'U0077',
  'age': 32,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2023-05-29',
  'total_watch_time_hours': 463.2},
 {'user_id': 'U0078',
  'age': 57,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2023-10-13',
  'total_watch_time_hours': 11.6},
 {'user_id': 'U0079',
  'age': 56,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2023-09-16',
  'total_watch_time_hours': 873.8},
 {'user_id': 'U0080',
  'age': 39,
  'country': 'Argentina',
  'subscription_type': 'Standard',
  'registration_date': '2023-12-14',
  'total_watch_time_hours': 355.8},
 {'user_id': 'U0081',
  'age': 62,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-02-23',
  'total_watch_time_hours': 336.1},
 {'user_id': 'U0082',
  'age': 47,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2023-01-06',
  'total_watch_time_hours': 479.3},
 {'user_id': 'U0083',
  'age': 44,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-11-20',
  'total_watch_time_hours': 371.5},
 {'user_id': 'U0084',
  'age': 46,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-12-18',
  'total_watch_time_hours': 815.2},
 {'user_id': 'U0085',
  'age': 30,
  'country': 'Chile',
  'subscription_type': 'Standard',
  'registration_date': '2022-07-05',
  'total_watch_time_hours': 236.8},
 {'user_id': 'U0086',
  'age': 21,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2023-03-01',
  'total_watch_time_hours': 213.3},
 {'user_id': 'U0087',
  'age': 34,
  'country': 'Chile',
  'subscription_type': 'Premium',
  'registration_date': '2022-06-29',
  'total_watch_time_hours': 859.2},
 {'user_id': 'U0088',
  'age': 42,
  'country': 'Peru',
  'subscription_type': 'Basic',
  'registration_date': '2023-01-13',
  'total_watch_time_hours': 43.9},
 {'user_id': 'U0089',
  'age': 36,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2022-05-06',
  'total_watch_time_hours': 455.0},
 {'user_id': 'U0090',
  'age': 50,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-09-12',
  'total_watch_time_hours': 201.5},
 {'user_id': 'U0091',
  'age': 42,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-02-22',
  'total_watch_time_hours': 297.1},
 {'user_id': 'U0092',
  'age': 37,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2022-04-21',
  'total_watch_time_hours': 476.2},
 {'user_id': 'U0093',
  'age': 63,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-11-29',
  'total_watch_time_hours': 232.0},
 {'user_id': 'U0094',
  'age': 46,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-09-30',
  'total_watch_time_hours': 506.4},
 {'user_id': 'U0095',
  'age': 54,
  'country': 'Peru',
  'subscription_type': 'Standard',
  'registration_date': '2023-08-09',
  'total_watch_time_hours': 192.9},
 {'user_id': 'U0096',
  'age': 62,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-04-12',
  'total_watch_time_hours': 275.9},
 {'user_id': 'U0097',
  'age': 35,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-12-12',
  'total_watch_time_hours': 573.5},
 {'user_id': 'U0098',
  'age': 29,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-05-07',
  'total_watch_time_hours': 26.1},
 {'user_id': 'U0099',
  'age': 60,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2023-05-24',
  'total_watch_time_hours': 399.1},
 {'user_id': 'U0100',
  'age': 48,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-07-02',
  'total_watch_time_hours': 31.0},
 {'user_id': 'U0101',
  'age': 52,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2022-05-25',
  'total_watch_time_hours': 152.7},
 {'user_id': 'U0102',
  'age': 41,
  'country': 'Argentina',
  'subscription_type': 'Premium',
  'registration_date': '2022-08-15',
  'total_watch_time_hours': 605.7},
 {'user_id': 'U0103',
  'age': 20,
  'country': 'Chile',
  'subscription_type': 'Standard',
  'registration_date': '2023-04-20',
  'total_watch_time_hours': 339.3},
 {'user_id': 'U0104',
  'age': 56,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-10-23',
  'total_watch_time_hours': 384.3},
 {'user_id': 'U0105',
  'age': 18,
  'country': 'Argentina',
  'subscription_type': 'Basic',
  'registration_date': '2022-11-25',
  'total_watch_time_hours': 404.4},
 {'user_id': 'U0106',
  'age': 32,
  'country': 'Chile',
  'subscription_type': 'Standard',
  'registration_date': '2023-12-06',
  'total_watch_time_hours': 534.0},
 {'user_id': 'U0107',
  'age': 34,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-10-19',
  'total_watch_time_hours': 184.7},
 {'user_id': 'U0108',
  'age': 44,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-01-02',
  'total_watch_time_hours': 261.9},
 {'user_id': 'U0109',
  'age': 56,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2022-01-14',
  'total_watch_time_hours': 228.1},
 {'user_id': 'U0110',
  'age': 28,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2022-07-22',
  'total_watch_time_hours': 36.1},
 {'user_id': 'U0111',
  'age': 51,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2022-06-19',
  'total_watch_time_hours': 691.7},
 {'user_id': 'U0112',
  'age': 51,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2022-07-18',
  'total_watch_time_hours': 285.0},
 {'user_id': 'U0113',
  'age': 47,
  'country': 'Peru',
  'subscription_type': 'Basic',
  'registration_date': '2022-08-18',
  'total_watch_time_hours': 148.4},
 {'user_id': 'U0114',
  'age': 23,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2022-04-16',
  'total_watch_time_hours': 299.5},
 {'user_id': 'U0115',
  'age': 52,
  'country': 'Colombia',
  'subscription_type': 'Basic',
  'registration_date': '2023-07-25',
  'total_watch_time_hours': 132.2},
 {'user_id': 'U0116',
  'age': 30,
  'country': 'Mexico',
  'subscription_type': 'Basic',
  'registration_date': '2023-06-18',
  'total_watch_time_hours': 471.0},
 {'user_id': 'U0117',
  'age': 22,
  'country': 'Mexico',
  'subscription_type': 'Premium',
  'registration_date': '2023-10-13',
  'total_watch_time_hours': 1034.7},
 {'user_id': 'U0118',
  'age': 44,
  'country': 'Chile',
  'subscription_type': 'Basic',
  'registration_date': '2023-04-05',
  'total_watch_time_hours': 64.4},
 {'user_id': 'U0119',
  'age': 54,
  'country': 'Colombia',
  'subscription_type': 'Premium',
  'registration_date': '2023-03-20',
  'total_watch_time_hours': 689.8},
 {'user_id': 'U0120',
  'age': 45,
  'country': 'Colombia',
  'subscription_type': 'Standard',
  'registration_date': '2023-06-14',
  'total_watch_time_hours': 221.6},
 {'user_id': 'U0121',
  'age': 49,
  'country': 'Mexico',
  'subscription_type': 'Standard',
  'registration_date': '2022-05-18',

In [34]:
def leer():
    df_csv = pd.read_csv(file_path)
    return df_csv

def comprobar():
    df = leer()
    columns = list(df.columns)
    if table == "users":
        data_types = [str, int, str, str, str, float]
        for column in columns:
            data_type = data_types.pop(0)
            df = df.astype({column : data_type})
        df = df.to_json(orient='records')
        df_processed = json.loads(df)
        for dictionary in df_processed:
            yield dictionary
    else:
        data_types = [str, str, str, str, int, float, str, str]
        for column in columns:
            data_type = data_types.pop(0)
            df = df.astype({column : data_type})
        df = df.to_json(orient='records')
        df_processed = json.loads(df)
        for dictionary in df_processed:
            yield dictionary

def preparar(dictionary: dict):
    payload_body = {
        'table': table,
        'data': dictionary
    }
    return payload_body

def enviar(dictionary: dict):
    response= preparar(dictionary)
    print(f"Se ha enviado {response}")

if __name__ == '__main__':
    for dictionary in comprobar():
        enviar(dictionary)

Se ha enviado {'table': 'users', 'data': {'user_id': 'U0001', 'age': 21, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-10-02', 'total_watch_time_hours': 58.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0002', 'age': 44, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-09-30', 'total_watch_time_hours': 75.3}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0003', 'age': 20, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-01-24', 'total_watch_time_hours': 360.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0004', 'age': 39, 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2022-12-15', 'total_watch_time_hours': 513.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0005', 'age': 28, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-05-19', 'total_watch_time_hours': 192.8}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0006', 'age': 39, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-12-20', 'total_watch_time_hours': 156.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0007', 'age': 18, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-03-23', 'total_watch_time_hours': 428.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0008', 'age': 56, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-01-22', 'total_watch_time_hours': 47.8}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0009', 'age': 38, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2024-01-20', 'total_watch_time_hours': 229.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0010', 'age': 20, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-04-05', 'total_watch_time_hours': 444.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0011', 'age': 26, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-01-22', 'total_watch_time_hours': 336.6}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0012', 'age': 45, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-08-11', 'total_watch_time_hours': 292.4}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0013', 'age': 48, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-02-07', 'total_watch_time_hours': 386.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0014', 'age': 39, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-06-19', 'total_watch_time_hours': 402.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0015', 'age': 31, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-09-16', 'total_watch_time_hours': 387.6}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0016', 'age': 54, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-11-19', 'total_watch_time_hours': 17.4}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0017', 'age': 59, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-06-10', 'total_watch_time_hours': 240.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0018', 'age': 52, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-10-16', 'total_watch_time_hours': 360.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0019', 'age': 56, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2023-05-13', 'total_watch_time_hours': 477.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0020', 'age': 44, 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2023-01-19', 'total_watch_time_hours': 311.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0021', 'age': 59, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-07-05', 'total_watch_time_hours': 329.1}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0022', 'age': 23, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-05-14', 'total_watch_time_hours': 438.8}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0023', 'age': 28, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2022-12-09', 'total_watch_time_hours': 192.6}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0024', 'age': 43, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-03-17', 'total_watch_time_hours': 728.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0025', 'age': 42, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-08-10', 'total_watch_time_hours': 469.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0026', 'age': 19, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2022-07-13', 'total_watch_time_hours': 653.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0027', 'age': 58, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-01-08', 'total_watch_time_hours': 17.6}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0028', 'age': 40, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-08-23', 'total_watch_time_hours': 208.8}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0029', 'age': 50, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2024-01-12', 'total_watch_time_hours': 496.6}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0030', 'age': 21, 'country': 'Chile', 'subscription_type': 'Standard', 'registration_date': '2023-10-17', 'total_watch_time_hours': 199.3}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0031', 'age': 49, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2024-02-22', 'total_watch_time_hours': 382.4}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0032', 'age': 32, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-07-12', 'total_watch_time_hours': 296.5}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0033', 'age': 29, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2022-06-07', 'total_watch_time_hours': 545.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0034', 'age': 46, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2023-01-23', 'total_watch_time_hours': 378.3}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0035', 'age': 20, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-01-11', 'total_watch_time_hours': 100.3}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0036', 'age': 30, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2022-01-22', 'total_watch_time_hours': 271.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0037', 'age': 40, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-12-03', 'total_watch_time_hours': 171.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0038', 'age': 45, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-10-12', 'total_watch_time_hours': 259.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0039', 'age': 24, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-09-25', 'total_watch_time_hours': 44.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0040', 'age': 40, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-12-26', 'total_watch_time_hours': 64.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0041', 'age': 45, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-01-09', 'total_watch_time_hours': 479.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0042', 'age': 42, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-03-17', 'total_watch_time_hours': 277.8}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0043', 'age': 58, 'country': 'Peru', 'subscription_type': 'Premium', 'registration_date': '2023-02-18', 'total_watch_time_hours': 43.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0044', 'age': 38, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-09-26', 'total_watch_time_hours': 478.3}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0045', 'age': 20, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2024-02-08', 'total_watch_time_hours': 313.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0046', 'age': 44, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-12-23', 'total_watch_time_hours': 43.3}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0047', 'age': 58, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-06-17', 'total_watch_time_hours': 797.6}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0048', 'age': 44, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2022-03-07', 'total_watch_time_hours': 434.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0049', 'age': 61, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2022-05-28', 'total_watch_time_hours': 173.1}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0050', 'age': 33, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2024-02-01', 'total_watch_time_hours': 48.4}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0051', 'age': 58, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-02-28', 'total_watch_time_hours': 412.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0052', 'age': 42, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2023-07-05', 'total_watch_time_hours': 160.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0053', 'age': 59, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2024-03-01', 'total_watch_time_hours': 495.5}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0054', 'age': 42, 'country': 'Chile', 'subscription_type': 'Standard', 'registration_date': '2023-01-13', 'total_watch_time_hours': 86.4}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0055', 'age': 39, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2023-06-14', 'total_watch_time_hours': 68.6}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0056', 'age': 28, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-08-27', 'total_watch_time_hours': 219.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0057', 'age': 21, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2024-01-30', 'total_watch_time_hours': 168.6}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0058', 'age': 60, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-01-22', 'total_watch_time_hours': 195.8}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0059', 'age': 65, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2024-01-28', 'total_watch_time_hours': 391.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0060', 'age': 63, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2023-11-16', 'total_watch_time_hours': 415.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0061', 'age': 45, 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2022-01-29', 'total_watch_time_hours': 87.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0062', 'age': 38, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-06-14', 'total_watch_time_hours': 314.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0063', 'age': 26, 'country': 'Peru', 'subscription_type': 'Premium', 'registration_date': '2022-12-18', 'total_watch_time_hours': 561.1}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0064', 'age': 52, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2024-01-14', 'total_watch_time_hours': 206.1}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0065', 'age': 54, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2022-12-15', 'total_watch_time_hours': 49.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0066', 'age': 50, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-09-07', 'total_watch_time_hours': 109.6}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0067', 'age': 38, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-09-28', 'total_watch_time_hours': 410.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0068', 'age': 50, 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2022-03-24', 'total_watch_time_hours': 478.5}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0069', 'age': 50, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-07-24', 'total_watch_time_hours': 381.5}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0070', 'age': 19, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-07-18', 'total_watch_time_hours': 186.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0071', 'age': 32, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2022-03-29', 'total_watch_time_hours': 304.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0072', 'age': 23, 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2022-12-16', 'total_watch_time_hours': 371.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0073', 'age': 26, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2023-07-02', 'total_watch_time_hours': 168.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0074', 'age': 48, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-05-20', 'total_watch_time_hours': 368.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0075', 'age': 19, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-09-21', 'total_watch_time_hours': 791.4}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0076', 'age': 54, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2023-05-13', 'total_watch_time_hours': 318.3}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0077', 'age': 32, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2023-05-29', 'total_watch_time_hours': 463.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0078', 'age': 57, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-10-13', 'total_watch_time_hours': 11.6}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0079', 'age': 56, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2023-09-16', 'total_watch_time_hours': 873.8}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0080', 'age': 39, 'country': 'Argentina', 'subscription_type': 'Standard', 'registration_date': '2023-12-14', 'total_watch_time_hours': 355.8}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0081', 'age': 62, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-02-23', 'total_watch_time_hours': 336.1}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0082', 'age': 47, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2023-01-06', 'total_watch_time_hours': 479.3}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0083', 'age': 44, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-11-20', 'total_watch_time_hours': 371.5}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0084', 'age': 46, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-12-18', 'total_watch_time_hours': 815.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0085', 'age': 30, 'country': 'Chile', 'subscription_type': 'Standard', 'registration_date': '2022-07-05', 'total_watch_time_hours': 236.8}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0086', 'age': 21, 'country': 'Chile', 'subscription_type': 'Basic', 'registration_date': '2023-03-01', 'total_watch_time_hours': 213.3}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0087', 'age': 34, 'country': 'Chile', 'subscription_type': 'Premium', 'registration_date': '2022-06-29', 'total_watch_time_hours': 859.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0088', 'age': 42, 'country': 'Peru', 'subscription_type': 'Basic', 'registration_date': '2023-01-13', 'total_watch_time_hours': 43.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0089', 'age': 36, 'country': 'Mexico', 'subscription_type': 'Basic', 'registration_date': '2022-05-06', 'total_watch_time_hours': 455.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0090', 'age': 50, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2023-09-12', 'total_watch_time_hours': 201.5}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0091', 'age': 42, 'country': 'Argentina', 'subscription_type': 'Basic', 'registration_date': '2022-02-22', 'total_watch_time_hours': 297.1}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0092', 'age': 37, 'country': 'Mexico', 'subscription_type': 'Premium', 'registration_date': '2022-04-21', 'total_watch_time_hours': 476.2}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0093', 'age': 63, 'country': 'Colombia', 'subscription_type': 'Premium', 'registration_date': '2022-11-29', 'total_watch_time_hours': 232.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0094', 'age': 46, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-09-30', 'total_watch_time_hours': 506.4}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0095', 'age': 54, 'country': 'Peru', 'subscription_type': 'Standard', 'registration_date': '2023-08-09', 'total_watch_time_hours': 192.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0096', 'age': 62, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-04-12', 'total_watch_time_hours': 275.9}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0097', 'age': 35, 'country': 'Colombia', 'subscription_type': 'Standard', 'registration_date': '2022-12-12', 'total_watch_time_hours': 573.5}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0098', 'age': 29, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2022-05-07', 'total_watch_time_hours': 26.1}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0099', 'age': 60, 'country': 'Mexico', 'subscription_type': 'Standard', 'registration_date': '2023-05-24', 'total_watch_time_hours': 399.1}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0100', 'age': 48, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2023-07-02', 'total_watch_time_hours': 31.0}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0101', 'age': 52, 'country': 'Colombia', 'subscription_type': 'Basic', 'registration_date': '2022-05-25', 'total_watch_time_hours': 152.7}}
Se ha enviado {'table': 'users', 'data': {'user_id': 'U0102', 'age': 41, 'country': 'Argentina', 'subscription_type': 'Premium', 'registration_date': '2022-08-15', 'total_watch_time_hours': 605.7}}

## Version C

In [105]:
import pandas as pd, json

In [106]:
# Variables

file_path = "../data/users.csv"
table = "users"

In [107]:
def leer():
    with open(file_path,'r') as file:
        df_json = pd.read_csv(file)
        return df_json

def convertir_columnas():
    df = leer()
    columnas = list(df.columns)
    if table == "users":
        data_types = [str, int, str, str, str, float]
        for column in columnas:
            item = data_types.pop(0)
            df = df.astype({column: item})
        df_processed = df.to_json(orient='records')
        json_processed = json.loads(df_processed)
        return json_processed
    else:
        data_types = [str, str, str, str, int, float, str, str]
        for column in columnas:
            item = data_types.pop(0)
            df = df.astype({column: item})
        df_processed = df.to_json(orient='records')
        json_processed = json.loads(df_processed)
        return json_processed

def preparar():
    data = convertir_columnas()
    payload_body = {
    'table': table,
    'data': data
    }
    return payload_body    

def enviar():
    response = preparar()
    print(f"¡Se envío correctamente la siguiente información!:\n {response}")
        
if __name__ == '__main__':
    enviar()

¡Se envío correctamente la siguiente información!:

## Version D

In [ ]:
import pandas as pd

# NEW APPROACH - JSON

## Version A

In [58]:
import pandas as pd, json, requests

In [80]:
# Variables

data = "movies"
file_path = '../data/content.json'

In [81]:
# Maybe in a utils file

def transform_types(dictionary: dict, list_1: list, list_2: list):
    for llave in list_1:
        if llave in dictionary.keys():
            value_type = list_2.pop(0)
            dictionary[llave] = value_type(dictionary[llave])
        else:
            raise Exception("The dictionary does not meet the required keys")
    return dictionary

In [82]:
def leer():
    with open(file_path,'r') as file:
        json_data = json.load(file)[data]
    for dictionary in json_data:
        yield dictionary
def comprobar(dictionary:dict):
    if data == 'movies':
        llaves_permitidas = ['_id','title','genre','duration_minutes','release_year','rating','views_count','production_budget']
        data_types = [str, str, list, int, int, float, int, int]
        payload_data = transform_types(dictionary, llaves_permitidas, data_types)
        return payload_data
    elif data == 'series':
        llaves_permitidas = ['_id','title','genre','seasons','episodes_per_season','avg_episode_duration','rating','total_views', 'production_budget']
        data_types = [str, str, list, int, list, int, float, int, int]
        payload_data = transform_types(dictionary, llaves_permitidas, data_types)
        return payload_data

def preparar(dictionary:str):
    new_dict = comprobar(dictionary)
    payload_body = {
        'collection': data,
        'data': new_dict
    }
    return payload_body

def enviar(dictionary):
    dictionary = preparar(dictionary)
    to_API = dictionary
    response = print(f"Se envió correctamente {to_API}")
    return response
    
    
if __name__ == '__main__':
    for dictionary in leer():
        enviar(dictionary)

Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M001', 'title': 'Advanced World', 'genre': ['Sci-Fi', 'Horror', 'Drama'], 'duration_minutes': 179, 'release_year': 2020, 'rating': 3.5, 'views_count': 66721, 'production_budget': 220088717}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M002', 'title': 'Neural Signal', 'genre': ['Animation', 'Horror'], 'duration_minutes': 146, 'release_year': 2021, 'rating': 2.8, 'views_count': 11128, 'production_budget': 23593231}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M003', 'title': 'An Stream', 'genre': ['Action'], 'duration_minutes': 102, 'release_year': 2023, 'rating': 1.9, 'views_count': 75949, 'production_budget': 83166461}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M004', 'title': 'Binary Journey', 'genre': ['Thriller', 'Documentary'], 'duration_minutes': 146, 'release_year': 2022, 'rating': 3.0, 'views_count': 85958, 'production_budget': 46298444}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M005', 'title': 'Lost Data', 'genre': ['Horror', 'Romance'], 'duration_minutes': 169, 'release_year': 2022, 'rating': 4.7, 'views_count': 56808, 'production_budget': 67293750}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M006', 'title': 'Ultimate Mystery', 'genre': ['Action', 'Animation', 'Horror'], 'duration_minutes': 157, 'release_year': 2024, 'rating': 1.1, 'views_count': 148876, 'production_budget': 234348717}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M007', 'title': 'Code', 'genre': ['Comedy', 'Romance'], 'duration_minutes': 136, 'release_year': 2022, 'rating': 3.1, 'views_count': 9228, 'production_budget': 35028167}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M008', 'title': 'Digital Protocol', 'genre': ['Documentary', 'Romance'], 'duration_minutes': 155, 'release_year': 2023, 'rating': 3.7, 'views_count': 125068, 'production_budget': 49545701}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M009', 'title': 'Tale', 'genre': ['Drama', 'Horror'], 'duration_minutes': 90, 'release_year': 2023, 'rating': 4.4, 'views_count': 37911, 'production_budget': 146895476}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M010', 'title': 'An Code 2', 'genre': ['Comedy', 'Romance', 'Action'], 'duration_minutes': 174, 'release_year': 2021, 'rating': 3.5, 'views_count': 78005, 'production_budget': 224671521}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M011', 'title': 'Algorithm', 'genre': ['Drama', 'Animation', 'Horror'], 'duration_minutes': 81, 'release_year': 2023, 'rating': 2.7, 'views_count': 92634, 'production_budget': 20512281}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M012', 'title': 'Quest 5', 'genre': ['Comedy'], 'duration_minutes': 104, 'release_year': 2023, 'rating': 2.4, 'views_count': 59155, 'production_budget': 36408859}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M013', 'title': 'Mystery', 'genre': ['Documentary', 'Drama'], 'duration_minutes': 178, 'release_year': 2020, 'rating': 1.6, 'views_count': 61328, 'production_budget': 16064411}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M014', 'title': 'Kingdom', 'genre': ['Thriller', 'Action'], 'duration_minutes': 122, 'release_year': 2021, 'rating': 4.2, 'views_count': 138918, 'production_budget': 202395249}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M015', 'title': 'Quantum Code', 'genre': ['Animation', 'Documentary', 'Sci-Fi'], 'duration_minutes': 177, 'release_year': 2021, 'rating': 2.4, 'views_count': 13807, 'production_budget': 227198245}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M016', 'title': 'A Database', 'genre': ['Drama', 'Documentary'], 'duration_minutes': 95, 'release_year': 2023, 'rating': 3.0, 'views_count': 81858, 'production_budget': 6729979}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M017', 'title': 'Adventure', 'genre': ['Action', 'Documentary', 'Horror'], 'duration_minutes': 97, 'release_year': 2020, 'rating': 4.6, 'views_count': 132014, 'production_budget': 50839665}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M018', 'title': 'Mystery', 'genre': ['Comedy', 'Action'], 'duration_minutes': 84, 'release_year': 2023, 'rating': 3.6, 'views_count': 81531, 'production_budget': 158431993}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M019', 'title': 'Final Stream', 'genre': ['Action'], 'duration_minutes': 83, 'release_year': 2023, 'rating': 2.3, 'views_count': 144211, 'production_budget': 114952801}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M020', 'title': 'Quest', 'genre': ['Thriller', 'Action', 'Drama'], 'duration_minutes': 108, 'release_year': 2022, 'rating': 3.1, 'views_count': 47873, 'production_budget': 250548961}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M021', 'title': 'Tale', 'genre': ['Drama', 'Horror'], 'duration_minutes': 148, 'release_year': 2020, 'rating': 4.9, 'views_count': 168298, 'production_budget': 62478620}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M022', 'title': 'Quantum System', 'genre': ['Horror'], 'duration_minutes': 147, 'release_year': 2023, 'rating': 4.7, 'views_count': 116580, 'production_budget': 73128204}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M023', 'title': 'Smart Story', 'genre': ['Horror'], 'duration_minutes': 147, 'release_year': 2022, 'rating': 3.3, 'views_count': 36200, 'production_budget': 12509378}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M024', 'title': 'First Mystery', 'genre': ['Horror'], 'duration_minutes': 159, 'release_year': 2020, 'rating': 4.2, 'views_count': 117924, 'production_budget': 146907831}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M025', 'title': 'An Protocol', 'genre': ['Comedy'], 'duration_minutes': 162, 'release_year': 2020, 'rating': 4.0, 'views_count': 26519, 'production_budget': 49021276}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M026', 'title': 'Lost Kingdom', 'genre': ['Documentary', 'Drama', 'Action'], 'duration_minutes': 163, 'release_year': 2024, 'rating': 2.6, 'views_count': 113230, 'production_budget': 90625130}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M027', 'title': 'Quantum Story', 'genre': ['Thriller', 'Horror', 'Sci-Fi'], 'duration_minutes': 128, 'release_year': 2023, 'rating': 1.2, 'views_count': 19816, 'production_budget': 150283990}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M028', 'title': 'Final Kingdom', 'genre': ['Comedy', 'Horror', 'Drama'], 'duration_minutes': 175, 'release_year': 2023, 'rating': 1.7, 'views_count': 87291, 'production_budget': 8816404}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M029', 'title': 'System', 'genre': ['Documentary'], 'duration_minutes': 123, 'release_year': 2023, 'rating': 1.8, 'views_count': 27793, 'production_budget': 30738350}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M030', 'title': 'Database 4', 'genre': ['Drama', 'Action'], 'duration_minutes': 145, 'release_year': 2020, 'rating': 1.3, 'views_count': 98063, 'production_budget': 100987742}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M031', 'title': 'Empire', 'genre': ['Action', 'Animation', 'Drama'], 'duration_minutes': 104, 'release_year': 2020, 'rating': 4.9, 'views_count': 114316, 'production_budget': 184475405}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M032', 'title': 'A Code', 'genre': ['Thriller', 'Action'], 'duration_minutes': 133, 'release_year': 2024, 'rating': 3.4, 'views_count': 83014, 'production_budget': 283617949}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M033', 'title': 'Dark Stream', 'genre': ['Action', 'Animation'], 'duration_minutes': 119, 'release_year': 2023, 'rating': 2.9, 'views_count': 54865, 'production_budget': 193790052}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M034', 'title': 'Stream', 'genre': ['Romance', 'Sci-Fi', 'Action'], 'duration_minutes': 151, 'release_year': 2020, 'rating': 4.9, 'views_count': 41348, 'production_budget': 122112109}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M035', 'title': 'Lost System 5', 'genre': ['Thriller', 'Romance'], 'duration_minutes': 112, 'release_year': 2021, 'rating': 1.8, 'views_count': 64414, 'production_budget': 2127388}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M036', 'title': 'Quest', 'genre': ['Romance', 'Animation'], 'duration_minutes': 100, 'release_year': 2020, 'rating': 2.9, 'views_count': 90335, 'production_budget': 12670028}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M037', 'title': 'Quest', 'genre': ['Animation', 'Comedy', 'Documentary'], 'duration_minutes': 90, 'release_year': 2022, 'rating': 1.2, 'views_count': 13250, 'production_budget': 33987762}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M038', 'title': 'Data', 'genre': ['Animation', 'Documentary'], 'duration_minutes': 161, 'release_year': 2021, 'rating': 3.6, 'views_count': 47672, 'production_budget': 15316213}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M039', 'title': 'Lost Cloud', 'genre': ['Horror', 'Drama', 'Action'], 'duration_minutes': 103, 'release_year': 2020, 'rating': 2.8, 'views_count': 48310, 'production_budget': 202148811}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M040', 'title': 'Quest', 'genre': ['Comedy', 'Documentary', 'Drama'], 'duration_minutes': 171, 'release_year': 2022, 'rating': 2.2, 'views_count': 52925, 'production_budget': 1600669}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M041', 'title': 'Infinite Story', 'genre': ['Horror', 'Thriller'], 'duration_minutes': 117, 'release_year': 2021, 'rating': 4.2, 'views_count': 129104, 'production_budget': 186923029}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M042', 'title': 'Advanced System 2', 'genre': ['Documentary'], 'duration_minutes': 163, 'release_year': 2020, 'rating': 3.3, 'views_count': 44583, 'production_budget': 42856949}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M043', 'title': 'Hidden Empire', 'genre': ['Horror'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 4.1, 'views_count': 290064, 'production_budget': 128140036}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M044', 'title': 'Cyber Cloud 4', 'genre': ['Animation', 'Thriller'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 3.3, 'views_count': 8992, 'production_budget': 8120314}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M045', 'title': 'First Database', 'genre': ['Animation', 'Action'], 'duration_minutes': 123, 'release_year': 2023, 'rating': 3.1, 'views_count': 115282, 'production_budget': 182644208}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M046', 'title': 'Binary Signal', 'genre': ['Animation', 'Documentary', 'Thriller'], 'duration_minutes': 147, 'release_year': 2023, 'rating': 1.9, 'views_count': 18247, 'production_budget': 24000248}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M047', 'title': 'Story', 'genre': ['Drama'], 'duration_minutes': 120, 'release_year': 2023, 'rating': 3.3, 'views_count': 5974, 'production_budget': 18448764}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M048', 'title': 'Tale', 'genre': ['Horror', 'Romance', 'Documentary'], 'duration_minutes': 104, 'release_year': 2021, 'rating': 4.9, 'views_count': 178486, 'production_budget': 59289648}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M049', 'title': 'Neural Cloud 2', 'genre': ['Drama', 'Sci-Fi', 'Action'], 'duration_minutes': 126, 'release_year': 2020, 'rating': 3.7, 'views_count': 33051, 'production_budget': 135871052}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M050', 'title': 'Infinite Protocol', 'genre': ['Thriller', 'Documentary'], 'duration_minutes': 96, 'release_year': 2021, 'rating': 2.0, 'views_count': 53173, 'production_budget': 39370044}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M051', 'title': 'A Algorithm', 'genre': ['Animation'], 'duration_minutes': 155, 'release_year': 2022, 'rating': 4.8, 'views_count': 136410, 'production_budget': 106311259}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M052', 'title': 'Adventure', 'genre': ['Horror', 'Thriller', 'Sci-Fi'], 'duration_minutes': 120, 'release_year': 2021, 'rating': 3.9, 'views_count': 94063, 'production_budget': 193008798}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M053', 'title': 'Infinite Empire', 'genre': ['Action'], 'duration_minutes': 162, 'release_year': 2022, 'rating': 1.9, 'views_count': 50863, 'production_budget': 296179703}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M054', 'title': 'Binary Stream', 'genre': ['Action', 'Animation', 'Documentary'], 'duration_minutes': 98, 'release_year': 2021, 'rating': 4.6, 'views_count': 17832, 'production_budget': 122289319}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M055', 'title': 'Infinite Adventure', 'genre': ['Thriller'], 'duration_minutes': 142, 'release_year': 2023, 'rating': 3.6, 'views_count': 121651, 'production_budget': 37909361}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M056', 'title': 'Binary Journey', 'genre': ['Thriller', 'Action'], 'duration_minutes': 88, 'release_year': 2023, 'rating': 3.6, 'views_count': 105627, 'production_budget': 140493022}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M057', 'title': 'Journey', 'genre': ['Drama', 'Sci-Fi'], 'duration_minutes': 149, 'release_year': 2022, 'rating': 1.9, 'views_count': 38409, 'production_budget': 213938522}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M058', 'title': 'Last Quest', 'genre': ['Documentary', 'Animation', 'Romance'], 'duration_minutes': 173, 'release_year': 2020, 'rating': 3.6, 'views_count': 53146, 'production_budget': 20440772}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M059', 'title': 'System', 'genre': ['Sci-Fi', 'Thriller', 'Drama'], 'duration_minutes': 146, 'release_year': 2020, 'rating': 1.5, 'views_count': 63578, 'production_budget': 80650718}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M060', 'title': 'Dark Kingdom', 'genre': ['Thriller', 'Sci-Fi'], 'duration_minutes': 122, 'release_year': 2020, 'rating': 4.9, 'views_count': 196906, 'production_budget': 107714280}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M061', 'title': 'An Cloud', 'genre': ['Drama', 'Comedy', 'Action'], 'duration_minutes': 99, 'release_year': 2022, 'rating': 4.6, 'views_count': 58038, 'production_budget': 181262622}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M062', 'title': 'Secret Empire', 'genre': ['Horror'], 'duration_minutes': 136, 'release_year': 2024, 'rating': 1.1, 'views_count': 113496, 'production_budget': 45559979}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M063', 'title': 'Neural Cloud', 'genre': ['Sci-Fi', 'Drama'], 'duration_minutes': 104, 'release_year': 2024, 'rating': 4.5, 'views_count': 241308, 'production_budget': 52788131}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M064', 'title': 'Virtual Adventure', 'genre': ['Drama', 'Action'], 'duration_minutes': 113, 'release_year': 2024, 'rating': 4.4, 'views_count': 99105, 'production_budget': 99191442}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M065', 'title': 'Final Story', 'genre': ['Documentary', 'Romance', 'Sci-Fi'], 'duration_minutes': 102, 'release_year': 2024, 'rating': 1.9, 'views_count': 107506, 'production_budget': 92334091}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M066', 'title': 'Last World', 'genre': ['Animation'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 4.1, 'views_count': 139206, 'production_budget': 232940727}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M067', 'title': 'Smart World', 'genre': ['Documentary', 'Romance', 'Sci-Fi'], 'duration_minutes': 126, 'release_year': 2023, 'rating': 4.0, 'views_count': 125397, 'production_budget': 233435578}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M068', 'title': 'Protocol', 'genre': ['Comedy', 'Thriller', 'Horror'], 'duration_minutes': 169, 'release_year': 2024, 'rating': 4.2, 'views_count': 110097, 'production_budget': 100149438}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M069', 'title': 'Last World', 'genre': ['Horror'], 'duration_minutes': 119, 'release_year': 2022, 'rating': 4.0, 'views_count': 12355, 'production_budget': 39301506}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M070', 'title': 'Lost Adventure', 'genre': ['Drama', 'Sci-Fi'], 'duration_minutes': 171, 'release_year': 2020, 'rating': 1.7, 'views_count': 5512, 'production_budget': 218689270}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M071', 'title': 'Cyber Tale', 'genre': ['Sci-Fi', 'Drama', 'Comedy'], 'duration_minutes': 102, 'release_year': 2023, 'rating': 4.3, 'views_count': 292824, 'production_budget': 139504878}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M072', 'title': 'Secret Signal', 'genre': ['Romance'], 'duration_minutes': 125, 'release_year': 2022, 'rating': 1.6, 'views_count': 60180, 'production_budget': 8844926}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M073', 'title': 'System', 'genre': ['Documentary', 'Animation', 'Action'], 'duration_minutes': 141, 'release_year': 2021, 'rating': 1.3, 'views_count': 12675, 'production_budget': 167251523}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M074', 'title': 'Digital Database', 'genre': ['Comedy'], 'duration_minutes': 146, 'release_year': 2022, 'rating': 3.2, 'views_count': 8998, 'production_budget': 29227591}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M075', 'title': 'Neural Journey', 'genre': ['Sci-Fi', 'Thriller', 'Romance'], 'duration_minutes': 125, 'release_year': 2020, 'rating': 4.2, 'views_count': 84468, 'production_budget': 296040480}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M076', 'title': 'The Journey', 'genre': ['Thriller', 'Documentary', 'Animation'], 'duration_minutes': 166, 'release_year': 2020, 'rating': 2.4, 'views_count': 78189, 'production_budget': 27396354}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M077', 'title': 'Signal', 'genre': ['Romance'], 'duration_minutes': 101, 'release_year': 2021, 'rating': 4.5, 'views_count': 97638, 'production_budget': 203590741}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M078', 'title': 'Algorithm', 'genre': ['Comedy', 'Romance', 'Documentary'], 'duration_minutes': 155, 'release_year': 2024, 'rating': 1.6, 'views_count': 28957, 'production_budget': 13524987}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M079', 'title': 'Secret Algorithm', 'genre': ['Thriller'], 'duration_minutes': 156, 'release_year': 2022, 'rating': 3.8, 'views_count': 44993, 'production_budget': 46138210}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M080', 'title': 'Digital Empire', 'genre': ['Comedy'], 'duration_minutes': 99, 'release_year': 2022, 'rating': 3.5, 'views_count': 51624, 'production_budget': 49787105}}
Se envió correctamente {'collection': 'movies', 'data': {'_id': 'M081', 'title': 'A Empire', 'genre': ['Thriller'], 'duration_minutes': 158, 'release_year': 2023, 'rating': 3.2, 'views_count': 20857, 'production_budget': 21843745}}

## Version B

In [83]:
import pandas as pd,json, io

In [84]:
# Variables

data = "series"
file_path = '../data/content.json'

In [85]:
with open(file_path,'r') as file:
    json_data = json.load(file)[data]
json_dataframe = pd.json_normalize(json_data)
columnas = list(json_dataframe.columns)
print(columnas)

['_id', 'title', 'genre', 'seasons', 'episodes_per_season', 'avg_episode_duration', 'rating', 'total_views', 'production_budget']

In [86]:
json_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   _id                   100 non-null    object
 1   title                 100 non-null    object
 2   genre                 100 non-null    object
 3   seasons               100 non-null    int64
 4   episodes_per_season   100 non-null    object
 5   avg_episode_duration  100 non-null    int64
 6   rating                100 non-null    float64
 7   total_views           100 non-null    int64
 8   production_budget     100 non-null    int64
dtypes: float64(1), int64(4), object(4)
memory usage: 7.2+ KB

In [ ]:
def leer():
    with open(file_path,'r') as file:
        json_data = json.load(file)[data]
        df_json = pd.json_normalize(json_data)
        return df_json

def convertir_columnas():
    df = leer()
    if data == "movies":
        data_types = [str, str, object, int, int, float, int, int]
        for column in columnas:
            item = data_types.pop(0)
            df = df.astype({column: item})
        df_processed = df.to_json(orient='records')
        json_processed = json.loads(df_processed)
        for dictionary in json_processed:
            yield dictionary
    elif data == "series":
        data_types = [str, str, object, int, object, int, float, int, int]
        for column in columnas:
            item = data_types.pop(0)
            df = df.astype({column: item})
        df_processed = df.to_json(orient='records')
        json_processed = json.loads(df_processed)
        for dictionary in json_processed:
            yield dictionary
def preparar(dictionary: dict):
    payload_body = {
        'collection': data,
        'data': dictionary
    }
    return payload_body

def enviar(dictionary):
    to_API = preparar(dictionary)
    print(f"¡Se envío correctamente la siguiente información!:\n {to_API}")
        
if __name__ == '__main__':
    for dictionary in convertir_columnas():
        enviar(dictionary)

¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S001', 'title': 'The Investigators', 'genre': ['Crime'], 'seasons': 7, 'episodes_per_season': [8, 14, 7, 17, 12, 13, 18], 'avg_episode_duration': 50, 'rating': 1.3, 'total_views': 50315, 'production_budget': 44041273}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S002', 'title': 'The Investigators', 'genre': ['Sci-Fi'], 'seasons': 7, 'episodes_per_season': [16, 12, 14, 14, 23, 9, 24], 'avg_episode_duration': 20, 'rating': 4.4, 'total_views': 351932, 'production_budget': 126866932}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S003', 'title': 'System Archives', 'genre': ['Documentary'], 'seasons': 4, 'episodes_per_season': [9, 7, 21, 14], 'avg_episode_duration': 44, 'rating': 2.8, 'total_views': 78137, 'production_budget': 56625408}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S004', 'title': 'Cyber Archives', 'genre': ['Comedy', 'Romance'], 'seasons': 2, 'episodes_per_season': [8, 6], 'avg_episode_duration': 58, 'rating': 2.2, 'total_views': 58071, 'production_budget': 47182636}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S005', 'title': 'The Scientists', 'genre': ['Action', 'Drama'], 'seasons': 5, 'episodes_per_season': [22, 14, 6, 14, 9], 'avg_episode_duration': 29, 'rating': 4.4, 'total_views': 76998, 'production_budget': 327965922}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S006', 'title': 'The Scientists', 'genre': ['Reality', 'Crime'], 'seasons': 8, 'episodes_per_season': [10, 19, 7, 12, 21, 6, 10, 9], 'avg_episode_duration': 30, 'rating': 1.5, 'total_views': 34209, 'production_budget': 10288145}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S007', 'title': 'The Analysts', 'genre': ['Documentary'], 'seasons': 4, 'episodes_per_season': [16, 9, 14, 12], 'avg_episode_duration': 58, 'rating': 1.2, 'total_views': 63328, 'production_budget': 58423635}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S008', 'title': 'Intelligence Cases', 'genre': ['Reality', 'Sci-Fi'], 'seasons': 3, 'episodes_per_season': [21, 6, 7], 'avg_episode_duration': 28, 'rating': 3.8, 'total_views': 172536, 'production_budget': 65923441}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S009', 'title': 'The Investigators', 'genre': ['Action'], 'seasons': 2, 'episodes_per_season': [12, 23], 'avg_episode_duration': 38, 'rating': 3.4, 'total_views': 176621, 'production_budget': 25451448}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S010', 'title': 'The Detectives', 'genre': ['Romance', 'Sci-Fi'], 'seasons': 6, 'episodes_per_season': [11, 7, 21, 24, 15, 7], 'avg_episode_duration': 51, 'rating': 2.2, 'total_views': 137965, 'production_budget': 30273595}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S011', 'title': 'Tech Cases', 'genre': ['Crime', 'Sci-Fi'], 'seasons': 1, 'episodes_per_season': [17], 'avg_episode_duration': 39, 'rating': 4.9, 'total_views': 290490, 'production_budget': 114902788}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S012', 'title': 'Code Engineer Files', 'genre': ['Sci-Fi'], 'seasons': 5, 'episodes_per_season': [7, 10, 18, 19, 13], 'avg_episode_duration': 34, 'rating': 4.1, 'total_views': 170988, 'production_budget': 208347149}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S013', 'title': 'The Analysts', 'genre': ['Documentary'], 'seasons': 8, 'episodes_per_season': [11, 21, 24, 14, 19, 15, 19, 10], 'avg_episode_duration': 52, 'rating': 3.2, 'total_views': 107304, 'production_budget': 77414168}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S014', 'title': 'System Master Records', 'genre': ['Romance', 'Drama'], 'seasons': 8, 'episodes_per_season': [24, 21, 23, 21, 7, 10, 22, 12], 'avg_episode_duration': 60, 'rating': 1.7, 'total_views': 120686, 'production_budget': 396719513}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S015', 'title': 'System Analyst Logs', 'genre': ['Documentary'], 'seasons': 8, 'episodes_per_season': [10, 10, 12, 12, 16, 8, 9, 22], 'avg_episode_duration': 30, 'rating': 1.7, 'total_views': 173243, 'production_budget': 86131629}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S016', 'title': 'The Investigators', 'genre': ['Action'], 'seasons': 4, 'episodes_per_season': [23, 7, 18, 7], 'avg_episode_duration': 55, 'rating': 2.1, 'total_views': 134389, 'production_budget': 68265098}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S017', 'title': 'Data Expert Chronicles', 'genre': ['Action', 'Drama'], 'seasons': 7, 'episodes_per_season': [9, 15, 11, 24, 18, 17, 19], 'avg_episode_duration': 38, 'rating': 2.4, 'total_views': 12444, 'production_budget': 137756173}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S018', 'title': 'Code Files', 'genre': ['Action', 'Comedy'], 'seasons': 5, 'episodes_per_season': [8, 19, 19, 21, 21], 'avg_episode_duration': 37, 'rating': 1.5, 'total_views': 157045, 'production_budget': 19314996}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S019', 'title': 'Analytics Archives', 'genre': ['Romance', 'Drama'], 'seasons': 6, 'episodes_per_season': [15, 14, 11, 12, 11, 22], 'avg_episode_duration': 40, 'rating': 2.2, 'total_views': 188719, 'production_budget': 456731471}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S020', 'title': 'The Analysts', 'genre': ['Romance', 'Crime'], 'seasons': 6, 'episodes_per_season': [7, 13, 13, 16, 16, 23], 'avg_episode_duration': 36, 'rating': 2.2, 'total_views': 66964, 'production_budget': 30466126}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S021', 'title': 'The Specialists', 'genre': ['Crime'], 'seasons': 8, 'episodes_per_season': [20, 17, 14, 17, 12, 22, 17, 10], 'avg_episode_duration': 45, 'rating': 3.0, 'total_views': 33356, 'production_budget': 98820528}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S022', 'title': 'The Investigators', 'genre': ['Reality', 'Drama'], 'seasons': 8, 'episodes_per_season': [13, 21, 7, 23, 9, 11, 11, 8], 'avg_episode_duration': 37, 'rating': 2.1, 'total_views': 61463, 'production_budget': 197105748}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S023', 'title': 'The Engineers', 'genre': ['Action', 'Sci-Fi'], 'seasons': 1, 'episodes_per_season': [14], 'avg_episode_duration': 41, 'rating': 2.6, 'total_views': 47152, 'production_budget': 37455594}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S024', 'title': 'The Detectives', 'genre': ['Crime'], 'seasons': 4, 'episodes_per_season': [20, 21, 17, 23], 'avg_episode_duration': 48, 'rating': 1.3, 'total_views': 88924, 'production_budget': 79333132}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S025', 'title': 'Digital Master Files', 'genre': ['Documentary'], 'seasons': 6, 'episodes_per_season': [20, 15, 19, 24, 12, 20], 'avg_episode_duration': 36, 'rating': 3.7, 'total_views': 181783, 'production_budget': 65631668}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S026', 'title': 'Analytics Chronicles', 'genre': ['Comedy'], 'seasons': 6, 'episodes_per_season': [13, 10, 18, 7, 14, 12], 'avg_episode_duration': 59, 'rating': 3.9, 'total_views': 159023, 'production_budget': 85960997}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S027', 'title': 'The Specialists', 'genre': ['Reality', 'Romance'], 'seasons': 8, 'episodes_per_season': [9, 22, 14, 22, 22, 16, 23, 9], 'avg_episode_duration': 50, 'rating': 3.6, 'total_views': 124627, 'production_budget': 17641045}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S028', 'title': 'The Experts', 'genre': ['Crime'], 'seasons': 7, 'episodes_per_season': [15, 11, 21, 9, 22, 10, 11], 'avg_episode_duration': 45, 'rating': 1.6, 'total_views': 111067, 'production_budget': 15293760}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S029', 'title': 'Digital Diaries', 'genre': ['Documentary'], 'seasons': 4, 'episodes_per_season': [21, 16, 23, 12], 'avg_episode_duration': 42, 'rating': 1.8, 'total_views': 81277, 'production_budget': 68389735}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S030', 'title': 'The Scientists', 'genre': ['Romance', 'Documentary'], 'seasons': 6, 'episodes_per_season': [21, 6, 6, 13, 20, 7], 'avg_episode_duration': 58, 'rating': 4.5, 'total_views': 268280, 'production_budget': 400393000}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S031', 'title': 'The Analysts', 'genre': ['Crime'], 'seasons': 1, 'episodes_per_season': [23], 'avg_episode_duration': 59, 'rating': 4.2, 'total_views': 328774, 'production_budget': 415835464}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S032', 'title': 'Tech Reports', 'genre': ['Sci-Fi', 'Reality'], 'seasons': 5, 'episodes_per_season': [12, 14, 17, 13, 19], 'avg_episode_duration': 37, 'rating': 1.7, 'total_views': 53516, 'production_budget': 95839378}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S033', 'title': 'The Experts', 'genre': ['Crime', 'Romance'], 'seasons': 7, 'episodes_per_season': [7, 11, 6, 8, 15, 20, 10], 'avg_episode_duration': 28, 'rating': 3.0, 'total_views': 186235, 'production_budget': 19617530}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S034', 'title': 'Tech Master Records', 'genre': ['Drama'], 'seasons': 1, 'episodes_per_season': [11], 'avg_episode_duration': 27, 'rating': 4.2, 'total_views': 250364, 'production_budget': 210303817}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S035', 'title': 'Cloud Chronicles', 'genre': ['Action'], 'seasons': 8, 'episodes_per_season': [11, 12, 7, 13, 7, 14, 9, 6], 'avg_episode_duration': 49, 'rating': 1.5, 'total_views': 24212, 'production_budget': 32588164}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S036', 'title': 'Intelligence Logs', 'genre': ['Comedy'], 'seasons': 4, 'episodes_per_season': [24, 24, 7, 8], 'avg_episode_duration': 35, 'rating': 2.2, 'total_views': 122031, 'production_budget': 36342177}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S037', 'title': 'The Experts', 'genre': ['Reality'], 'seasons': 5, 'episodes_per_season': [20, 8, 15, 24, 7], 'avg_episode_duration': 39, 'rating': 1.3, 'total_views': 177234, 'production_budget': 6067543}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S038', 'title': 'The Masters', 'genre': ['Action'], 'seasons': 3, 'episodes_per_season': [22, 13, 13], 'avg_episode_duration': 52, 'rating': 4.3, 'total_views': 91190, 'production_budget': 228468542}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S039', 'title': 'The Experts', 'genre': ['Comedy', 'Action'], 'seasons': 3, 'episodes_per_season': [9, 19, 20], 'avg_episode_duration': 52, 'rating': 3.2, 'total_views': 186734, 'production_budget': 55906418}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S040', 'title': 'Cyber Archives', 'genre': ['Drama', 'Action'], 'seasons': 1, 'episodes_per_season': [15], 'avg_episode_duration': 34, 'rating': 4.4, 'total_views': 269484, 'production_budget': 467178636}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S041', 'title': 'The Analysts', 'genre': ['Action', 'Romance'], 'seasons': 7, 'episodes_per_season': [16, 11, 6, 15, 14, 22, 9], 'avg_episode_duration': 34, 'rating': 2.0, 'total_views': 193868, 'production_budget': 8921678}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S042', 'title': 'The Analysts', 'genre': ['Action'], 'seasons': 3, 'episodes_per_season': [10, 8, 18], 'avg_episode_duration': 51, 'rating': 4.9, 'total_views': 364998, 'production_budget': 470357872}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S043', 'title': 'The Specialists', 'genre': ['Drama', 'Reality'], 'seasons': 5, 'episodes_per_season': [8, 21, 23, 14, 11], 'avg_episode_duration': 35, 'rating': 1.4, 'total_views': 36502, 'production_budget': 352436532}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S044', 'title': 'Cloud Reports', 'genre': ['Comedy'], 'seasons': 1, 'episodes_per_season': [13], 'avg_episode_duration': 46, 'rating': 3.4, 'total_views': 152609, 'production_budget': 78560006}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S045', 'title': 'The Scientists', 'genre': ['Crime'], 'seasons': 3, 'episodes_per_season': [20, 13, 24], 'avg_episode_duration': 24, 'rating': 2.7, 'total_views': 55899, 'production_budget': 57056031}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S046', 'title': 'Code Archives', 'genre': ['Sci-Fi', 'Drama'], 'seasons': 5, 'episodes_per_season': [17, 7, 11, 7, 20], 'avg_episode_duration': 21, 'rating': 2.2, 'total_views': 46760, 'production_budget': 292316186}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S047', 'title': 'Intelligence Stories', 'genre': ['Comedy', 'Reality'], 'seasons': 5, 'episodes_per_season': [11, 24, 7, 15, 13], 'avg_episode_duration': 58, 'rating': 2.6, 'total_views': 96207, 'production_budget': 37685089}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S048', 'title': 'The Experts', 'genre': ['Comedy', 'Documentary'], 'seasons': 8, 'episodes_per_season': [24, 21, 7, 24, 11, 11, 17, 9], 'avg_episode_duration': 29, 'rating': 1.5, 'total_views': 78818, 'production_budget': 30228151}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S049', 'title': 'Cyber Archives', 'genre': ['Reality'], 'seasons': 1, 'episodes_per_season': [18], 'avg_episode_duration': 37, 'rating': 3.1, 'total_views': 84555, 'production_budget': 58765760}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S050', 'title': 'The Experts', 'genre': ['Sci-Fi', 'Comedy'], 'seasons': 2, 'episodes_per_season': [14, 15], 'avg_episode_duration': 39, 'rating': 4.6, 'total_views': 111070, 'production_budget': 291245363}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S051', 'title': 'Cyber Diaries', 'genre': ['Action'], 'seasons': 1, 'episodes_per_season': [24], 'avg_episode_duration': 23, 'rating': 4.3, 'total_views': 68702, 'production_budget': 368102832}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S052', 'title': 'Intelligence Engineer Records', 'genre': ['Action', 'Crime'], 'seasons': 4, 'episodes_per_season': [17, 10, 19, 11], 'avg_episode_duration': 55, 'rating': 1.2, 'total_views': 101497, 'production_budget': 60906031}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S053', 'title': 'Analytics Archives', 'genre': ['Sci-Fi'], 'seasons': 3, 'episodes_per_season': [6, 14, 19], 'avg_episode_duration': 43, 'rating': 2.2, 'total_views': 49311, 'production_budget': 41543684}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S054', 'title': 'Intelligence Chronicles', 'genre': ['Romance', 'Action'], 'seasons': 4, 'episodes_per_season': [16, 10, 11, 24], 'avg_episode_duration': 55, 'rating': 2.0, 'total_views': 99736, 'production_budget': 14694325}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S055', 'title': 'The Scientists', 'genre': ['Crime'], 'seasons': 2, 'episodes_per_season': [15, 18], 'avg_episode_duration': 59, 'rating': 1.5, 'total_views': 139418, 'production_budget': 28230331}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S056', 'title': 'The Scientists', 'genre': ['Crime'], 'seasons': 7, 'episodes_per_season': [24, 13, 13, 15, 18, 15, 10], 'avg_episode_duration': 59, 'rating': 1.0, 'total_views': 173098, 'production_budget': 93373094}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S057', 'title': 'Cyber Chronicles', 'genre': ['Documentary', 'Comedy'], 'seasons': 5, 'episodes_per_season': [17, 11, 13, 9, 23], 'avg_episode_duration': 23, 'rating': 4.1, 'total_views': 241304, 'production_budget': 499744453}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S058', 'title': 'Data Logs', 'genre': ['Comedy', 'Romance'], 'seasons': 6, 'episodes_per_season': [11, 7, 20, 10, 13, 18], 'avg_episode_duration': 57, 'rating': 1.2, 'total_views': 99661, 'production_budget': 66154832}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S059', 'title': 'The Scientists', 'genre': ['Documentary'], 'seasons': 2, 'episodes_per_season': [6, 20], 'avg_episode_duration': 27, 'rating': 5.0, 'total_views': 27954, 'production_budget': 280522409}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S060', 'title': 'The Detectives', 'genre': ['Drama'], 'seasons': 7, 'episodes_per_season': [14, 16, 10, 21, 19, 8, 7], 'avg_episode_duration': 41, 'rating': 3.1, 'total_views': 11044, 'production_budget': 143304276}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S061', 'title': 'Tech Master Files', 'genre': ['Documentary'], 'seasons': 5, 'episodes_per_season': [20, 10, 19, 16, 15], 'avg_episode_duration': 50, 'rating': 2.9, 'total_views': 17393, 'production_budget': 99027997}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S062', 'title': 'Digital Chronicles', 'genre': ['Documentary', 'Drama'], 'seasons': 7, 'episodes_per_season': [13, 14, 6, 15, 16, 14, 12], 'avg_episode_duration': 54, 'rating': 2.9, 'total_views': 157616, 'production_budget': 127511414}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S063', 'title': 'Digital Archives', 'genre': ['Drama', 'Comedy'], 'seasons': 6, 'episodes_per_season': [22, 18, 21, 14, 12, 11], 'avg_episode_duration': 51, 'rating': 4.0, 'total_views': 60750, 'production_budget': 382523478}}
¡Se envío correctamente la siguiente información!:
 {'collection': 'series', 'data': {'_id': 'S064', 'title': 'The Masters', 'genre': ['Crime'], 'seasons': 6, 'episodes_per_season': [21, 24, 19, 16, 13, 13], 'avg_episode_duration': 37, 'rating': 3.6, 'total_views': 25420, 'production_budget': 35573482}}
¡Se envío correctamente la siguiente información!:

## Version C

In [82]:
import pandas as pd, json

In [84]:
# Variables

collection = "series"
file_path = '../data/content.json'

In [86]:
with open(file_path,'r') as file:
    json_data = json.load(file)[collection]
    df_json = pd.json_normalize(json_data)
columnas = list(df_json.columns)

In [88]:
def leer():
    with open(file_path,'r') as file:
        json_data = json.load(file)[collection]
        df_json = pd.json_normalize(json_data)
        return df_json

def convertir_columnas():
    df = leer()
    if collection == "movies":
        data_types = [str, str, object, int, int, float, int, int]
        for column in columnas:
            item = data_types.pop(0)
            df = df.astype({column: item})
        df_processed = df.to_json(orient='records')
        json_processed = json.loads(df_processed)
        return json_processed
    elif collection == "series":
        data_types = [str, str, object, int, object, int, float, int, int]
        for column in columnas:
            item = data_types.pop(0)
            df = df.astype({column: item})
        df_processed = df.to_json(orient='records')
        json_processed = json.loads(df_processed)
        return json_processed

def preparar():
    data = convertir_columnas()
    payload_body = {
    'collection': collection,
    'data': data
    }
    return payload_body    

def enviar():
    response = preparar()
    print(f"¡Se envío correctamente la siguiente información!:\n {response}")
        
if __name__ == '__main__':
    enviar()

¡Se envío correctamente la siguiente información!:

## Version D

In [8]:
import pandas as pd, json, time

In [9]:
# Variables

collection = "movies"
file_path = '../data/content.json'

In [102]:
with open(file_path,'r') as file:
    json_data = json.load(file)[collection]
i = 0
chunk = json_data[i:(i+50)]
clusters = []
def void():
    i = 0
    chunk = json_data[i:(i+51)]
    clusters = []
    for cluster in json_data:
        cluster = chunk
        if chunk == []:
            return clusters
        print(f"The chunk in this cluster is {cluster}")
        i = i+50
        chunk = json_data[(i+1):(i+51)]
        clusters.append(cluster)
void()

The chunk in this cluster is [{'_id': 'M001', 'title': 'Advanced World', 'genre': ['Sci-Fi', 'Horror', 'Drama'], 'duration_minutes': 179, 'release_year': 2020, 'rating': 3.5, 'views_count': 66721, 'production_budget': 220088717}, {'_id': 'M002', 'title': 'Neural Signal', 'genre': ['Animation', 'Horror'], 'duration_minutes': 146, 'release_year': 2021, 'rating': 2.8, 'views_count': 11128, 'production_budget': 23593231}, {'_id': 'M003', 'title': 'An Stream', 'genre': ['Action'], 'duration_minutes': 102, 'release_year': 2023, 'rating': 1.9, 'views_count': 75949, 'production_budget': 83166461}, {'_id': 'M004', 'title': 'Binary Journey', 'genre': ['Thriller', 'Documentary'], 'duration_minutes': 146, 'release_year': 2022, 'rating': 3.0, 'views_count': 85958, 'production_budget': 46298444}, {'_id': 'M005', 'title': 'Lost Data', 'genre': ['Horror', 'Romance'], 'duration_minutes': 169, 'release_year': 2022, 'rating': 4.7, 'views_count': 56808, 'production_budget': 67293750}, {'_id': 'M006', 'title': 'Ultimate Mystery', 'genre': ['Action', 'Animation', 'Horror'], 'duration_minutes': 157, 'release_year': 2024, 'rating': 1.1, 'views_count': 148876, 'production_budget': 234348717}, {'_id': 'M007', 'title': 'Code', 'genre': ['Comedy', 'Romance'], 'duration_minutes': 136, 'release_year': 2022, 'rating': 3.1, 'views_count': 9228, 'production_budget': 35028167}, {'_id': 'M008', 'title': 'Digital Protocol', 'genre': ['Documentary', 'Romance'], 'duration_minutes': 155, 'release_year': 2023, 'rating': 3.7, 'views_count': 125068, 'production_budget': 49545701}, {'_id': 'M009', 'title': 'Tale', 'genre': ['Drama', 'Horror'], 'duration_minutes': 90, 'release_year': 2023, 'rating': 4.4, 'views_count': 37911, 'production_budget': 146895476}, {'_id': 'M010', 'title': 'An Code 2', 'genre': ['Comedy', 'Romance', 'Action'], 'duration_minutes': 174, 'release_year': 2021, 'rating': 3.5, 'views_count': 78005, 'production_budget': 224671521}, {'_id': 'M011', 'title': 'Algorithm', 'genre': ['Drama', 'Animation', 'Horror'], 'duration_minutes': 81, 'release_year': 2023, 'rating': 2.7, 'views_count': 92634, 'production_budget': 20512281}, {'_id': 'M012', 'title': 'Quest 5', 'genre': ['Comedy'], 'duration_minutes': 104, 'release_year': 2023, 'rating': 2.4, 'views_count': 59155, 'production_budget': 36408859}, {'_id': 'M013', 'title': 'Mystery', 'genre': ['Documentary', 'Drama'], 'duration_minutes': 178, 'release_year': 2020, 'rating': 1.6, 'views_count': 61328, 'production_budget': 16064411}, {'_id': 'M014', 'title': 'Kingdom', 'genre': ['Thriller', 'Action'], 'duration_minutes': 122, 'release_year': 2021, 'rating': 4.2, 'views_count': 138918, 'production_budget': 202395249}, {'_id': 'M015', 'title': 'Quantum Code', 'genre': ['Animation', 'Documentary', 'Sci-Fi'], 'duration_minutes': 177, 'release_year': 2021, 'rating': 2.4, 'views_count': 13807, 'production_budget': 227198245}, {'_id': 'M016', 'title': 'A Database', 'genre': ['Drama', 'Documentary'], 'duration_minutes': 95, 'release_year': 2023, 'rating': 3.0, 'views_count': 81858, 'production_budget': 6729979}, {'_id': 'M017', 'title': 'Adventure', 'genre': ['Action', 'Documentary', 'Horror'], 'duration_minutes': 97, 'release_year': 2020, 'rating': 4.6, 'views_count': 132014, 'production_budget': 50839665}, {'_id': 'M018', 'title': 'Mystery', 'genre': ['Comedy', 'Action'], 'duration_minutes': 84, 'release_year': 2023, 'rating': 3.6, 'views_count': 81531, 'production_budget': 158431993}, {'_id': 'M019', 'title': 'Final Stream', 'genre': ['Action'], 'duration_minutes': 83, 'release_year': 2023, 'rating': 2.3, 'views_count': 144211, 'production_budget': 114952801}, {'_id': 'M020', 'title': 'Quest', 'genre': ['Thriller', 'Action', 'Drama'], 'duration_minutes': 108, 'release_year': 2022, 'rating': 3.1, 'views_count': 47873, 'production_budget': 250548961}, {'_id': 'M021', 'title': 'Tale', 'genre': ['Drama', 'Horror'], 'duration_minutes': 148, 'release_year': 2020, 'rating': 4.9, 'views_count': 168298, 'production_budget': 62478620}, {'_id': 'M022', 'title': 'Quantum System', 'genre': ['Horror'], 'duration_minutes': 147, 'release_year': 2023, 'rating': 4.7, 'views_count': 116580, 'production_budget': 73128204}, {'_id': 'M023', 'title': 'Smart Story', 'genre': ['Horror'], 'duration_minutes': 147, 'release_year': 2022, 'rating': 3.3, 'views_count': 36200, 'production_budget': 12509378}, {'_id': 'M024', 'title': 'First Mystery', 'genre': ['Horror'], 'duration_minutes': 159, 'release_year': 2020, 'rating': 4.2, 'views_count': 117924, 'production_budget': 146907831}, {'_id': 'M025', 'title': 'An Protocol', 'genre': ['Comedy'], 'duration_minutes': 162, 'release_year': 2020, 'rating': 4.0, 'views_count': 26519, 'production_budget': 49021276}, {'_id': 'M026', 'title': 'Lost Kingdom', 'genre': ['Documentary', 'Drama', 'Action'], 'duration_minutes': 163, 'release_year': 2024, 'rating': 2.6, 'views_count': 113230, 'production_budget': 90625130}, {'_id': 'M027', 'title': 'Quantum Story', 'genre': ['Thriller', 'Horror', 'Sci-Fi'], 'duration_minutes': 128, 'release_year': 2023, 'rating': 1.2, 'views_count': 19816, 'production_budget': 150283990}, {'_id': 'M028', 'title': 'Final Kingdom', 'genre': ['Comedy', 'Horror', 'Drama'], 'duration_minutes': 175, 'release_year': 2023, 'rating': 1.7, 'views_count': 87291, 'production_budget': 8816404}, {'_id': 'M029', 'title': 'System', 'genre': ['Documentary'], 'duration_minutes': 123, 'release_year': 2023, 'rating': 1.8, 'views_count': 27793, 'production_budget': 30738350}, {'_id': 'M030', 'title': 'Database 4', 'genre': ['Drama', 'Action'], 'duration_minutes': 145, 'release_year': 2020, 'rating': 1.3, 'views_count': 98063, 'production_budget': 100987742}, {'_id': 'M031', 'title': 'Empire', 'genre': ['Action', 'Animation', 'Drama'], 'duration_minutes': 104, 'release_year': 2020, 'rating': 4.9, 'views_count': 114316, 'production_budget': 184475405}, {'_id': 'M032', 'title': 'A Code', 'genre': ['Thriller', 'Action'], 'duration_minutes': 133, 'release_year': 2024, 'rating': 3.4, 'views_count': 83014, 'production_budget': 283617949}, {'_id': 'M033', 'title': 'Dark Stream', 'genre': ['Action', 'Animation'], 'duration_minutes': 119, 'release_year': 2023, 'rating': 2.9, 'views_count': 54865, 'production_budget': 193790052}, {'_id': 'M034', 'title': 'Stream', 'genre': ['Romance', 'Sci-Fi', 'Action'], 'duration_minutes': 151, 'release_year': 2020, 'rating': 4.9, 'views_count': 41348, 'production_budget': 122112109}, {'_id': 'M035', 'title': 'Lost System 5', 'genre': ['Thriller', 'Romance'], 'duration_minutes': 112, 'release_year': 2021, 'rating': 1.8, 'views_count': 64414, 'production_budget': 2127388}, {'_id': 'M036', 'title': 'Quest', 'genre': ['Romance', 'Animation'], 'duration_minutes': 100, 'release_year': 2020, 'rating': 2.9, 'views_count': 90335, 'production_budget': 12670028}, {'_id': 'M037', 'title': 'Quest', 'genre': ['Animation', 'Comedy', 'Documentary'], 'duration_minutes': 90, 'release_year': 2022, 'rating': 1.2, 'views_count': 13250, 'production_budget': 33987762}, {'_id': 'M038', 'title': 'Data', 'genre': ['Animation', 'Documentary'], 'duration_minutes': 161, 'release_year': 2021, 'rating': 3.6, 'views_count': 47672, 'production_budget': 15316213}, {'_id': 'M039', 'title': 'Lost Cloud', 'genre': ['Horror', 'Drama', 'Action'], 'duration_minutes': 103, 'release_year': 2020, 'rating': 2.8, 'views_count': 48310, 'production_budget': 202148811}, {'_id': 'M040', 'title': 'Quest', 'genre': ['Comedy', 'Documentary', 'Drama'], 'duration_minutes': 171, 'release_year': 2022, 'rating': 2.2, 'views_count': 52925, 'production_budget': 1600669}, {'_id': 'M041', 'title': 'Infinite Story', 'genre': ['Horror', 'Thriller'], 'duration_minutes': 117, 'release_year': 2021, 'rating': 4.2, 'views_count': 129104, 'production_budget': 186923029}, {'_id': 'M042', 'title': 'Advanced System 2', 'genre': ['Documentary'], 'duration_minutes': 163, 'release_year': 2020, 'rating': 3.3, 'views_count': 44583, 'production_budget': 42856949}, {'_id': 'M043', 'title': 'Hidden Empire', 'genre': ['Horror'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 4.1, 'views_count': 290064, 'production_budget': 128140036}, {'_id': 'M044', 'title': 'Cyber Cloud 4', 'genre': ['Animation', 'Thriller'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 3.3, 'views_count': 8992, 'production_budget': 8120314}, {'_id': 'M045', 'title': 'First Database', 'genre': ['Animation', 'Action'], 'duration_minutes': 123, 'release_year': 2023, 'rating': 3.1, 'views_count': 115282, 'production_budget': 182644208}, {'_id': 'M046', 'title': 'Binary Signal', 'genre': ['Animation', 'Documentary', 'Thriller'], 'duration_minutes': 147, 'release_year': 2023, 'rating': 1.9, 'views_count': 18247, 'production_budget': 24000248}, {'_id': 'M047', 'title': 'Story', 'genre': ['Drama'], 'duration_minutes': 120, 'release_year': 2023, 'rating': 3.3, 'views_count': 5974, 'production_budget': 18448764}, {'_id': 'M048', 'title': 'Tale', 'genre': ['Horror', 'Romance', 'Documentary'], 'duration_minutes': 104, 'release_year': 2021, 'rating': 4.9, 'views_count': 178486, 'production_budget': 59289648}, {'_id': 'M049', 'title': 'Neural Cloud 2', 'genre': ['Drama', 'Sci-Fi', 'Action'], 'duration_minutes': 126, 'release_year': 2020, 'rating': 3.7, 'views_count': 33051, 'production_budget': 135871052}, {'_id': 'M050', 'title': 'Infinite Protocol', 'genre': ['Thriller', 'Documentary'], 'duration_minutes': 96, 'release_year': 2021, 'rating': 2.0, 'views_count': 53173, 'production_budget': 39370044}, {'_id': 'M051', 'title': 'A Algorithm', 'genre': ['Animation'], 'duration_minutes': 155, 'release_year': 2022, 'rating': 4.8, 'views_count': 136410, 'production_budget': 106311259}]
The chunk in this cluster is [{'_id': 'M052', 'title': 'Adventure', 'genre': ['Horror', 'Thriller', 'Sci-Fi'], 'duration_minutes': 120, 'release_year': 2021, 'rating': 3.9, 'views_count': 94063, 'production_budget': 193008798}, {'_id': 'M053', 'title': 'Infinite Empire', 'genre': ['Action'], 'duration_minutes': 162, 'release_year': 2022, 'rating': 1.9, 'views_count': 50863, 'production_budget': 296179703}, {'_id': 'M054', 'title': 'Binary Stream', 'genre': ['Action', 'Animation', 'Documentary'], 'duration_minutes': 98, 'release_year': 2021, 'rating': 4.6, 'views_count': 17832, 'production_budget': 122289319}, {'_id': 'M055', 'title': 'Infinite Adventure', 'genre': ['Thriller'], 'duration_minutes': 142, 'release_year': 2023, 'rating': 3.6, 'views_count': 121651, 'production_budget': 37909361}, {'_id': 'M056', 'title': 'Binary Journey', 'genre': ['Thriller', 'Action'], 'duration_minutes': 88, 'release_year': 2023, 'rating': 3.6, 'views_count': 105627, 'production_budget': 140493022}, {'_id': 'M057', 'title': 'Journey', 'genre': ['Drama', 'Sci-Fi'], 'duration_minutes': 149, 'release_year': 2022, 'rating': 1.9, 'views_count': 38409, 'production_budget': 213938522}, {'_id': 'M058', 'title': 'Last Quest', 'genre': ['Documentary', 'Animation', 'Romance'], 'duration_minutes': 173, 'release_year': 2020, 'rating': 3.6, 'views_count': 53146, 'production_budget': 20440772}, {'_id': 'M059', 'title': 'System', 'genre': ['Sci-Fi', 'Thriller', 'Drama'], 'duration_minutes': 146, 'release_year': 2020, 'rating': 1.5, 'views_count': 63578, 'production_budget': 80650718}, {'_id': 'M060', 'title': 'Dark Kingdom', 'genre': ['Thriller', 'Sci-Fi'], 'duration_minutes': 122, 'release_year': 2020, 'rating': 4.9, 'views_count': 196906, 'production_budget': 107714280}, {'_id': 'M061', 'title': 'An Cloud', 'genre': ['Drama', 'Comedy', 'Action'], 'duration_minutes': 99, 'release_year': 2022, 'rating': 4.6, 'views_count': 58038, 'production_budget': 181262622}, {'_id': 'M062', 'title': 'Secret Empire', 'genre': ['Horror'], 'duration_minutes': 136, 'release_year': 2024, 'rating': 1.1, 'views_count': 113496, 'production_budget': 45559979}, {'_id': 'M063', 'title': 'Neural Cloud', 'genre': ['Sci-Fi', 'Drama'], 'duration_minutes': 104, 'release_year': 2024, 'rating': 4.5, 'views_count': 241308, 'production_budget': 52788131}, {'_id': 'M064', 'title': 'Virtual Adventure', 'genre': ['Drama', 'Action'], 'duration_minutes': 113, 'release_year': 2024, 'rating': 4.4, 'views_count': 99105, 'production_budget': 99191442}, {'_id': 'M065', 'title': 'Final Story', 'genre': ['Documentary', 'Romance', 'Sci-Fi'], 'duration_minutes': 102, 'release_year': 2024, 'rating': 1.9, 'views_count': 107506, 'production_budget': 92334091}, {'_id': 'M066', 'title': 'Last World', 'genre': ['Animation'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 4.1, 'views_count': 139206, 'production_budget': 232940727}, {'_id': 'M067', 'title': 'Smart World', 'genre': ['Documentary', 'Romance', 'Sci-Fi'], 'duration_minutes': 126, 'release_year': 2023, 'rating': 4.0, 'views_count': 125397, 'production_budget': 233435578}, {'_id': 'M068', 'title': 'Protocol', 'genre': ['Comedy', 'Thriller', 'Horror'], 'duration_minutes': 169, 'release_year': 2024, 'rating': 4.2, 'views_count': 110097, 'production_budget': 100149438}, {'_id': 'M069', 'title': 'Last World', 'genre': ['Horror'], 'duration_minutes': 119, 'release_year': 2022, 'rating': 4.0, 'views_count': 12355, 'production_budget': 39301506}, {'_id': 'M070', 'title': 'Lost Adventure', 'genre': ['Drama', 'Sci-Fi'], 'duration_minutes': 171, 'release_year': 2020, 'rating': 1.7, 'views_count': 5512, 'production_budget': 218689270}, {'_id': 'M071', 'title': 'Cyber Tale', 'genre': ['Sci-Fi', 'Drama', 'Comedy'], 'duration_minutes': 102, 'release_year': 2023, 'rating': 4.3, 'views_count': 292824, 'production_budget': 139504878}, {'_id': 'M072', 'title': 'Secret Signal', 'genre': ['Romance'], 'duration_minutes': 125, 'release_year': 2022, 'rating': 1.6, 'views_count': 60180, 'production_budget': 8844926}, {'_id': 'M073', 'title': 'System', 'genre': ['Documentary', 'Animation', 'Action'], 'duration_minutes': 141, 'release_year': 2021, 'rating': 1.3, 'views_count': 12675, 'production_budget': 167251523}, {'_id': 'M074', 'title': 'Digital Database', 'genre': ['Comedy'], 'duration_minutes': 146, 'release_year': 2022, 'rating': 3.2, 'views_count': 8998, 'production_budget': 29227591}, {'_id': 'M075', 'title': 'Neural Journey', 'genre': ['Sci-Fi', 'Thriller', 'Romance'], 'duration_minutes': 125, 'release_year': 2020, 'rating': 4.2, 'views_count': 84468, 'production_budget': 296040480}, {'_id': 'M076', 'title': 'The Journey', 'genre': ['Thriller', 'Documentary', 'Animation'], 'duration_minutes': 166, 'release_year': 2020, 'rating': 2.4, 'views_count': 78189, 'production_budget': 27396354}, {'_id': 'M077', 'title': 'Signal', 'genre': ['Romance'], 'duration_minutes': 101, 'release_year': 2021, 'rating': 4.5, 'views_count': 97638, 'production_budget': 203590741}, {'_id': 'M078', 'title': 'Algorithm', 'genre': ['Comedy', 'Romance', 'Documentary'], 'duration_minutes': 155, 'release_year': 2024, 'rating': 1.6, 'views_count': 28957, 'production_budget': 13524987}, {'_id': 'M079', 'title': 'Secret Algorithm', 'genre': ['Thriller'], 'duration_minutes': 156, 'release_year': 2022, 'rating': 3.8, 'views_count': 44993, 'production_budget': 46138210}, {'_id': 'M080', 'title': 'Digital Empire', 'genre': ['Comedy'], 'duration_minutes': 99, 'release_year': 2022, 'rating': 3.5, 'views_count': 51624, 'production_budget': 49787105}, {'_id': 'M081', 'title': 'A Empire', 'genre': ['Thriller'], 'duration_minutes': 158, 'release_year': 2023, 'rating': 3.2, 'views_count': 20857, 'production_budget': 21843745}, {'_id': 'M082', 'title': 'Protocol', 'genre': ['Romance', 'Action', 'Comedy'], 'duration_minutes': 135, 'release_year': 2023, 'rating': 4.0, 'views_count': 106275, 'production_budget': 182661326}, {'_id': 'M083', 'title': 'Final World', 'genre': ['Horror'], 'duration_minutes': 116, 'release_year': 2023, 'rating': 1.1, 'views_count': 147540, 'production_budget': 9691644}, {'_id': 'M084', 'title': 'The Matrix', 'genre': ['Drama', 'Comedy'], 'duration_minutes': 141, 'release_year': 2021, 'rating': 2.2, 'views_count': 40998, 'production_budget': 49636072}, {'_id': 'M085', 'title': 'Lost Adventure', 'genre': ['Action', 'Romance'], 'duration_minutes': 150, 'release_year': 2022, 'rating': 4.4, 'views_count': 185972, 'production_budget': 272623780}, {'_id': 'M086', 'title': 'Data', 'genre': ['Thriller', 'Horror', 'Animation'], 'duration_minutes': 130, 'release_year': 2021, 'rating': 2.3, 'views_count': 41342, 'production_budget': 25908762}, {'_id': 'M087', 'title': 'A Data', 'genre': ['Action', 'Romance', 'Drama'], 'duration_minutes': 139, 'release_year': 2020, 'rating': 2.7, 'views_count': 41100, 'production_budget': 251619945}, {'_id': 'M088', 'title': 'Data', 'genre': ['Romance'], 'duration_minutes': 146, 'release_year': 2023, 'rating': 1.2, 'views_count': 2689, 'production_budget': 41797064}, {'_id': 'M089', 'title': 'Hidden Data', 'genre': ['Horror', 'Sci-Fi', 'Romance'], 'duration_minutes': 107, 'release_year': 2021, 'rating': 3.0, 'views_count': 48176, 'production_budget': 283777035}, {'_id': 'M090', 'title': 'Network', 'genre': ['Comedy', 'Animation'], 'duration_minutes': 86, 'release_year': 2020, 'rating': 2.6, 'views_count': 38966, 'production_budget': 41347239}, {'_id': 'M091', 'title': 'Empire', 'genre': ['Animation', 'Romance'], 'duration_minutes': 122, 'release_year': 2022, 'rating': 2.5, 'views_count': 48892, 'production_budget': 10832696}, {'_id': 'M092', 'title': 'Infinite Code', 'genre': ['Comedy', 'Horror'], 'duration_minutes': 145, 'release_year': 2021, 'rating': 2.1, 'views_count': 56151, 'production_budget': 16160068}, {'_id': 'M093', 'title': 'Digital Code', 'genre': ['Horror', 'Drama'], 'duration_minutes': 87, 'release_year': 2024, 'rating': 3.8, 'views_count': 97083, 'production_budget': 9974518}, {'_id': 'M094', 'title': 'Matrix', 'genre': ['Action', 'Animation'], 'duration_minutes': 173, 'release_year': 2020, 'rating': 1.2, 'views_count': 48295, 'production_budget': 250209902}, {'_id': 'M095', 'title': 'Digital Tale', 'genre': ['Documentary', 'Comedy', 'Romance'], 'duration_minutes': 131, 'release_year': 2024, 'rating': 3.8, 'views_count': 104163, 'production_budget': 27080387}, {'_id': 'M096', 'title': 'Final Mystery 5', 'genre': ['Romance', 'Comedy', 'Action'], 'duration_minutes': 85, 'release_year': 2022, 'rating': 2.0, 'views_count': 80921, 'production_budget': 134466599}, {'_id': 'M097', 'title': 'Dark Stream', 'genre': ['Horror', 'Comedy'], 'duration_minutes': 131, 'release_year': 2020, 'rating': 4.9, 'views_count': 152164, 'production_budget': 65465290}, {'_id': 'M098', 'title': 'Digital Data', 'genre': ['Horror', 'Thriller', 'Romance'], 'duration_minutes': 142, 'release_year': 2022, 'rating': 2.6, 'views_count': 13908, 'production_budget': 41421645}, {'_id': 'M099', 'title': 'Algorithm', 'genre': ['Animation', 'Romance', 'Action'], 'duration_minutes': 159, 'release_year': 2022, 'rating': 2.3, 'views_count': 53649, 'production_budget': 195742202}, {'_id': 'M100', 'title': 'Mystery', 'genre': ['Animation', 'Drama', 'Comedy'], 'duration_minutes': 145, 'release_year': 2022, 'rating': 2.5, 'views_count': 85093, 'production_budget': 1818805}, {'_id': 'M101', 'title': 'System', 'genre': ['Horror', 'Sci-Fi', 'Drama'], 'duration_minutes': 152, 'release_year': 2024, 'rating': 2.9, 'views_count': 27931, 'production_budget': 122138266}]

[[{'_id': 'M001',
   'title': 'Advanced World',
   'genre': ['Sci-Fi', 'Horror', 'Drama'],
   'duration_minutes': 179,
   'release_year': 2020,
   'rating': 3.5,
   'views_count': 66721,
   'production_budget': 220088717},
  {'_id': 'M002',
   'title': 'Neural Signal',
   'genre': ['Animation', 'Horror'],
   'duration_minutes': 146,
   'release_year': 2021,
   'rating': 2.8,
   'views_count': 11128,
   'production_budget': 23593231},
  {'_id': 'M003',
   'title': 'An Stream',
   'genre': ['Action'],
   'duration_minutes': 102,
   'release_year': 2023,
   'rating': 1.9,
   'views_count': 75949,
   'production_budget': 83166461},
  {'_id': 'M004',
   'title': 'Binary Journey',
   'genre': ['Thriller', 'Documentary'],
   'duration_minutes': 146,
   'release_year': 2022,
   'rating': 3.0,
   'views_count': 85958,
   'production_budget': 46298444},
  {'_id': 'M005',
   'title': 'Lost Data',
   'genre': ['Horror', 'Romance'],
   'duration_minutes': 169,
   'release_year': 2022,
   'rating': 4.7,
   'views_count': 56808,
   'production_budget': 67293750},
  {'_id': 'M006',
   'title': 'Ultimate Mystery',
   'genre': ['Action', 'Animation', 'Horror'],
   'duration_minutes': 157,
   'release_year': 2024,
   'rating': 1.1,
   'views_count': 148876,
   'production_budget': 234348717},
  {'_id': 'M007',
   'title': 'Code',
   'genre': ['Comedy', 'Romance'],
   'duration_minutes': 136,
   'release_year': 2022,
   'rating': 3.1,
   'views_count': 9228,
   'production_budget': 35028167},
  {'_id': 'M008',
   'title': 'Digital Protocol',
   'genre': ['Documentary', 'Romance'],
   'duration_minutes': 155,
   'release_year': 2023,
   'rating': 3.7,
   'views_count': 125068,
   'production_budget': 49545701},
  {'_id': 'M009',
   'title': 'Tale',
   'genre': ['Drama', 'Horror'],
   'duration_minutes': 90,
   'release_year': 2023,
   'rating': 4.4,
   'views_count': 37911,
   'production_budget': 146895476},
  {'_id': 'M010',
   'title': 'An Code 2',
   'genre': ['Comedy', 'Romance', 'Action'],
   'duration_minutes': 174,
   'release_year': 2021,
   'rating': 3.5,
   'views_count': 78005,
   'production_budget': 224671521},
  {'_id': 'M011',
   'title': 'Algorithm',
   'genre': ['Drama', 'Animation', 'Horror'],
   'duration_minutes': 81,
   'release_year': 2023,
   'rating': 2.7,
   'views_count': 92634,
   'production_budget': 20512281},
  {'_id': 'M012',
   'title': 'Quest 5',
   'genre': ['Comedy'],
   'duration_minutes': 104,
   'release_year': 2023,
   'rating': 2.4,
   'views_count': 59155,
   'production_budget': 36408859},
  {'_id': 'M013',
   'title': 'Mystery',
   'genre': ['Documentary', 'Drama'],
   'duration_minutes': 178,
   'release_year': 2020,
   'rating': 1.6,
   'views_count': 61328,
   'production_budget': 16064411},
  {'_id': 'M014',
   'title': 'Kingdom',
   'genre': ['Thriller', 'Action'],
   'duration_minutes': 122,
   'release_year': 2021,
   'rating': 4.2,
   'views_count': 138918,
   'production_budget': 202395249},
  {'_id': 'M015',
   'title': 'Quantum Code',
   'genre': ['Animation', 'Documentary', 'Sci-Fi'],
   'duration_minutes': 177,
   'release_year': 2021,
   'rating': 2.4,
   'views_count': 13807,
   'production_budget': 227198245},
  {'_id': 'M016',
   'title': 'A Database',
   'genre': ['Drama', 'Documentary'],
   'duration_minutes': 95,
   'release_year': 2023,
   'rating': 3.0,
   'views_count': 81858,
   'production_budget': 6729979},
  {'_id': 'M017',
   'title': 'Adventure',
   'genre': ['Action', 'Documentary', 'Horror'],
   'duration_minutes': 97,
   'release_year': 2020,
   'rating': 4.6,
   'views_count': 132014,
   'production_budget': 50839665},
  {'_id': 'M018',
   'title': 'Mystery',
   'genre': ['Comedy', 'Action'],
   'duration_minutes': 84,
   'release_year': 2023,
   'rating': 3.6,
   'views_count': 81531,
   'production_budget': 158431993},
  {'_id': 'M019',
   'title': 'Final Stream',
   'genre': ['Action'],
   'duration_minutes': 83,
   'release_year': 2023,
   'rating': 2.3,
   'views_count': 144211,
   'production_budget': 114952801},
  {'_id': 'M020',
   'title': 'Quest',
   'genre': ['Thriller', 'Action', 'Drama'],
   'duration_minutes': 108,
   'release_year': 2022,
   'rating': 3.1,
   'views_count': 47873,
   'production_budget': 250548961},
  {'_id': 'M021',
   'title': 'Tale',
   'genre': ['Drama', 'Horror'],
   'duration_minutes': 148,
   'release_year': 2020,
   'rating': 4.9,
   'views_count': 168298,
   'production_budget': 62478620},
  {'_id': 'M022',
   'title': 'Quantum System',
   'genre': ['Horror'],
   'duration_minutes': 147,
   'release_year': 2023,
   'rating': 4.7,
   'views_count': 116580,
   'production_budget': 73128204},
  {'_id': 'M023',
   'title': 'Smart Story',
   'genre': ['Horror'],
   'duration_minutes': 147,
   'release_year': 2022,
   'rating': 3.3,
   'views_count': 36200,
   'production_budget': 12509378},
  {'_id': 'M024',
   'title': 'First Mystery',
   'genre': ['Horror'],
   'duration_minutes': 159,
   'release_year': 2020,
   'rating': 4.2,
   'views_count': 117924,
   'production_budget': 146907831},
  {'_id': 'M025',
   'title': 'An Protocol',
   'genre': ['Comedy'],
   'duration_minutes': 162,
   'release_year': 2020,
   'rating': 4.0,
   'views_count': 26519,
   'production_budget': 49021276},
  {'_id': 'M026',
   'title': 'Lost Kingdom',
   'genre': ['Documentary', 'Drama', 'Action'],
   'duration_minutes': 163,
   'release_year': 2024,
   'rating': 2.6,
   'views_count': 113230,
   'production_budget': 90625130},
  {'_id': 'M027',
   'title': 'Quantum Story',
   'genre': ['Thriller', 'Horror', 'Sci-Fi'],
   'duration_minutes': 128,
   'release_year': 2023,
   'rating': 1.2,
   'views_count': 19816,
   'production_budget': 150283990},
  {'_id': 'M028',
   'title': 'Final Kingdom',
   'genre': ['Comedy', 'Horror', 'Drama'],
   'duration_minutes': 175,
   'release_year': 2023,
   'rating': 1.7,
   'views_count': 87291,
   'production_budget': 8816404},
  {'_id': 'M029',
   'title': 'System',
   'genre': ['Documentary'],
   'duration_minutes': 123,
   'release_year': 2023,
   'rating': 1.8,
   'views_count': 27793,
   'production_budget': 30738350},
  {'_id': 'M030',
   'title': 'Database 4',
   'genre': ['Drama', 'Action'],
   'duration_minutes': 145,
   'release_year': 2020,
   'rating': 1.3,
   'views_count': 98063,
   'production_budget': 100987742},
  {'_id': 'M031',
   'title': 'Empire',
   'genre': ['Action', 'Animation', 'Drama'],
   'duration_minutes': 104,
   'release_year': 2020,
   'rating': 4.9,
   'views_count': 114316,
   'production_budget': 184475405},
  {'_id': 'M032',
   'title': 'A Code',
   'genre': ['Thriller', 'Action'],
   'duration_minutes': 133,
   'release_year': 2024,
   'rating': 3.4,
   'views_count': 83014,
   'production_budget': 283617949},
  {'_id': 'M033',
   'title': 'Dark Stream',
   'genre': ['Action', 'Animation'],
   'duration_minutes': 119,
   'release_year': 2023,
   'rating': 2.9,
   'views_count': 54865,
   'production_budget': 193790052},
  {'_id': 'M034',
   'title': 'Stream',
   'genre': ['Romance', 'Sci-Fi', 'Action'],
   'duration_minutes': 151,
   'release_year': 2020,
   'rating': 4.9,
   'views_count': 41348,
   'production_budget': 122112109},
  {'_id': 'M035',
   'title': 'Lost System 5',
   'genre': ['Thriller', 'Romance'],
   'duration_minutes': 112,
   'release_year': 2021,
   'rating': 1.8,
   'views_count': 64414,
   'production_budget': 2127388},
  {'_id': 'M036',
   'title': 'Quest',
   'genre': ['Romance', 'Animation'],
   'duration_minutes': 100,
   'release_year': 2020,
   'rating': 2.9,
   'views_count': 90335,
   'production_budget': 12670028},
  {'_id': 'M037',
   'title': 'Quest',
   'genre': ['Animation', 'Comedy', 'Documentary'],
   'duration_minutes': 90,
   'release_year': 2022,
   'rating': 1.2,
   'views_count': 13250,
   'production_budget': 33987762},
  {'_id': 'M038',
   'title': 'Data',
   'genre': ['Animation', 'Documentary'],
   'duration_minutes': 161,
   'release_year': 2021,
   'rating': 3.6,
   'views_count': 47672,
   'production_budget': 15316213},
  {'_id': 'M039',
   'title': 'Lost Cloud',
   'genre': ['Horror', 'Drama', 'Action'],
   'duration_minutes': 103,
   'release_year': 2020,
   'rating': 2.8,
   'views_count': 48310,
   'production_budget': 202148811},
  {'_id': 'M040',
   'title': 'Quest',
   'genre': ['Comedy', 'Documentary', 'Drama'],
   'duration_minutes': 171,
   'release_year': 2022,
   'rating': 2.2,
   'views_count': 52925,
   'production_budget': 1600669},
  {'_id': 'M041',
   'title': 'Infinite Story',
   'genre': ['Horror', 'Thriller'],
   'duration_minutes': 117,
   'release_year': 2021,
   'rating': 4.2,
   'views_count': 129104,
   'production_budget': 186923029},
  {'_id': 'M042',
   'title': 'Advanced System 2',
   'genre': ['Documentary'],
   'duration_minutes': 163,
   'release_year': 2020,
   'rating': 3.3,
   'views_count': 44583,
   'production_budget': 42856949},
  {'_id': 'M043',
   'title': 'Hidden Empire',
   'genre': ['Horror'],
   'duration_minutes': 134,
   'release_year': 2024,
   'rating': 4.1,
   'views_count': 290064,
   'production_budget': 128140036},
  {'_id': 'M044',
   'title': 'Cyber Cloud 4',
   'genre': ['Animation', 'Thriller'],
   'duration_minutes': 134,
   'release_year': 2024,
   'rating': 3.3,
   'views_count': 8992,
   'production_budget': 8120314},
  {'_id': 'M045',
   'title': 'First Database',
   'genre': ['Animation', 'Action'],
   'duration_minutes': 123,
   'release_year': 2023,
   'rating': 3.1,
   'views_count': 115282,
   'production_budget': 182644208},
  {'_id': 'M046',
   'title': 'Binary Signal',
   'genre': ['Animation', 'Documentary', 'Thriller'],
   'duration_minutes': 147,
   'release_year': 2023,
   'rating': 1.9,
   'views_count': 18247,
   'production_budget': 24000248},
  {'_id': 'M047',
   'title': 'Story',
   'genre': ['Drama'],
   'duration_minutes': 120,
   'release_year': 2023,
   'rating': 3.3,
   'views_count': 5974,
   'production_budget': 18448764},
  {'_id': 'M048',
   'title': 'Tale',
   'genre': ['Horror', 'Romance', 'Documentary'],
   'duration_minutes': 104,
   'release_year': 2021,
   'rating': 4.9,
   'views_count': 178486,
   'production_budget': 59289648},
  {'_id': 'M049',
   'title': 'Neural Cloud 2',
   'genre': ['Drama', 'Sci-Fi', 'Action'],
   'duration_minutes': 126,
   'release_year': 2020,
   'rating': 3.7,
   'views_count': 33051,
   'production_budget': 135871052},
  {'_id': 'M050',
   'title': 'Infinite Protocol',
   'genre': ['Thriller', 'Documentary'],
   'duration_minutes': 96,
   'release_year': 2021,
   'rating': 2.0,
   'views_count': 53173,
   'production_budget': 39370044},
  {'_id': 'M051',
   'title': 'A Algorithm',
   'genre': ['Animation'],
   'duration_minutes': 155,
   'release_year': 2022,
   'rating': 4.8,
   'views_count': 136410,
   'production_budget': 106311259}],
 [{'_id': 'M052',
   'title': 'Adventure',
   'genre': ['Horror', 'Thriller', 'Sci-Fi'],
   'duration_minutes': 120,
   'release_year': 2021,
   'rating': 3.9,
   'views_count': 94063,
   'production_budget': 193008798},
  {'_id': 'M053',
   'title': 'Infinite Empire',
   'genre': ['Action'],
   'duration_minutes': 162,
   'release_year': 2022,
   'rating': 1.9,
   'views_count': 50863,
   'production_budget': 296179703},
  {'_id': 'M054',
   'title': 'Binary Stream',
   'genre': ['Action', 'Animation', 'Documentary'],
   'duration_minutes': 98,
   'release_year': 2021,
   'rating': 4.6,
   'views_count': 17832,
   'production_budget': 122289319},
  {'_id': 'M055',
   'title': 'Infinite Adventure',
   'genre': ['Thriller'],
   'duration_minutes': 142,
   'release_year': 2023,
   'rating': 3.6,
   'views_count': 121651,
   'production_budget': 37909361},
  {'_id': 'M056',
   'title': 'Binary Journey',
   'genre': ['Thriller', 'Action'],
   'duration_minutes': 88,
   'release_year': 2023,
   'rating': 3.6,
   'views_count': 105627,
   'production_budget': 140493022},
  {'_id': 'M057',
   'title': 'Journey',
   'genre': ['Drama', 'Sci-Fi'],
   'duration_minutes': 149,
   'release_year': 2022,
   'rating': 1.9,
   'views_count': 38409,
   'production_budget': 213938522},
  {'_id': 'M058',
   'title': 'Last Quest',
   'genre': ['Documentary', 'Animation', 'Romance'],
   'duration_minutes': 173,
   'release_year': 2020,
   'rating': 3.6,
   'views_count': 53146,
   'production_budget': 20440772},
  {'_id': 'M059',
   'title': 'System',
   'genre': ['Sci-Fi', 'Thriller', 'Drama'],
   'duration_minutes': 146,
   'release_year': 2020,
   'rating': 1.5,
   'views_count': 63578,
   'production_budget': 80650718},
  {'_id': 'M060',
   'title': 'Dark Kingdom',
   'genre': ['Thriller', 'Sci-Fi'],
   'duration_minutes': 122,
   'release_year': 2020,
   'rating': 4.9,
   'views_count': 196906,
   'production_budget': 107714280},
  {'_id': 'M061',
   'title': 'An Cloud',
   'genre': ['Drama', 'Comedy', 'Action'],
   'duration_minutes': 99,
   'release_year': 2022,
   'rating': 4.6,
   'views_count': 58038,
   'production_budget': 181262622},
  {'_id': 'M062',
   'title': 'Secret Empire',
   'genre': ['Horror'],
   'duration_minutes': 136,
   'release_year': 2024,
   'rating': 1.1,
   'views_count': 113496,
   'production_budget': 45559979},
  {'_id': 'M063',
   'title': 'Neural Cloud',
   'genre': ['Sci-Fi', 'Drama'],
   'duration_minutes': 104,
   'release_year': 2024,
   'rating': 4.5,
   'views_count': 241308,
   'production_budget': 52788131},
  {'_id': 'M064',
   'title': 'Virtual Adventure',
   'genre': ['Drama', 'Action'],
   'duration_minutes': 113,
   'release_year': 2024,
   'rating': 4.4,
   'views_count': 99105,
   'production_budget': 99191442},
  {'_id': 'M065',
   'title': 'Final Story',
   'genre': ['Documentary', 'Romance', 'Sci-Fi'],
   'duration_minutes': 102,
   'release_year': 2024,
   'rating': 1.9,
   'views_count': 107506,
   'production_budget': 92334091},
  {'_id': 'M066',
   'title': 'Last World',
   'genre': ['Animation'],
   'duration_minutes': 134,
   'release_year': 2024,
   'rating': 4.1,
   'views_count': 139206,
   'production_budget': 232940727},
  {'_id': 'M067',
   'title': 'Smart World',
   'genre': ['Documentary', 'Romance', 'Sci-Fi'],
   'duration_minutes': 126,
   'release_year': 2023,
   'rating': 4.0,
   'views_count': 125397,
   'production_budget': 233435578},
  {'_id': 'M068',
   'title': 'Protocol',
   'genre': ['Comedy', 'Thriller', 'Horror'],
   'duration_minutes': 169,
   'release_year': 2024,
   'rating': 4.2,
   'views_count': 110097,
   'production_budget': 100149438},
  {'_id': 'M069',
   'title': 'Last World',
   'genre': ['Horror'],
   'duration_minutes': 119,
   'release_year': 2022,
   'rating': 4.0,
   'views_count': 12355,
   'production_budget': 39301506},
  {'_id': 'M070',
   'title': 'Lost Adventure',
   'genre': ['Drama', 'Sci-Fi'],
   'duration_minutes': 171,
   'release_year': 2020,
   'rating': 1.7,
   'views_count': 5512,
   'production_budget': 218689270},
  {'_id': 'M071',
   'title': 'Cyber Tale',
   'genre': ['Sci-Fi', 'Drama', 'Comedy'],
   'duration_minutes': 102,
   'release_year': 2023,
   'rating': 4.3,
   'views_count': 292824,
   'production_budget': 139504878},
  {'_id': 'M072',
   'title': 'Secret Signal',
   'genre': ['Romance'],
   'duration_minutes': 125,
   'release_year': 2022,
   'rating': 1.6,
   'views_count': 60180,
   'production_budget': 8844926},
  {'_id': 'M073',
   'title': 'System',
   'genre': ['Documentary', 'Animation', 'Action'],
   'duration_minutes': 141,
   'release_year': 2021,
   'rating': 1.3,
   'views_count': 12675,
   'production_budget': 167251523},
  {'_id': 'M074',
   'title': 'Digital Database',
   'genre': ['Comedy'],
   'duration_minutes': 146,
   'release_year': 2022,
   'rating': 3.2,
   'views_count': 8998,
   'production_budget': 29227591},
  {'_id': 'M075',
   'title': 'Neural Journey',
   'genre': ['Sci-Fi', 'Thriller', 'Romance'],
   'duration_minutes': 125,
   'release_year': 2020,
   'rating': 4.2,
   'views_count': 84468,
   'production_budget': 296040480},
  {'_id': 'M076',
   'title': 'The Journey',
   'genre': ['Thriller', 'Documentary', 'Animation'],
   'duration_minutes': 166,
   'release_year': 2020,
   'rating': 2.4,
   'views_count': 78189,
   'production_budget': 27396354},
  {'_id': 'M077',
   'title': 'Signal',
   'genre': ['Romance'],
   'duration_minutes': 101,
   'release_year': 2021,
   'rating': 4.5,
   'views_count': 97638,
   'production_budget': 203590741},
  {'_id': 'M078',
   'title': 'Algorithm',
   'genre': ['Comedy', 'Romance', 'Documentary'],
   'duration_minutes': 155,
   'release_year': 2024,
   'rating': 1.6,
   'views_count': 28957,
   'production_budget': 13524987},
  {'_id': 'M079',
   'title': 'Secret Algorithm',
   'genre': ['Thriller'],
   'duration_minutes': 156,
   'release_year': 2022,
   'rating': 3.8,
   'views_count': 44993,
   'production_budget': 46138210},
  {'_id': 'M080',
   'title': 'Digital Empire',
   'genre': ['Comedy'],
   'duration_minutes': 99,
   'release_year': 2022,
   'rating': 3.5,
   'views_count': 51624,
   'production_budget': 49787105},
  {'_id': 'M081',
   'title': 'A Empire',
   'genre': ['Thriller'],
   'duration_minutes': 158,
   'release_year': 2023,
   'rating': 3.2,
   'views_count': 20857,
   'production_budget': 21843745},
  {'_id': 'M082',
   'title': 'Protocol',
   'genre': ['Romance', 'Action', 'Comedy'],
   'duration_minutes': 135,
   'release_year': 2023,
   'rating': 4.0,
   'views_count': 106275,
   'production_budget': 182661326},
  {'_id': 'M083',
   'title': 'Final World',
   'genre': ['Horror'],
   'duration_minutes': 116,
   'release_year': 2023,
   'rating': 1.1,
   'views_count': 147540,
   'production_budget': 9691644},
  {'_id': 'M084',
   'title': 'The Matrix',
   'genre': ['Drama', 'Comedy'],
   'duration_minutes': 141,
   'release_year': 2021,
   'rating': 2.2,
   'views_count': 40998,
   'production_budget': 49636072},
  {'_id': 'M085',
   'title': 'Lost Adventure',
   'genre': ['Action', 'Romance'],
   'duration_minutes': 150,
   'release_year': 2022,
   'rating': 4.4,
   'views_count': 185972,
   'production_budget': 272623780},
  {'_id': 'M086',
   'title': 'Data',
   'genre': ['Thriller', 'Horror', 'Animation'],
   'duration_minutes': 130,
   'release_year': 2021,
   'rating': 2.3,
   'views_count': 41342,
   'production_budget': 25908762},
  {'_id': 'M087',
   'title': 'A Data',
   'genre': ['Action', 'Romance', 'Drama'],
   'duration_minutes': 139,
   'release_year': 2020,
   'rating': 2.7,
   'views_count': 41100,
   'production_budget': 251619945},
  {'_id': 'M088',
   'title': 'Data',
   'genre': ['Romance'],
   'duration_minutes': 146,
   'release_year': 2023,
   'rating': 1.2,
   'views_count': 2689,
   'production_budget': 41797064},
  {'_id': 'M089',
   'title': 'Hidden Data',
   'genre': ['Horror', 'Sci-Fi', 'Romance'],
   'duration_minutes': 107,
   'release_year': 2021,
   'rating': 3.0,
   'views_count': 48176,
   'production_budget': 283777035},
  {'_id': 'M090',
   'title': 'Network',
   'genre': ['Comedy', 'Animation'],
   'duration_minutes': 86,
   'release_year': 2020,
   'rating': 2.6,
   'views_count': 38966,
   'production_budget': 41347239},
  {'_id': 'M091',
   'title': 'Empire',
   'genre': ['Animation', 'Romance'],
   'duration_minutes': 122,
   'release_year': 2022,
   'rating': 2.5,
   'views_count': 48892,
   'production_budget': 10832696},
  {'_id': 'M092',
   'title': 'Infinite Code',
   'genre': ['Comedy', 'Horror'],
   'duration_minutes': 145,
   'release_year': 2021,
   'rating': 2.1,
   'views_count': 56151,
   'production_budget': 16160068},
  {'_id': 'M093',
   'title': 'Digital Code',
   'genre': ['Horror', 'Drama'],
   'duration_minutes': 87,
   'release_year': 2024,
   'rating': 3.8,
   'views_count': 97083,
   'production_budget': 9974518},
  {'_id': 'M094',
   'title': 'Matrix',
   'genre': ['Action', 'Animation'],
   'duration_minutes': 173,
   'release_year': 2020,
   'rating': 1.2,
   'views_count': 48295,

In [115]:
with open(file_path,'r') as file:
    json_data = json.load(file)[collection]
    df_json = pd.json_normalize(json_data)
columnas = list(df_json.columns)
df_processed = df_json.to_json(orient='records')
json_processed = json.loads(df_processed)
json_processed[49]

{'_id': 'M050',
 'title': 'Infinite Protocol',
 'genre': ['Thriller', 'Documentary'],
 'duration_minutes': 96,
 'release_year': 2021,
 'rating': 2.0,
 'views_count': 53173,
 'production_budget': 39370044}

In [110]:
def leer():
    with open(file_path,'r') as file:
        json_data = json.load(file)[collection]
        df_json = pd.json_normalize(json_data)
        return df_json

def convertir_columnas():
    df = leer()
    if collection == "movies":
        data_types = [str, str, object, int, int, float, int, int]
        for column in columnas:
            item = data_types.pop(0)
            df = df.astype({column: item})
        df_processed = df.to_json(orient='records')
        json_processed = json.loads(df_processed)
        return json_processed
    elif collection == "series":
        data_types = [str, str, object, int, object, int, float, int, int]
        for column in columnas:
            item = data_types.pop(0)
            df = df.astype({column: item})
        df_processed = df.to_json(orient='records')
        json_processed = json.loads(df_processed)
        return json_processed

def preparar():
    data = convertir_columnas()
    i = 0
    chunk = data[i:(i+50)]
    for cluster in data:
        cluster = chunk
        if cluster == []:
            return None
        payload_body = {
        'collection': collection,
        'data': cluster
        }
        yield payload_body
        i = i+50
        chunk = data[(i):(i+50)]

def enviar(dictionary: dict):
    response = dictionary
    print(f"¡Se envío correctamente la siguiente información!:\n {response}")
    
        
if __name__ == '__main__':
    for payload_body in preparar():
        enviar(payload_body)

¡Se envío correctamente la siguiente información!:
 {'collection': 'movies', 'data': [{'_id': 'M001', 'title': 'Advanced World', 'genre': ['Sci-Fi', 'Horror', 'Drama'], 'duration_minutes': 179, 'release_year': 2020, 'rating': 3.5, 'views_count': 66721, 'production_budget': 220088717}, {'_id': 'M002', 'title': 'Neural Signal', 'genre': ['Animation', 'Horror'], 'duration_minutes': 146, 'release_year': 2021, 'rating': 2.8, 'views_count': 11128, 'production_budget': 23593231}, {'_id': 'M003', 'title': 'An Stream', 'genre': ['Action'], 'duration_minutes': 102, 'release_year': 2023, 'rating': 1.9, 'views_count': 75949, 'production_budget': 83166461}, {'_id': 'M004', 'title': 'Binary Journey', 'genre': ['Thriller', 'Documentary'], 'duration_minutes': 146, 'release_year': 2022, 'rating': 3.0, 'views_count': 85958, 'production_budget': 46298444}, {'_id': 'M005', 'title': 'Lost Data', 'genre': ['Horror', 'Romance'], 'duration_minutes': 169, 'release_year': 2022, 'rating': 4.7, 'views_count': 56808, 'production_budget': 67293750}, {'_id': 'M006', 'title': 'Ultimate Mystery', 'genre': ['Action', 'Animation', 'Horror'], 'duration_minutes': 157, 'release_year': 2024, 'rating': 1.1, 'views_count': 148876, 'production_budget': 234348717}, {'_id': 'M007', 'title': 'Code', 'genre': ['Comedy', 'Romance'], 'duration_minutes': 136, 'release_year': 2022, 'rating': 3.1, 'views_count': 9228, 'production_budget': 35028167}, {'_id': 'M008', 'title': 'Digital Protocol', 'genre': ['Documentary', 'Romance'], 'duration_minutes': 155, 'release_year': 2023, 'rating': 3.7, 'views_count': 125068, 'production_budget': 49545701}, {'_id': 'M009', 'title': 'Tale', 'genre': ['Drama', 'Horror'], 'duration_minutes': 90, 'release_year': 2023, 'rating': 4.4, 'views_count': 37911, 'production_budget': 146895476}, {'_id': 'M010', 'title': 'An Code 2', 'genre': ['Comedy', 'Romance', 'Action'], 'duration_minutes': 174, 'release_year': 2021, 'rating': 3.5, 'views_count': 78005, 'production_budget': 224671521}, {'_id': 'M011', 'title': 'Algorithm', 'genre': ['Drama', 'Animation', 'Horror'], 'duration_minutes': 81, 'release_year': 2023, 'rating': 2.7, 'views_count': 92634, 'production_budget': 20512281}, {'_id': 'M012', 'title': 'Quest 5', 'genre': ['Comedy'], 'duration_minutes': 104, 'release_year': 2023, 'rating': 2.4, 'views_count': 59155, 'production_budget': 36408859}, {'_id': 'M013', 'title': 'Mystery', 'genre': ['Documentary', 'Drama'], 'duration_minutes': 178, 'release_year': 2020, 'rating': 1.6, 'views_count': 61328, 'production_budget': 16064411}, {'_id': 'M014', 'title': 'Kingdom', 'genre': ['Thriller', 'Action'], 'duration_minutes': 122, 'release_year': 2021, 'rating': 4.2, 'views_count': 138918, 'production_budget': 202395249}, {'_id': 'M015', 'title': 'Quantum Code', 'genre': ['Animation', 'Documentary', 'Sci-Fi'], 'duration_minutes': 177, 'release_year': 2021, 'rating': 2.4, 'views_count': 13807, 'production_budget': 227198245}, {'_id': 'M016', 'title': 'A Database', 'genre': ['Drama', 'Documentary'], 'duration_minutes': 95, 'release_year': 2023, 'rating': 3.0, 'views_count': 81858, 'production_budget': 6729979}, {'_id': 'M017', 'title': 'Adventure', 'genre': ['Action', 'Documentary', 'Horror'], 'duration_minutes': 97, 'release_year': 2020, 'rating': 4.6, 'views_count': 132014, 'production_budget': 50839665}, {'_id': 'M018', 'title': 'Mystery', 'genre': ['Comedy', 'Action'], 'duration_minutes': 84, 'release_year': 2023, 'rating': 3.6, 'views_count': 81531, 'production_budget': 158431993}, {'_id': 'M019', 'title': 'Final Stream', 'genre': ['Action'], 'duration_minutes': 83, 'release_year': 2023, 'rating': 2.3, 'views_count': 144211, 'production_budget': 114952801}, {'_id': 'M020', 'title': 'Quest', 'genre': ['Thriller', 'Action', 'Drama'], 'duration_minutes': 108, 'release_year': 2022, 'rating': 3.1, 'views_count': 47873, 'production_budget': 250548961}, {'_id': 'M021', 'title': 'Tale', 'genre': ['Drama', 'Horror'], 'duration_minutes': 148, 'release_year': 2020, 'rating': 4.9, 'views_count': 168298, 'production_budget': 62478620}, {'_id': 'M022', 'title': 'Quantum System', 'genre': ['Horror'], 'duration_minutes': 147, 'release_year': 2023, 'rating': 4.7, 'views_count': 116580, 'production_budget': 73128204}, {'_id': 'M023', 'title': 'Smart Story', 'genre': ['Horror'], 'duration_minutes': 147, 'release_year': 2022, 'rating': 3.3, 'views_count': 36200, 'production_budget': 12509378}, {'_id': 'M024', 'title': 'First Mystery', 'genre': ['Horror'], 'duration_minutes': 159, 'release_year': 2020, 'rating': 4.2, 'views_count': 117924, 'production_budget': 146907831}, {'_id': 'M025', 'title': 'An Protocol', 'genre': ['Comedy'], 'duration_minutes': 162, 'release_year': 2020, 'rating': 4.0, 'views_count': 26519, 'production_budget': 49021276}, {'_id': 'M026', 'title': 'Lost Kingdom', 'genre': ['Documentary', 'Drama', 'Action'], 'duration_minutes': 163, 'release_year': 2024, 'rating': 2.6, 'views_count': 113230, 'production_budget': 90625130}, {'_id': 'M027', 'title': 'Quantum Story', 'genre': ['Thriller', 'Horror', 'Sci-Fi'], 'duration_minutes': 128, 'release_year': 2023, 'rating': 1.2, 'views_count': 19816, 'production_budget': 150283990}, {'_id': 'M028', 'title': 'Final Kingdom', 'genre': ['Comedy', 'Horror', 'Drama'], 'duration_minutes': 175, 'release_year': 2023, 'rating': 1.7, 'views_count': 87291, 'production_budget': 8816404}, {'_id': 'M029', 'title': 'System', 'genre': ['Documentary'], 'duration_minutes': 123, 'release_year': 2023, 'rating': 1.8, 'views_count': 27793, 'production_budget': 30738350}, {'_id': 'M030', 'title': 'Database 4', 'genre': ['Drama', 'Action'], 'duration_minutes': 145, 'release_year': 2020, 'rating': 1.3, 'views_count': 98063, 'production_budget': 100987742}, {'_id': 'M031', 'title': 'Empire', 'genre': ['Action', 'Animation', 'Drama'], 'duration_minutes': 104, 'release_year': 2020, 'rating': 4.9, 'views_count': 114316, 'production_budget': 184475405}, {'_id': 'M032', 'title': 'A Code', 'genre': ['Thriller', 'Action'], 'duration_minutes': 133, 'release_year': 2024, 'rating': 3.4, 'views_count': 83014, 'production_budget': 283617949}, {'_id': 'M033', 'title': 'Dark Stream', 'genre': ['Action', 'Animation'], 'duration_minutes': 119, 'release_year': 2023, 'rating': 2.9, 'views_count': 54865, 'production_budget': 193790052}, {'_id': 'M034', 'title': 'Stream', 'genre': ['Romance', 'Sci-Fi', 'Action'], 'duration_minutes': 151, 'release_year': 2020, 'rating': 4.9, 'views_count': 41348, 'production_budget': 122112109}, {'_id': 'M035', 'title': 'Lost System 5', 'genre': ['Thriller', 'Romance'], 'duration_minutes': 112, 'release_year': 2021, 'rating': 1.8, 'views_count': 64414, 'production_budget': 2127388}, {'_id': 'M036', 'title': 'Quest', 'genre': ['Romance', 'Animation'], 'duration_minutes': 100, 'release_year': 2020, 'rating': 2.9, 'views_count': 90335, 'production_budget': 12670028}, {'_id': 'M037', 'title': 'Quest', 'genre': ['Animation', 'Comedy', 'Documentary'], 'duration_minutes': 90, 'release_year': 2022, 'rating': 1.2, 'views_count': 13250, 'production_budget': 33987762}, {'_id': 'M038', 'title': 'Data', 'genre': ['Animation', 'Documentary'], 'duration_minutes': 161, 'release_year': 2021, 'rating': 3.6, 'views_count': 47672, 'production_budget': 15316213}, {'_id': 'M039', 'title': 'Lost Cloud', 'genre': ['Horror', 'Drama', 'Action'], 'duration_minutes': 103, 'release_year': 2020, 'rating': 2.8, 'views_count': 48310, 'production_budget': 202148811}, {'_id': 'M040', 'title': 'Quest', 'genre': ['Comedy', 'Documentary', 'Drama'], 'duration_minutes': 171, 'release_year': 2022, 'rating': 2.2, 'views_count': 52925, 'production_budget': 1600669}, {'_id': 'M041', 'title': 'Infinite Story', 'genre': ['Horror', 'Thriller'], 'duration_minutes': 117, 'release_year': 2021, 'rating': 4.2, 'views_count': 129104, 'production_budget': 186923029}, {'_id': 'M042', 'title': 'Advanced System 2', 'genre': ['Documentary'], 'duration_minutes': 163, 'release_year': 2020, 'rating': 3.3, 'views_count': 44583, 'production_budget': 42856949}, {'_id': 'M043', 'title': 'Hidden Empire', 'genre': ['Horror'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 4.1, 'views_count': 290064, 'production_budget': 128140036}, {'_id': 'M044', 'title': 'Cyber Cloud 4', 'genre': ['Animation', 'Thriller'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 3.3, 'views_count': 8992, 'production_budget': 8120314}, {'_id': 'M045', 'title': 'First Database', 'genre': ['Animation', 'Action'], 'duration_minutes': 123, 'release_year': 2023, 'rating': 3.1, 'views_count': 115282, 'production_budget': 182644208}, {'_id': 'M046', 'title': 'Binary Signal', 'genre': ['Animation', 'Documentary', 'Thriller'], 'duration_minutes': 147, 'release_year': 2023, 'rating': 1.9, 'views_count': 18247, 'production_budget': 24000248}, {'_id': 'M047', 'title': 'Story', 'genre': ['Drama'], 'duration_minutes': 120, 'release_year': 2023, 'rating': 3.3, 'views_count': 5974, 'production_budget': 18448764}, {'_id': 'M048', 'title': 'Tale', 'genre': ['Horror', 'Romance', 'Documentary'], 'duration_minutes': 104, 'release_year': 2021, 'rating': 4.9, 'views_count': 178486, 'production_budget': 59289648}, {'_id': 'M049', 'title': 'Neural Cloud 2', 'genre': ['Drama', 'Sci-Fi', 'Action'], 'duration_minutes': 126, 'release_year': 2020, 'rating': 3.7, 'views_count': 33051, 'production_budget': 135871052}, {'_id': 'M050', 'title': 'Infinite Protocol', 'genre': ['Thriller', 'Documentary'], 'duration_minutes': 96, 'release_year': 2021, 'rating': 2.0, 'views_count': 53173, 'production_budget': 39370044}]}
¡Se envío correctamente la siguiente información!:
 {'collection': 'movies', 'data': [{'_id': 'M051', 'title': 'A Algorithm', 'genre': ['Animation'], 'duration_minutes': 155, 'release_year': 2022, 'rating': 4.8, 'views_count': 136410, 'production_budget': 106311259}, {'_id': 'M052', 'title': 'Adventure', 'genre': ['Horror', 'Thriller', 'Sci-Fi'], 'duration_minutes': 120, 'release_year': 2021, 'rating': 3.9, 'views_count': 94063, 'production_budget': 193008798}, {'_id': 'M053', 'title': 'Infinite Empire', 'genre': ['Action'], 'duration_minutes': 162, 'release_year': 2022, 'rating': 1.9, 'views_count': 50863, 'production_budget': 296179703}, {'_id': 'M054', 'title': 'Binary Stream', 'genre': ['Action', 'Animation', 'Documentary'], 'duration_minutes': 98, 'release_year': 2021, 'rating': 4.6, 'views_count': 17832, 'production_budget': 122289319}, {'_id': 'M055', 'title': 'Infinite Adventure', 'genre': ['Thriller'], 'duration_minutes': 142, 'release_year': 2023, 'rating': 3.6, 'views_count': 121651, 'production_budget': 37909361}, {'_id': 'M056', 'title': 'Binary Journey', 'genre': ['Thriller', 'Action'], 'duration_minutes': 88, 'release_year': 2023, 'rating': 3.6, 'views_count': 105627, 'production_budget': 140493022}, {'_id': 'M057', 'title': 'Journey', 'genre': ['Drama', 'Sci-Fi'], 'duration_minutes': 149, 'release_year': 2022, 'rating': 1.9, 'views_count': 38409, 'production_budget': 213938522}, {'_id': 'M058', 'title': 'Last Quest', 'genre': ['Documentary', 'Animation', 'Romance'], 'duration_minutes': 173, 'release_year': 2020, 'rating': 3.6, 'views_count': 53146, 'production_budget': 20440772}, {'_id': 'M059', 'title': 'System', 'genre': ['Sci-Fi', 'Thriller', 'Drama'], 'duration_minutes': 146, 'release_year': 2020, 'rating': 1.5, 'views_count': 63578, 'production_budget': 80650718}, {'_id': 'M060', 'title': 'Dark Kingdom', 'genre': ['Thriller', 'Sci-Fi'], 'duration_minutes': 122, 'release_year': 2020, 'rating': 4.9, 'views_count': 196906, 'production_budget': 107714280}, {'_id': 'M061', 'title': 'An Cloud', 'genre': ['Drama', 'Comedy', 'Action'], 'duration_minutes': 99, 'release_year': 2022, 'rating': 4.6, 'views_count': 58038, 'production_budget': 181262622}, {'_id': 'M062', 'title': 'Secret Empire', 'genre': ['Horror'], 'duration_minutes': 136, 'release_year': 2024, 'rating': 1.1, 'views_count': 113496, 'production_budget': 45559979}, {'_id': 'M063', 'title': 'Neural Cloud', 'genre': ['Sci-Fi', 'Drama'], 'duration_minutes': 104, 'release_year': 2024, 'rating': 4.5, 'views_count': 241308, 'production_budget': 52788131}, {'_id': 'M064', 'title': 'Virtual Adventure', 'genre': ['Drama', 'Action'], 'duration_minutes': 113, 'release_year': 2024, 'rating': 4.4, 'views_count': 99105, 'production_budget': 99191442}, {'_id': 'M065', 'title': 'Final Story', 'genre': ['Documentary', 'Romance', 'Sci-Fi'], 'duration_minutes': 102, 'release_year': 2024, 'rating': 1.9, 'views_count': 107506, 'production_budget': 92334091}, {'_id': 'M066', 'title': 'Last World', 'genre': ['Animation'], 'duration_minutes': 134, 'release_year': 2024, 'rating': 4.1, 'views_count': 139206, 'production_budget': 232940727}, {'_id': 'M067', 'title': 'Smart World', 'genre': ['Documentary', 'Romance', 'Sci-Fi'], 'duration_minutes': 126, 'release_year': 2023, 'rating': 4.0, 'views_count': 125397, 'production_budget': 233435578}, {'_id': 'M068', 'title': 'Protocol', 'genre': ['Comedy', 'Thriller', 'Horror'], 'duration_minutes': 169, 'release_year': 2024, 'rating': 4.2, 'views_count': 110097, 'production_budget': 100149438}, {'_id': 'M069', 'title': 'Last World', 'genre': ['Horror'], 'duration_minutes': 119, 'release_year': 2022, 'rating': 4.0, 'views_count': 12355, 'production_budget': 39301506}, {'_id': 'M070', 'title': 'Lost Adventure', 'genre': ['Drama', 'Sci-Fi'], 'duration_minutes': 171, 'release_year': 2020, 'rating': 1.7, 'views_count': 5512, 'production_budget': 218689270}, {'_id': 'M071', 'title': 'Cyber Tale', 'genre': ['Sci-Fi', 'Drama', 'Comedy'], 'duration_minutes': 102, 'release_year': 2023, 'rating': 4.3, 'views_count': 292824, 'production_budget': 139504878}, {'_id': 'M072', 'title': 'Secret Signal', 'genre': ['Romance'], 'duration_minutes': 125, 'release_year': 2022, 'rating': 1.6, 'views_count': 60180, 'production_budget': 8844926}, {'_id': 'M073', 'title': 'System', 'genre': ['Documentary', 'Animation', 'Action'], 'duration_minutes': 141, 'release_year': 2021, 'rating': 1.3, 'views_count': 12675, 'production_budget': 167251523}, {'_id': 'M074', 'title': 'Digital Database', 'genre': ['Comedy'], 'duration_minutes': 146, 'release_year': 2022, 'rating': 3.2, 'views_count': 8998, 'production_budget': 29227591}, {'_id': 'M075', 'title': 'Neural Journey', 'genre': ['Sci-Fi', 'Thriller', 'Romance'], 'duration_minutes': 125, 'release_year': 2020, 'rating': 4.2, 'views_count': 84468, 'production_budget': 296040480}, {'_id': 'M076', 'title': 'The Journey', 'genre': ['Thriller', 'Documentary', 'Animation'], 'duration_minutes': 166, 'release_year': 2020, 'rating': 2.4, 'views_count': 78189, 'production_budget': 27396354}, {'_id': 'M077', 'title': 'Signal', 'genre': ['Romance'], 'duration_minutes': 101, 'release_year': 2021, 'rating': 4.5, 'views_count': 97638, 'production_budget': 203590741}, {'_id': 'M078', 'title': 'Algorithm', 'genre': ['Comedy', 'Romance', 'Documentary'], 'duration_minutes': 155, 'release_year': 2024, 'rating': 1.6, 'views_count': 28957, 'production_budget': 13524987}, {'_id': 'M079', 'title': 'Secret Algorithm', 'genre': ['Thriller'], 'duration_minutes': 156, 'release_year': 2022, 'rating': 3.8, 'views_count': 44993, 'production_budget': 46138210}, {'_id': 'M080', 'title': 'Digital Empire', 'genre': ['Comedy'], 'duration_minutes': 99, 'release_year': 2022, 'rating': 3.5, 'views_count': 51624, 'production_budget': 49787105}, {'_id': 'M081', 'title': 'A Empire', 'genre': ['Thriller'], 'duration_minutes': 158, 'release_year': 2023, 'rating': 3.2, 'views_count': 20857, 'production_budget': 21843745}, {'_id': 'M082', 'title': 'Protocol', 'genre': ['Romance', 'Action', 'Comedy'], 'duration_minutes': 135, 'release_year': 2023, 'rating': 4.0, 'views_count': 106275, 'production_budget': 182661326}, {'_id': 'M083', 'title': 'Final World', 'genre': ['Horror'], 'duration_minutes': 116, 'release_year': 2023, 'rating': 1.1, 'views_count': 147540, 'production_budget': 9691644}, {'_id': 'M084', 'title': 'The Matrix', 'genre': ['Drama', 'Comedy'], 'duration_minutes': 141, 'release_year': 2021, 'rating': 2.2, 'views_count': 40998, 'production_budget': 49636072}, {'_id': 'M085', 'title': 'Lost Adventure', 'genre': ['Action', 'Romance'], 'duration_minutes': 150, 'release_year': 2022, 'rating': 4.4, 'views_count': 185972, 'production_budget': 272623780}, {'_id': 'M086', 'title': 'Data', 'genre': ['Thriller', 'Horror', 'Animation'], 'duration_minutes': 130, 'release_year': 2021, 'rating': 2.3, 'views_count': 41342, 'production_budget': 25908762}, {'_id': 'M087', 'title': 'A Data', 'genre': ['Action', 'Romance', 'Drama'], 'duration_minutes': 139, 'release_year': 2020, 'rating': 2.7, 'views_count': 41100, 'production_budget': 251619945}, {'_id': 'M088', 'title': 'Data', 'genre': ['Romance'], 'duration_minutes': 146, 'release_year': 2023, 'rating': 1.2, 'views_count': 2689, 'production_budget': 41797064}, {'_id': 'M089', 'title': 'Hidden Data', 'genre': ['Horror', 'Sci-Fi', 'Romance'], 'duration_minutes': 107, 'release_year': 2021, 'rating': 3.0, 'views_count': 48176, 'production_budget': 283777035}, {'_id': 'M090', 'title': 'Network', 'genre': ['Comedy', 'Animation'], 'duration_minutes': 86, 'release_year': 2020, 'rating': 2.6, 'views_count': 38966, 'production_budget': 41347239}, {'_id': 'M091', 'title': 'Empire', 'genre': ['Animation', 'Romance'], 'duration_minutes': 122, 'release_year': 2022, 'rating': 2.5, 'views_count': 48892, 'production_budget': 10832696}, {'_id': 'M092', 'title': 'Infinite Code', 'genre': ['Comedy', 'Horror'], 'duration_minutes': 145, 'release_year': 2021, 'rating': 2.1, 'views_count': 56151, 'production_budget': 16160068}, {'_id': 'M093', 'title': 'Digital Code', 'genre': ['Horror', 'Drama'], 'duration_minutes': 87, 'release_year': 2024, 'rating': 3.8, 'views_count': 97083, 'production_budget': 9974518}, {'_id': 'M094', 'title': 'Matrix', 'genre': ['Action', 'Animation'], 'duration_minutes': 173, 'release_year': 2020, 'rating': 1.2, 'views_count': 48295, 'production_budget': 250209902}, {'_id': 'M095', 'title': 'Digital Tale', 'genre': ['Documentary', 'Comedy', 'Romance'], 'duration_minutes': 131, 'release_year': 2024, 'rating': 3.8, 'views_count': 104163, 'production_budget': 27080387}, {'_id': 'M096', 'title': 'Final Mystery 5', 'genre': ['Romance', 'Comedy', 'Action'], 'duration_minutes': 85, 'release_year': 2022, 'rating': 2.0, 'views_count': 80921, 'production_budget': 134466599}, {'_id': 'M097', 'title': 'Dark Stream', 'genre': ['Horror', 'Comedy'], 'duration_minutes': 131, 'release_year': 2020, 'rating': 4.9, 'views_count': 152164, 'production_budget': 65465290}, {'_id': 'M098', 'title': 'Digital Data', 'genre': ['Horror', 'Thriller', 'Romance'], 'duration_minutes': 142, 'release_year': 2022, 'rating': 2.6, 'views_count': 13908, 'production_budget': 41421645}, {'_id': 'M099', 'title': 'Algorithm', 'genre': ['Animation', 'Romance', 'Action'], 'duration_minutes': 159, 'release_year': 2022, 'rating': 2.3, 'views_count': 53649, 'production_budget': 195742202}, {'_id': 'M100', 'title': 'Mystery', 'genre': ['Animation', 'Drama', 'Comedy'], 'duration_minutes': 145, 'release_year': 2022, 'rating': 2.5, 'views_count': 85093, 'production_budget': 1818805}]}
¡Se envío correctamente la siguiente información!:

In [105]:
"""def comprobar(dictionary:dict):
    if data == 'movies':
        llaves_permitidas = ['_id','title','genre','duration_minutes','release_year','rating','views_count','production_budget']
        for llave in llaves_permitidas:
            if llave in dictionary.keys():
                print("It meets the requirements")
                continue
            else:
                raise Exception("The dictionary does not meet the required keys")
    elif data == 'series':
        llaves_permitidas = ['_id','title','genre','seasons','episodes_per_season','avg_episode_duration','rating','total_views', 'production_budget']
        for llave in llaves_permitidas:
            if llave in dictionary.keys():
                print("It meets the requirements")
                continue
            else:
                raise Exception("The dictionary does not meet the required keys")"""

'def comprobar(dictionary:dict):\n    if data == \'movies\':\n        llaves_permitidas = [\'_id\',\'title\',\'genre\',\'duration_minutes\',\'release_year\',\'rating\',\'views_count\',\'production_budget\']\n        for llave in llaves_permitidas:\n            if llave in dictionary.keys():\n                print("It meets the requirements")\n                continue\n            else:\n                raise Exception("The dictionary does not meet the required keys")\n    elif data == \'series\':\n        llaves_permitidas = [\'_id\',\'title\',\'genre\',\'seasons\',\'episodes_per_season\',\'avg_episode_duration\',\'rating\',\'total_views\', \'production_budget\']\n        for llave in llaves_permitidas:\n            if llave in dictionary.keys():\n                print("It meets the requirements")\n                continue\n            else:\n                raise Exception("The dictionary does not meet the required keys")'